export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: string;
  category?: string;
  body: string[]; // paragraphs / headings (use ##, -, > prefixes)
};

export const POSTS: BlogPost[] = [
  {
    slug: "jeetbuzz-registration-guide-bangladesh",
    title: "JeetBuzz Registration Guide for Bangladesh (2026)",
    category: "Registration",
    description:
      "Step-by-step JeetBuzz signup for Bangladeshi players — phone, email, bKash setup and verification, in Bengali and English.",
    date: "2026-06-12",
    readTime: "6 min",
    body: [
      "## ১ মিনিটে সারসংক্ষেপ",
      "JeetBuzz এ একাউন্ট খুলতে আপনার একটি বৈধ মোবাইল নম্বর, একটি ইমেইল ঠিকানা এবং bKash/Nagad/Rocket এর মত একটি পেমেন্ট মাধ্যম প্রয়োজন। পুরো প্রক্রিয়াটি সাধারণত ২–৩ মিনিটের মধ্যে শেষ হয়।",
      "## Step 1 — Open the official site",
      "Use the outbound button on this page. Avoid third-party mirrors or APK files shared on Telegram — they're a common source of phishing.",
      "## Step 2 — Click Sign Up",
      "Choose phone or email registration. For Bangladesh, phone registration with OTP is usually faster.",
      "## Step 3 — Fill the form",
      "Enter a strong password, your country (Bangladesh), and currency (BDT). Promo codes can usually be applied at this step.",
      "## Step 4 — Verify",
      "Confirm the OTP sent to your phone. For higher withdrawal limits you may later be asked for KYC documents (NID + selfie).",
      "## Step 5 — Make your first deposit",
      "Choose bKash, Nagad or Rocket from the cashier. See our payments guide for minimums and fees.",
      "> Last verified: June 2026. Terms can change — always check the official site for current minimums and bonuses.",
    ],
  },
  {
    slug: "jeetbuzz-login-guide",
    title: "JeetBuzz Login Guide — Safe Access from Bangladesh",
    description:
      "How to log in to JeetBuzz from Bangladesh, what to do if you can't access the site and how to spot fake mirror pages.",
    date: "2026-06-10",
    readTime: "4 min",
    body: [
      "## সংক্ষেপে",
      "JeetBuzz এ লগইন করতে আপনার রেজিস্টার্ড ফোন/ইমেইল এবং পাসওয়ার্ড লাগবে। লগইন সবসময় অফিসিয়াল সাইট থেকে করুন।",
      "## How to log in",
      "Use the Login button on the official JeetBuzz site. Enter your registered phone or email and password.",
      "## Forgot your password?",
      "Use 'Forgot password' on the official site to receive a reset link via SMS or email.",
      "## Can't access the site?",
      "Some ISPs throttle gambling domains. Try a stable connection or contact official support — never enter your credentials on third-party 'mirror' sites.",
      "## Red flags to avoid",
      "- Sites asking you to 'login here' on a domain that isn't JeetBuzz",
      "- APKs from random Telegram groups",
      "- Anyone DM'ing you offering to 'recover' your account",
    ],
  },
  {
    slug: "jeetbuzz-apk-download-safe-guide",
    title: "JeetBuzz APK Download — Safe Install Guide",
    description:
      "How to install the JeetBuzz Android app safely from the official site, with Android security tips for Bangladeshi users.",
    date: "2026-06-08",
    readTime: "5 min",
    body: [
      "## We don't host the APK",
      "GetJeetBuzz never hosts the APK file. Always download it from the official JeetBuzz site to avoid tampered builds.",
      "## Install steps",
      "1. Open the official site on your Android browser.",
      "2. Tap the App / APK download button.",
      "3. Allow 'Install from unknown sources' for your browser when prompted.",
      "4. Open the downloaded file and tap Install.",
      "## After install",
      "Log in with your existing JeetBuzz credentials. Enable biometric login if available for faster, safer access.",
      "> iOS users currently access JeetBuzz via the mobile web app (no native iOS app at the time of writing).",
    ],
  },
  {
    slug: "jeetbuzz-bonus-terms-explained",
    title: "JeetBuzz Bonus Terms — What the Fine Print Actually Means",
    description:
      "Wagering requirements, max bet, eligible games and time limits — a plain-English breakdown of JeetBuzz bonus terms.",
    date: "2026-06-05",
    readTime: "7 min",
    body: [
      "## Wagering requirements",
      "Most JeetBuzz bonuses carry a wagering requirement, e.g. 15x. That means a 1,000 BDT bonus needs 15,000 BDT in qualifying bets before withdrawal.",
      "## Max bet rule",
      "While a bonus is active, single-bet caps may apply. Exceeding them can void the bonus.",
      "## Eligible games",
      "Sports and slots usually contribute differently. Live casino often contributes very little or nothing to wagering.",
      "## Time limits",
      "Bonuses commonly expire 7–30 days after activation. Check the offer page before opting in.",
      "## Our take",
      "Bonuses are useful if you'd be betting anyway. Don't chase wagering — bet within your bankroll, ignore the bonus if terms don't suit you.",
    ],
  },
  {
    slug: "jeetbuzz-bkash-nagad-deposit-guide",
    title: "JeetBuzz Deposits with bKash, Nagad & Rocket",
    description:
      "Minimums, fees and processing times for bKash, Nagad and Rocket deposits on JeetBuzz — plus fixes for common errors.",
    date: "2026-06-02",
    readTime: "6 min",
    body: [
      "## At a glance",
      "bKash, Nagad and Rocket are the three most popular deposit methods for Bangladeshi JeetBuzz users. Deposits are usually instant; withdrawals typically clear within hours.",
      "## How to deposit (bKash example)",
      "1. Log into JeetBuzz and open the Cashier.",
      "2. Choose bKash and enter the amount.",
      "3. Send money from your bKash app to the displayed merchant number with the transaction reference.",
      "4. Paste the bKash TrxID back into the form and submit.",
      "## Common errors",
      "- Wrong TrxID — double-check before submitting.",
      "- Sending to a personal number instead of the merchant — funds may be lost.",
      "- Using someone else's wallet — JeetBuzz requires the wallet to match the account holder.",
      "## Withdrawals",
      "Withdraw to the same wallet used for deposit. KYC may be required for the first cash-out.",
    ],
  },
  {
    slug: "jeetbuzz-live-cricket-betting-guide",
    title: "JeetBuzz Live Cricket Betting — A Practical Guide",
    description:
      "Markets, in-play tips and bankroll management for live cricket betting on JeetBuzz, with BPL and IPL coverage notes.",
    date: "2026-05-28",
    readTime: "8 min",
    body: [
      "## Why live cricket",
      "JeetBuzz's cricket coverage is one of the deepest available to Bangladeshi players — BPL, IPL, T20 World Cup, internationals and county games.",
      "## Markets worth knowing",
      "- Match winner / handicap",
      "- Over runs (e.g. runs in the first 6)",
      "- Top batter / bowler",
      "- Method of dismissal",
      "## Live bet tips",
      "Pre-decide a per-match budget. In-play odds move fast — avoid revenge bets after a wicket.",
      "## Responsible gaming",
      "Set deposit and loss limits in your account. If betting stops being fun, take a break.",
    ],
  },
  {
    slug: "is-jeetbuzz-safe-bangladesh",
    title: "Is JeetBuzz Safe for Bangladeshi Players? An Independent Look",
    description:
      "Licensing, payments, withdrawals, support and red flags — our honest take on JeetBuzz safety for Bangladesh users.",
    date: "2026-05-22",
    readTime: "7 min",
    body: [
      "## Licensing",
      "JeetBuzz operates under an offshore license. That's industry-standard for international books serving South Asia, but doesn't replace local regulation.",
      "## Payments",
      "Local payment rails (bKash, Nagad, Rocket) and quick withdrawals are positive signs.",
      "## Support",
      "24/7 live chat in English and Bengali. Response times in our checks were good.",
      "## Red flags we'd watch",
      "- Promo terms change without much notice — re-read before opting in.",
      "- Phishing 'mirror' sites are common. Always start from a verified link.",
      "## Verdict",
      "JeetBuzz is one of the more credible options serving Bangladesh today, with the usual offshore-book caveats. Bet within your means.",
    ],
  },
  {
    slug: "jeetbuzz-affiliate-program-explained",
    title: "JeetBuzz Affiliate Program Explained",
    category: "Affiliate",
    description:
      "Commission structure, payout cycles and cookie window for the JeetBuzz affiliate program — what to expect as a partner.",
    date: "2026-05-18",
    readTime: "5 min",
    body: [
      "## Who it's for",
      "Content creators, tipsters and site owners serving the Bangladesh / South Asia sports betting audience.",
      "## Commission models",
      "Revenue share (typically 20–45% depending on volume) and CPA on qualified deposits are usually available — confirm current numbers with the official program.",
      "## Payments",
      "Monthly payouts in popular wallets and crypto. Minimums apply.",
      "## Tracking",
      "Each affiliate gets a unique link with cookie-based tracking (commonly 30 days). Sub-IDs let you split traffic sources.",
    ],
  },
];

export function getPost(slug: string) {
  return POSTS.find((p) => p.slug === slug);
}

// Additional posts (Phase 2 SEO expansion). Concise but unique articles.
const EXTRA: BlogPost[] = [
  {
    slug: "jeetbuzz-bpl-betting-tips",
    title: "JeetBuzz BPL Betting Tips for Bangladesh Fans",
    category: "Live Cricket",
    description: "Practical BPL betting tips for JeetBuzz — markets, in-play tactics and bankroll for Bangladesh Premier League.",
    date: "2026-06-18",
    readTime: "6 min",
    body: [
      "## BPL is JeetBuzz's biggest event",
      "Every BPL season is the peak of cricket betting volume on JeetBuzz Bangladesh. Liquidity is deep, in-play odds move fast.",
      "## Markets to focus on",
      "- Match winner — simplest, lowest house edge",
      "- Top batter / bowler — value when team news drops late",
      "- Runs in first 6 overs — strong powerplay signal",
      "## In-play tactics",
      "Pre-set your bet size. Don't chase a wicket-fall move — the algorithm reprices in seconds.",
      "## Bankroll",
      "Allocate per-match, not per-session. A single BPL match should never exceed 2–5% of your bankroll.",
      "## Stay legal and responsible",
      "Set deposit limits before the season. Read our Responsible Gaming guide.",
    ],
  },
  {
    slug: "jeetbuzz-ipl-coverage",
    title: "JeetBuzz IPL Coverage and Best Markets",
    category: "Live Cricket",
    description: "How JeetBuzz covers the IPL — markets, streaming, and which bets carry the best value for South Asia players.",
    date: "2026-06-15",
    readTime: "5 min",
    body: [
      "## IPL on JeetBuzz",
      "IPL is the second peak of cricket betting traffic after BPL. JeetBuzz typically offers 200+ markets per match.",
      "## Best value markets",
      "- Method of dismissal in first wicket",
      "- 5-over runs",
      "- Top batter (in selected teams)",
      "## Live streaming",
      "Depends on rights and region. Scoreboards are always available.",
      "## Watch for line moves",
      "Sharp moves before toss often reflect team news. Bet ahead of the toss if you spot a strong indicator.",
    ],
  },
  {
    slug: "jeetbuzz-welcome-bonus-walkthrough",
    title: "JeetBuzz Welcome Bonus — Step-by-Step Walkthrough",
    category: "Bonus",
    description: "How to claim the JeetBuzz welcome bonus correctly — opt-in, deposit, wagering and how to avoid voiding it.",
    date: "2026-06-14",
    readTime: "5 min",
    body: [
      "## Opt in first",
      "Choose the welcome bonus from the Promotions page BEFORE depositing. After depositing, you usually cannot retroactively apply it.",
      "## Deposit smart",
      "Match the suggested minimum exactly. Some bonuses cap the maximum bonus to the first deposit, so a single larger deposit > multiple small ones.",
      "## Wagering",
      "Most welcome bonuses carry 15x wagering. Sportsbook bets at odds ≥ 1.80 usually count.",
      "## Don't void",
      "- Don't exceed the max bet while a bonus is active",
      "- Don't bet on excluded markets",
      "- Don't withdraw before completing wagering",
    ],
  },
  {
    slug: "jeetbuzz-cashback-explained",
    title: "JeetBuzz Cashback Promotions Explained",
    category: "Bonus",
    description: "What JeetBuzz cashback offers actually pay, how often, and when they are worth opting into.",
    date: "2026-06-13",
    readTime: "4 min",
    body: [
      "## What cashback is",
      "A percentage of net losses returned to your account each week. Usually with low or no wagering.",
      "## When it is worth it",
      "If you bet regularly anyway. If you bet rarely, the cashback rarely covers a single bad week.",
      "## VIP tie-in",
      "Cashback percentage usually scales with VIP tier. See our VIP Program guide.",
    ],
  },
  {
    slug: "jeetbuzz-2fa-setup-bangladesh",
    title: "JeetBuzz 2FA Setup for Bangladesh Players",
    category: "Security",
    description: "How to enable two-factor authentication on JeetBuzz and why it matters for Bangladesh players.",
    date: "2026-06-11",
    readTime: "4 min",
    body: [
      "## Why 2FA",
      "Even a strong password can be phished. 2FA blocks remote logins from stolen credentials.",
      "## Enable it",
      "Account > Security > Two-Factor. Pick SMS at minimum. Confirm the code.",
      "## What to do if you change SIM",
      "Update your registered number BEFORE swapping SIMs. Otherwise you may lose access.",
    ],
  },
  {
    slug: "jeetbuzz-phishing-red-flags",
    title: "JeetBuzz Phishing Red Flags — How to Spot Fake Sites",
    category: "Security",
    description: "Common phishing patterns targeting JeetBuzz Bangladesh users — domains, Telegram scams and fake APKs.",
    date: "2026-06-09",
    readTime: "5 min",
    body: [
      "## Domain tricks",
      "Lookalike domains with hyphens, extra words or slightly different TLDs are the most common. Always check the URL bar.",
      "## Telegram traps",
      "Anyone DMing you to 'recover your account' or 'unlock withdrawals' is a scammer. JeetBuzz support lives inside live chat.",
      "## Fake APKs",
      "APKs shared in random groups can carry credential-stealing malware. Only install from the official site.",
      "## If you click",
      "If you entered a password on a fake site, change it immediately and enable 2FA.",
    ],
  },
  {
    slug: "jeetbuzz-kyc-process",
    title: "JeetBuzz KYC Process — What Documents Are Needed",
    category: "Registration",
    description: "What KYC looks like on JeetBuzz Bangladesh — NID, selfie, processing times and tips for fast approval.",
    date: "2026-06-07",
    readTime: "4 min",
    body: [
      "## What KYC is",
      "Identity verification required before your first withdrawal. Standard for any regulated operator.",
      "## Documents",
      "- NID front and back",
      "- Selfie holding the NID",
      "- Proof of registered phone",
      "## Approval time",
      "Usually 1–24 hours. Avoid blurry photos to speed it up.",
    ],
  },
  {
    slug: "jeetbuzz-livestream-tips",
    title: "JeetBuzz Live Stream Tips for Cricket Fans",
    category: "Live Cricket",
    description: "How to use JeetBuzz live streams for cricket without burning your mobile data — quality settings and fallback options.",
    date: "2026-06-06",
    readTime: "4 min",
    body: [
      "## Quality settings",
      "Default is auto. Switch to 480p on mobile data to save 50%+ bandwidth without losing the action.",
      "## Audio-only fallback",
      "Some matches allow audio commentary plus the live scorecard — perfect for office hours.",
      "## Why streams sometimes fail",
      "Rights restrictions, not technical issues. Use the scoreboard plus your TV.",
    ],
  },
  {
    slug: "jeetbuzz-android-update",
    title: "JeetBuzz Android App — Updating Without Losing Data",
    category: "APK",
    description: "How to update the JeetBuzz Android APK safely, with login and bet history intact.",
    date: "2026-06-04",
    readTime: "3 min",
    body: [
      "## When to update",
      "Whenever the app prompts you, or quarterly. New versions include security patches and odds improvements.",
      "## Steps",
      "1. Backup nothing — your bets live on the JeetBuzz server, not the app.",
      "2. Download the new APK from the official site.",
      "3. Install over the existing app — you stay logged in.",
      "## After update",
      "Verify your version number in Settings.",
    ],
  },
  {
    slug: "jeetbuzz-ios-webapp-install",
    title: "JeetBuzz iOS Web App — Install in 30 Seconds",
    category: "APK",
    description: "How to install the JeetBuzz iOS web app to your iPhone home screen — works just like a native app.",
    date: "2026-06-03",
    readTime: "3 min",
    body: [
      "## Open Safari",
      "Visit the official JeetBuzz site in Safari (not Chrome).",
      "## Add to home screen",
      "Tap Share > Add to Home Screen. Confirm.",
      "## Use like an app",
      "The icon now launches JeetBuzz in standalone mode — no Safari chrome.",
    ],
  },
  {
    slug: "jeetbuzz-casino-best-slots",
    title: "JeetBuzz Casino — Best Slots for Bangladesh Players",
    category: "Casino",
    description: "Our pick of JeetBuzz slots with the best RTP and content for Bangladesh players.",
    date: "2026-06-01",
    readTime: "5 min",
    body: [
      "## What to look for",
      "RTP (return-to-player) above 96% and volatility that matches your bankroll.",
      "## Provider mix",
      "JeetBuzz lists slots from Pragmatic, PG Soft, JILI and others. Pragmatic and JILI dominate the lobby.",
      "## Bonus eligibility",
      "Not every slot contributes equally to wagering. Check the bonus terms table.",
    ],
  },
  {
    slug: "jeetbuzz-live-baccarat",
    title: "JeetBuzz Live Baccarat — A Beginner's Guide",
    category: "Casino",
    description: "How baccarat works on JeetBuzz live casino, with Bengali-speaking dealer tables and side bets explained.",
    date: "2026-05-30",
    readTime: "5 min",
    body: [
      "## The basics",
      "Bet on Banker, Player, or Tie. Banker is the lowest house-edge bet at ~1.06%.",
      "## Side bets",
      "Pair bets carry higher house edge but the payouts are eye-catching.",
      "## Bengali tables",
      "Look for dealers labelled BN — the chat moderation runs in Bengali too.",
    ],
  },
  {
    slug: "jeetbuzz-aviator-guide",
    title: "JeetBuzz Aviator — How the Game Works",
    category: "Casino",
    description: "Aviator on JeetBuzz — gameplay, RTP, auto-cashout and the realistic strategy talk.",
    date: "2026-05-29",
    readTime: "4 min",
    body: [
      "## How it works",
      "Cash out before the plane flies away. Multiplier rises from 1.0x. RTP is ~97%.",
      "## Auto cashout",
      "Set a fixed multiplier to remove emotion.",
      "## Strategy reality",
      "It is RNG. No system 'beats' it long-term. Set a stop-loss.",
    ],
  },
  {
    slug: "jeetbuzz-cricket-prediction-tools",
    title: "JeetBuzz Cricket Prediction Tools — Are They Worth It?",
    category: "Sports",
    description: "An honest look at cricket prediction tools and tipsters around JeetBuzz, and what actually works.",
    date: "2026-05-27",
    readTime: "6 min",
    body: [
      "## What works",
      "Public stats (recent form, head-to-head, pitch reports). Free, neutral, useful.",
      "## What doesn't",
      "Paid Telegram tipsters with screenshots only of winners. Sample bias, not skill.",
      "## Better approach",
      "Track your own bets, calculate ROI by market, drop the markets you lose on.",
    ],
  },
  {
    slug: "jeetbuzz-football-betting",
    title: "JeetBuzz Football Betting — Markets & Tips",
    category: "Sports",
    description: "Football on JeetBuzz — Premier League, Champions League, World Cup, and the best markets for Bangladesh players.",
    date: "2026-05-25",
    readTime: "5 min",
    body: [
      "## Coverage",
      "Premier League, La Liga, Champions League, World Cup qualifiers, plus regional leagues.",
      "## Best markets",
      "Asian handicap, both teams to score, 1H/FT goals.",
      "## In-play",
      "Football in-play moves slower than cricket, leaving more time to think.",
    ],
  },
  {
    slug: "jeetbuzz-esports-overview",
    title: "JeetBuzz Esports — Dota, CS, Mobile Legends",
    category: "Sports",
    description: "Esports markets on JeetBuzz — Dota 2, CS2, Mobile Legends — and how they compare to dedicated esports books.",
    date: "2026-05-24",
    readTime: "4 min",
    body: [
      "## Coverage",
      "Top-tier Dota, CS and Mobile Legends are reliably covered. Lower tiers can be sparse.",
      "## Compared to dedicated esports books",
      "Markets thinner, odds slightly weaker, but bankroll lives with the rest of your sports betting.",
    ],
  },
  {
    slug: "jeetbuzz-tennis-betting",
    title: "JeetBuzz Tennis Betting — Grand Slams to Challengers",
    category: "Sports",
    description: "Tennis on JeetBuzz — Grand Slam coverage, in-play markets and tips for Bangladesh players.",
    date: "2026-05-23",
    readTime: "4 min",
    body: [
      "## Coverage",
      "All four Grand Slams plus ATP/WTA tour. Challenger coverage is thinner.",
      "## Markets",
      "Match winner, total games, total sets, in-play game-by-game.",
      "## Tip",
      "Watch first-set break points — momentum shifts the in-play line meaningfully.",
    ],
  },
  {
    slug: "jeetbuzz-deposit-failed-bkash",
    title: "JeetBuzz Deposit Failed on bKash — Step-by-Step Fix",
    category: "Payment",
    description: "What to do when your bKash deposit to JeetBuzz fails — checklist, support template and prevention.",
    date: "2026-05-21",
    readTime: "4 min",
    body: [
      "## First, breathe",
      "Your bKash app SMS is the source of truth. If you have a TrxID, the money is recoverable.",
      "## Checklist",
      "- Right merchant number?",
      "- Right amount?",
      "- Reference exactly as shown?",
      "## Open chat with this",
      "JeetBuzz username, TrxID, amount, time. Live chat usually credits within 10 minutes.",
    ],
  },
  {
    slug: "jeetbuzz-usdt-deposit",
    title: "JeetBuzz USDT Deposit — TRC20 vs BEP20",
    category: "Payment",
    description: "How to deposit USDT to JeetBuzz — TRC20 vs BEP20, fees, confirmations and avoiding network mistakes.",
    date: "2026-05-20",
    readTime: "5 min",
    body: [
      "## Pick the right network",
      "TRC20 (Tron) is cheaper. BEP20 (BSC) is also low-fee. Sending on the wrong network can lose funds.",
      "## Confirmations",
      "TRC20 confirms in seconds. BEP20 in under a minute.",
      "## Why USDT for big players",
      "No wallet caps. Faster withdrawals once approved.",
    ],
  },
  {
    slug: "jeetbuzz-affiliate-commission-tips",
    title: "JeetBuzz Affiliate Commission Tips — Grow Faster",
    category: "Affiliate",
    description: "How JeetBuzz affiliates in Bangladesh grow commissions faster — sub-IDs, content strategy, retention.",
    date: "2026-05-19",
    readTime: "5 min",
    body: [
      "## Lead with content",
      "Guides outperform pure offer pages because they retain. Retained players pay you for months, not days.",
      "## Use sub-IDs religiously",
      "Split every channel. You can only improve what you can measure.",
      "## Don't chase CPA-only",
      "Revenue share compounds. CPA is a one-off.",
    ],
  },
  {
    slug: "jeetbuzz-affiliate-payout-day",
    title: "JeetBuzz Affiliate Payout Day — What to Expect",
    category: "Affiliate",
    description: "How JeetBuzz affiliate payouts work — currencies, minimums, KYC and dates.",
    date: "2026-05-17",
    readTime: "4 min",
    body: [
      "## When",
      "Monthly, typically in the first week.",
      "## Minimums",
      "Confirm in the affiliate portal — minimums vary by currency.",
      "## KYC",
      "Affiliate KYC is separate from player KYC. Complete it once.",
    ],
  },
  {
    slug: "jeetbuzz-responsible-gaming-tools",
    title: "JeetBuzz Responsible Gaming Tools You Should Use",
    category: "Responsible Gaming",
    description: "Deposit limits, loss limits, time-outs and self-exclusion on JeetBuzz — and when to use each.",
    date: "2026-05-16",
    readTime: "5 min",
    body: [
      "## Deposit limits",
      "Cap daily, weekly or monthly. Enabling one is the single most useful tool.",
      "## Loss limits",
      "Cap how much you can lose in a window.",
      "## Time-out",
      "A short cool-down (24h, 7d, 30d). Useful after a tilt session.",
      "## Self-exclusion",
      "Long-term lockout. Permanent options exist.",
      "> If betting stops being fun, take a break. BeGambleAware has free, confidential help.",
    ],
  },
  {
    slug: "jeetbuzz-language-support",
    title: "JeetBuzz Language Support — Bengali, Hindi, Urdu, English",
    category: "Login",
    description: "How to switch languages on JeetBuzz and what is fully translated versus partially.",
    date: "2026-05-15",
    readTime: "3 min",
    body: [
      "## Switch language",
      "Top-right of the site, or Account > Preferences. Bengali, Hindi, Urdu and English are official.",
      "## What is fully translated",
      "Cashier, support, account settings. Some promo terms remain English-first.",
    ],
  },
  {
    slug: "jeetbuzz-promo-codes",
    title: "JeetBuzz Promo Codes — How to Use Them",
    category: "Bonus",
    description: "Where to apply JeetBuzz promo codes during signup and reload, and what to do if a code is rejected.",
    date: "2026-05-14",
    readTime: "3 min",
    body: [
      "## On signup",
      "Apply in the Promo Code field during registration. Cannot be added later for most welcome offers.",
      "## On deposit",
      "Reload codes are applied in the cashier before submitting the deposit.",
      "## Rejected?",
      "Often expired or country-restricted. Contact live chat.",
    ],
  },
  {
    slug: "jeetbuzz-bangladesh-vs-india-market",
    title: "JeetBuzz Bangladesh vs India — Differences That Matter",
    category: "Registration",
    description: "How JeetBuzz differs between Bangladesh and India — payments, currency, language and promos.",
    date: "2026-05-12",
    readTime: "4 min",
    body: [
      "## Currency",
      "BDT in Bangladesh, INR in India.",
      "## Payments",
      "bKash/Nagad/Rocket in Bangladesh, UPI in India.",
      "## Language",
      "Bengali leads in Bangladesh, Hindi in India. Both have English fallback.",
      "## Promos",
      "Welcome bonus structures often differ by country — check the cashier.",
    ],
  },
];

POSTS.push(...EXTRA);