import { createFileRoute } from "@tanstack/react-router";
import { GuidePage } from "@/components/GuidePage";
import { imageAbsoluteUrl } from "@/lib/images";

export const Route = createFileRoute("/bonus-and-promotions")({
  head: () => ({
    meta: [
      { title: "JeetBuzz Bonus 2026 — Welcome Offer, Free Bets, Cashback & Wagering Rules Decoded" },
      { name: "description", content: "JeetBuzz bonus & promotions 2026 — welcome match, weekly reloads, 10% cashback, free bets and referral bonus, with the exact wagering (15x/25x) and max-bet rules that decide if a bonus is worth taking." },
      { property: "og:title", content: "JeetBuzz Bonus 2026 — Welcome, Reload, Cashback & Wagering" },
      { property: "og:description", content: "Which JeetBuzz bonus is actually worth taking in 2026 — wagering, max-bet, eligible games and opt-in rules explained." },
      { property: "og:type", content: "article" },
      { property: "og:image", content: imageAbsoluteUrl("bonus") },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "twitter:image", content: imageAbsoluteUrl("bonus") },
    ],
  }),
  component: () => (
    <GuidePage
      title={<>JeetBuzz <span className="gold-text">Bonuses & Promotions</span></>}
      titleByLocale={{
        bn: <>জিতবাজ <span className="gold-text">বোনাস ও প্রোমোশন</span></>,
        ur: <>JeetBuzz <span className="gold-text">بونس اور پروموشنز</span></>,
        hi: <>JeetBuzz <span className="gold-text">बोनस और प्रोमोशन</span></>,
      }}
      subtitle="A plain-English breakdown of the welcome offer, recurring reloads and the wagering terms that decide whether a bonus is actually worth taking."
      subtitleByLocale={{
        bn: "ওয়েলকাম বোনাস, রিলোড অফার ও wagering শর্ত — কোন বোনাস আসলে নেওয়ার মতো, সরল বাংলায় ব্যাখ্যা।",
        ur: "ویلکم بونس، ری لوڈ آفرز اور wagering شرائط — کون سا بونس واقعی فائدہ مند ہے، آسان اردو میں۔",
        hi: "वेलकम बोनस, रीलोड ऑफ़र और wagering शर्तें — कौन-सा बोनस सच में लेने लायक है, सरल हिंदी में।",
      }}
      heroImage="bonus"
      body={[
        "> **Quick summary:** JeetBuzz runs a deposit-match welcome (Sports OR Casino, not both), weekly reloads, cashback up to 10%, free bets and a referral bonus. Wagering is typically 15x for sports/slots and 25x for casino, with a 200–500 BDT max-bet rule while a bonus is active. Always opt in **before** depositing — bonuses are never added retroactively.",
        "## Welcome bonus",
        "JeetBuzz typically runs a deposit-match welcome bonus for sportsbook and a separate one for casino. Read the fine print — you usually pick one.",
        "## Promotions at a glance (2026)",
        "| Promotion | Typical Match | Wagering | Max Bet | Eligible Games |",
        "|---|---|---|---|---|",
        "| Sports Welcome | 100% up to 10,000 BDT | ~15x | 500 BDT | Sports @ odds ≥ 1.50 |",
        "| Casino Welcome | 150% up to 15,000 BDT | ~25x | 200 BDT | Slots 100%, Live 10% |",
        "| Weekly Reload | 25–50% | ~10x | 500 BDT | Sports & Slots |",
        "| Cashback | Up to 10% | None | n/a | Net losses, weekly |",
        "| Free Bet | 100–500 BDT | 1x (stake not returned) | n/a | Sports |",
        "| Referral | 500 BDT per friend | Friend must deposit + wager | n/a | All |",
        "## Wagering requirements",
        "Most bonuses carry ~15x wagering. A 1,000 BDT bonus needs around 15,000 BDT in qualifying bets before it (and any winnings) can be withdrawn.",
        "## Max bet rule",
        "While the bonus is active, single-bet caps apply. Going over can void the bonus.",
        "## Eligible games",
        "Sports and slots usually count fully. Live casino often contributes 10% or less.",
        "## Time limits",
        "Bonuses commonly expire in 7–30 days after activation.",
        "## Country-specific notes",
        "- **Bangladesh:** Welcome bonus is most rewarding for cricket bettors who play through IPL/BPL — sports wagering at odds ≥ 1.50 clears fastest. Fund through the [bKash guide](/bkash-guide) or [Nagad guide](/nagad-guide).",
        "- **Pakistan:** PSL season unlocks higher-cap reloads. Deposit via the [JazzCash guide](/jazzcash-guide) or [EasyPaisa guide](/easypaisa-guide).",
        "- **India:** IPL-season promotions stack on top of the standard welcome offer. Deposit through the [UPI guide](/upi-guide) or [PhonePe guide](/phonepe-guide).",
        "## How to claim — step by step",
        "1. Register a JeetBuzz account using the [Registration Guide](/registration-guide).",
        "2. Open **Promotions** from the top menu.",
        "3. Choose Sports or Casino welcome (you cannot stack both).",
        "4. Tap **Opt In** — the bonus must be active *before* you deposit.",
        "5. Make your qualifying deposit via the [Deposit Guide](/deposit-guide).",
        "6. The bonus credit appears in the Promotions wallet within 60 seconds.",
        "7. Wager through the requirement at qualifying odds; track progress in the Promotions widget.",
        "8. Once cleared, the funds move to your main balance and can be withdrawn via the [Withdrawal Guide](/withdrawal-guide).",
        "## Wagering math — worked examples",
        "- **1,000 BDT bonus @ 15x:** you must place 15,000 BDT in qualifying bets (odds ≥ 1.50) before withdrawing.",
        "- **10,000 BDT welcome @ 15x:** 150,000 BDT in qualifying turnover — realistic for daily cricket bettors over 14–21 days.",
        "- **5,000 BDT casino @ 25x:** 125,000 BDT in slot turnover. Live casino at 10% means you would need 1,250,000 BDT of live turnover instead — almost always not worth it.",
        "## Our take",
        "Take the bonus if you'd be betting anyway. Skip if the wagering doesn't suit your style.",
        "> Promotions change frequently — always confirm the current offer on the official site before depositing.",
        "## Ready to claim your bonus?",
        "Opt in first, then deposit. Use the [Deposit Guide](/deposit-guide) for the exact flow and the [Welcome Bonus](/welcome-bonus) page for the current match percentage.",
      ]}
      bodyByLocale={{
        bn: [
          "## এক নজরে",
          "জিতবাজে বাংলাদেশি প্লেয়ারদের জন্য কয়েক ধরনের প্রোমোশন চলে — ওয়েলকাম বোনাস (Sports অথবা Casino), সাপ্তাহিক রিলোড, ক্যাশব্যাক, ফ্রি বেট এবং রেফারেল বোনাস। গুরুত্বপূর্ণ কথা: ডিপোজিটের **আগে** অপ্ট-ইন করতে হয়; পরে আর retroactive যোগ হয় না।",
          "## ওয়েলকাম বোনাস — Sports নাকি Casino?",
          "Sports ওয়েলকাম সাধারণত প্রি-ম্যাচ ও লাইভ ক্রিকেট/ফুটবল বাজির জন্য তৈরি — যোগ্য odds সাধারণত ১.৫০ বা তার বেশি। Casino ওয়েলকাম স্লট-ভিত্তিক প্লেয়ারদের জন্য উপযোগী, কারণ স্লট বেশিরভাগ সময় wagering-এ পুরো অবদান রাখে। দুইটা একসাথে নেওয়া যায় না — যেই গেম-স্টাইল আপনার আসল অভ্যাস, সেটাই বেছে নিন।",
          "## প্রোমোশন এক নজরে",
          "| প্রোমোশন | সাধারণ ম্যাচ | Wagering (আনুমানিক) | Max bet | যোগ্য গেম |",
          "|---|---|---|---|---|",
          "| Sports Welcome | ১০০% (সীমা অনুযায়ী) | ~১৫x | ক্যাশিয়ারে দেখানো | Sports @ odds ≥ ১.৫০ |",
          "| Casino Welcome | ১৫০% (সীমা অনুযায়ী) | ~২৫x | ক্যাশিয়ারে দেখানো | Slots ১০০%, Live ~১০% |",
          "| সাপ্তাহিক Reload | ২৫–৫০% | ~১০x | ক্যাশিয়ারে দেখানো | Sports ও Slots |",
          "| Cashback | ১০% পর্যন্ত | নেই | প্রযোজ্য নয় | নেট লসের ওপর |",
          "| Free Bet | অফার অনুযায়ী | ১x (stake ফেরত নয়) | প্রযোজ্য নয় | Sports |",
          "| Referral | প্রতি বন্ধুর জন্য নির্দিষ্ট পরিমাণ | বন্ধুকে ডিপোজিট+wager করতে হয় | প্রযোজ্য নয় | সব |",
          "টেবিলের সংখ্যা পরিবর্তিত হতে পারে — চূড়ান্ত মান অফিসিয়াল Promotions পেজ ও ক্যাশিয়ারে দেখানো শর্ত অনুযায়ী।",
          "## Wagering শর্ত — সহজ উদাহরণ",
          "ধরা যাক ১,০০০ টাকার ওয়েলকাম বোনাস পেলেন, wagering ১৫x। মানে প্রায় ১৫,০০০ টাকার যোগ্য বাজি ধরতে হবে (odds ≥ ১.৫০ এ) বোনাস ও তার থেকে আসা winnings উইথড্রয়ের আগে। যদি Casino ওয়েলকাম নেন (~২৫x) এবং লাইভ ক্যাসিনো খেলেন (যেখানে অবদান ~১০%), তাহলে প্রকৃত টার্নওভার অনেক গুণ বেড়ে যায় — তাই Casino ওয়েলকাম মূলত স্লট প্লেয়ারদের জন্যই অর্থবহ।",
          "## Max bet নিয়ম",
          "বোনাস অ্যাক্টিভ থাকা অবস্থায় প্রতি বাজির একটি সর্বোচ্চ সীমা থাকে। এই সীমা অতিক্রম করলে সিস্টেম পুরো বোনাস এবং তার থেকে আসা winnings বাতিল করে দিতে পারে। ক্যাশিয়ারে দেখানো সঠিক সীমা সবসময় যাচাই করে নিন।",
          "## যোগ্য গেম ও অবদান",
          "প্রি-ম্যাচ ও লাইভ স্পোর্টস (yog্য odds-এ) এবং বেশিরভাগ স্লট সাধারণত ১০০% অবদান রাখে। লাইভ ক্যাসিনো (Blackjack, Roulette, Baccarat) সাধারণত অনেক কম — কোনো গেম পুরোপুরি বাদও থাকতে পারে। বাজি ধরার আগে গেমের terms-এ ‘contribution’ লেখা অংশটি দেখে নিন।",
          "## ক্লেইম করার ধাপে ধাপে গাইড",
          "১. [Registration Guide](/registration-guide) অনুসরণ করে অ্যাকাউন্ট খুলুন।",
          "২. উপরের মেনু থেকে Promotions খুলুন।",
          "৩. Sports বা Casino — একটি ওয়েলকাম বেছে নিন।",
          "৪. Opt In চাপুন — ডিপোজিটের **আগেই** এটি করতে হবে।",
          "৫. [Deposit Guide](/deposit-guide) দেখে bKash/Nagad/Rocket দিয়ে যোগ্য ডিপোজিট করুন।",
          "৬. বোনাস ক্রেডিট সাধারণত কিছুক্ষণের মধ্যে Promotions ওয়ালেটে দেখা যায়।",
          "৭. যোগ্য odds-এ বাজি ধরে wagering সম্পন্ন করুন; অগ্রগতি Promotions উইজেটে দেখা যায়।",
          "৮. ক্লিয়ার হলে ফান্ড মূল ব্যালেন্সে চলে আসে; [Withdrawal Guide](/withdrawal-guide) অনুসরণ করে উইথড্র করুন।",
          "## কোন বোনাস আপনার জন্য?",
          "যদি আপনি এমনিতেই BPL/IPL/PSL মৌসুমে নিয়মিত ক্রিকেট বাজি ধরেন, Sports ওয়েলকাম দ্রুত ক্লিয়ার হয়। যদি কেবল মাঝে মাঝে স্লট খেলেন বিনোদনের জন্য, Casino ওয়েলকাম মানানসই — তবে wagering বেশি বলে ধৈর্য রাখতে হবে। যদি আপনার খেলার ধরনের সঙ্গে wagering মেলে না, বোনাস না নিয়ে শুধু নিজের ডিপোজিট দিয়ে খেলাই বেশি লাভজনক।",
          "## সময়সীমা ও সাধারণ ভুল",
          "বোনাস সাধারণত নির্দিষ্ট সময়ের মধ্যে wagering সম্পন্ন করতে হয় (অফার অনুযায়ী, ক্যাশিয়ারে দেখানো)। সক্রিয় বোনাস থাকা অবস্থায় উইথড্রয়াল চেষ্টা করলে বোনাস ও তার winnings বাতিল হয়ে যেতে পারে — তাই আগে wagering শেষ করুন।",
          "## পরবর্তী ধাপ",
          "[Welcome Bonus](/welcome-bonus) পেজে চলমান ম্যাচ পার্সেন্টেজ দেখে নিন, তারপর [Deposit Guide](/deposit-guide) অনুসরণ করে প্রথম ডিপোজিট করুন।",
          "> অফার ঘন ঘন বদলায় — ডিপোজিটের আগে অফিসিয়াল Promotions পেজে চলমান শর্ত যাচাই করে নিন। ১৮+ মাত্র; দয়া করে [Responsible Gaming](/responsible-gaming) দেখুন।",
        ],
        ur: [
          "## ایک نظر میں",
          "JeetBuzz پاکستانی کھلاڑیوں کو کئی قسم کے پروموشنز پیش کرتا ہے — ویلکم بونس (Sports یا Casino)، ہفتہ وار ری لوڈ، کیش بیک، فری بیٹ اور ریفرل بونس۔ اہم بات: ہر بونس کو ڈپازٹ سے **پہلے** آپٹ-ان کرنا ضروری ہے؛ بعد میں retroactive طور پر شامل نہیں ہوتا۔",
          "## ویلکم بونس — Sports یا Casino؟",
          "Sports ویلکم بنیادی طور پر پری میچ اور لائیو کرکٹ/فٹبال بیٹنگ کے لیے بنایا گیا ہے — اہل odds عام طور پر 1.50 یا اس سے زیادہ ہوتے ہیں۔ Casino ویلکم سلاٹ کھلاڑیوں کے لیے زیادہ مناسب ہے کیونکہ سلاٹ بیشتر اوقات wagering میں مکمل حصہ ڈالتے ہیں۔ دونوں ایک ساتھ نہیں لیے جا سکتے — جو گیم اسٹائل واقعی آپ کا ہے، وہی چنیں۔",
          "## پروموشنز ایک نظر میں",
          "| پروموشن | عام میچ | Wagering (تخمینی) | Max bet | اہل گیمز |",
          "|---|---|---|---|---|",
          "| Sports Welcome | 100% (حد کے مطابق) | ~15x | کیشیئر میں دکھائی گئی | Sports @ odds ≥ 1.50 |",
          "| Casino Welcome | 150% (حد کے مطابق) | ~25x | کیشیئر میں دکھائی گئی | Slots 100%، Live ~10% |",
          "| ہفتہ وار Reload | 25–50% | ~10x | کیشیئر میں دکھائی گئی | Sports اور Slots |",
          "| Cashback | 10% تک | نہیں | لاگو نہیں | نیٹ نقصان پر |",
          "| Free Bet | آفر کے مطابق | 1x (stake واپس نہیں) | لاگو نہیں | Sports |",
          "| Referral | فی دوست مقررہ رقم | دوست کو ڈپازٹ+wager کرنا ہوگا | لاگو نہیں | تمام |",
          "ٹیبل کی اقدار وقتاً فوقتاً تبدیل ہو سکتی ہیں — حتمی اقدار آفیشل Promotions پیج اور کیشیئر میں دکھائی گئی شرائط کے مطابق ہی درست ہیں۔",
          "## Wagering شرائط — آسان مثال",
          "فرض کریں آپ کو 1,000 PKR کا ویلکم بونس ملا، wagering 15x ہے۔ اس کا مطلب ہے کہ بونس اور اس سے بنی جیت نکالنے سے پہلے تقریباً 15,000 PKR کی اہل بیٹس (odds ≥ 1.50) لگانی پڑیں گی۔ اگر Casino ویلکم لیں (~25x) اور لائیو کیسینو کھیلیں (جہاں حصہ ~10%) تو حقیقی ٹرن اوور کئی گنا بڑھ جاتا ہے — اس لیے Casino ویلکم بنیادی طور پر سلاٹ کھلاڑیوں کے لیے ہی فائدہ مند ہے۔",
          "## Max bet اصول",
          "بونس فعال ہونے کے دوران فی بیٹ ایک زیادہ سے زیادہ حد لاگو ہوتی ہے۔ اس حد سے تجاوز کرنے پر سسٹم پورے بونس اور اس سے بنی جیت کو کالعدم کر سکتا ہے۔ کیشیئر میں دکھائی گئی صحیح حد ہمیشہ تصدیق کر لیں۔",
          "## اہل گیمز اور حصہ",
          "پری میچ اور لائیو اسپورٹس (اہل odds پر) اور بیشتر سلاٹس عام طور پر 100% حصہ ڈالتے ہیں۔ لائیو کیسینو (Blackjack، Roulette، Baccarat) عام طور پر بہت کم — کچھ گیمز مکمل طور پر خارج بھی ہو سکتے ہیں۔ بیٹ لگانے سے پہلے گیم کی ‘contribution’ شرائط ضرور دیکھیں۔",
          "## کلیم کرنے کا مرحلہ وار طریقہ",
          "1. [Registration Guide](/registration-guide) کے مطابق اکاؤنٹ کھولیں۔",
          "2. اوپر کے مینو سے Promotions کھولیں۔",
          "3. Sports یا Casino — ایک ویلکم منتخب کریں۔",
          "4. Opt In دبائیں — ڈپازٹ سے **پہلے** ہی یہ کرنا ضروری ہے۔",
          "5. [Deposit Guide](/deposit-guide) دیکھ کر JazzCash/EasyPaisa سے اہل ڈپازٹ کریں۔",
          "6. بونس کریڈٹ عام طور پر چند منٹوں میں Promotions والیٹ میں نظر آتا ہے۔",
          "7. اہل odds پر بیٹ لگا کر wagering مکمل کریں؛ پیش رفت Promotions ویجٹ میں دکھائی دیتی ہے۔",
          "8. کلیئر ہونے پر فنڈز مین بیلنس میں آ جاتے ہیں؛ [Withdrawal Guide](/withdrawal-guide) کے مطابق ودڈرا کریں۔",
          "## کون سا بونس آپ کے لیے؟",
          "اگر آپ ویسے ہی PSL/IPL/BPL سیزن میں باقاعدگی سے کرکٹ پر بیٹ لگاتے ہیں تو Sports ویلکم تیزی سے کلیئر ہوتا ہے۔ اگر صرف کبھی کبھار تفریح کے لیے سلاٹس کھیلتے ہیں تو Casino ویلکم زیادہ مناسب ہے — البتہ wagering زیادہ ہونے کی وجہ سے صبر چاہیے۔ اگر آپ کے کھیلنے کے انداز سے wagering میل نہیں کھاتا تو بونس چھوڑ کر صرف اپنی رقم سے کھیلنا زیادہ سود مند ہے۔",
          "## وقت کی حد اور عام غلطیاں",
          "بونس کو عام طور پر مقررہ مدت کے اندر wagering مکمل کرنا ہوتا ہے (آفر کے مطابق، کیشیئر میں دکھائی گئی)۔ فعال بونس کے دوران ودڈرا کی کوشش کرنے پر بونس اور اس کی جیت ضبط ہو سکتی ہے — اس لیے پہلے wagering مکمل کریں۔",
          "## اگلا قدم",
          "[Welcome Bonus](/welcome-bonus) پیج پر موجودہ میچ فیصد دیکھ لیں، پھر [Deposit Guide](/deposit-guide) کے مطابق پہلی ڈپازٹ کریں۔",
          "> آفرز اکثر بدلتے ہیں — ڈپازٹ سے پہلے آفیشل Promotions پیج پر موجودہ شرائط تصدیق کر لیں۔ صرف 18+؛ براہِ کرم [Responsible Gaming](/responsible-gaming) دیکھیں۔",
        ],
        hi: [
          "## एक नज़र में",
          "JeetBuzz भारतीय खिलाड़ियों को कई तरह के प्रोमोशन देता है — वेलकम बोनस (Sports या Casino), साप्ताहिक रीलोड, कैशबैक, फ्री बेट और रेफ़रल बोनस। ज़रूरी बात: हर बोनस को डिपॉज़िट से **पहले** opt-in करना अनिवार्य है; बाद में retroactive नहीं जुड़ता।",
          "## वेलकम बोनस — Sports या Casino?",
          "Sports वेलकम मूल रूप से प्री-मैच और लाइव क्रिकेट/फ़ुटबॉल बेटिंग के लिए बना है — योग्य odds आम तौर पर 1.50 या उससे ऊपर। Casino वेलकम स्लॉट खिलाड़ियों के लिए ज़्यादा उपयुक्त है, क्योंकि स्लॉट अधिकतर समय wagering में पूरा योगदान देते हैं। दोनों एक साथ नहीं लिए जा सकते — जो गेम शैली वास्तव में आपकी है, वही चुनें।",
          "## प्रोमोशन एक नज़र में",
          "| प्रोमोशन | सामान्य मैच | Wagering (अनुमानित) | Max bet | योग्य गेम्स |",
          "|---|---|---|---|---|",
          "| Sports Welcome | 100% (सीमा अनुसार) | ~15x | कैशियर में दिखाया गया | Sports @ odds ≥ 1.50 |",
          "| Casino Welcome | 150% (सीमा अनुसार) | ~25x | कैशियर में दिखाया गया | Slots 100%, Live ~10% |",
          "| साप्ताहिक Reload | 25–50% | ~10x | कैशियर में दिखाया गया | Sports और Slots |",
          "| Cashback | 10% तक | नहीं | लागू नहीं | नेट नुक़सान पर |",
          "| Free Bet | ऑफ़र अनुसार | 1x (stake वापस नहीं) | लागू नहीं | Sports |",
          "| Referral | प्रति मित्र निश्चित राशि | मित्र को डिपॉज़िट+wager करना होगा | लागू नहीं | सभी |",
          "तालिका के मान समय-समय पर बदल सकते हैं — अंतिम मान ऑफ़िशियल Promotions पेज और कैशियर में दिखाई शर्तों के अनुसार ही मान्य हैं।",
          "## Wagering शर्तें",
          "मान लीजिए आपको ₹1,000 का वेलकम बोनस मिला, wagering 15x है। इसका अर्थ है कि बोनस और उससे बनी जीत निकालने से पहले लगभग ₹15,000 की योग्य बेट्स (odds ≥ 1.50) लगानी होंगी। यदि Casino वेलकम लें (~25x) और लाइव कसीनो खेलें (जहाँ योगदान ~10%), तो वास्तविक टर्नओवर कई गुना बढ़ जाता है — इसलिए Casino वेलकम मुख्यतः स्लॉट खिलाड़ियों के लिए ही फ़ायदेमंद है।",
          "## Max bet नियम",
          "बोनस सक्रिय रहते हर बेट की एक अधिकतम सीमा लागू होती है। इस सीमा से बाहर जाने पर सिस्टम पूरे बोनस और उससे बनी जीत को रद्द कर सकता है। कैशियर में दिखाई गई सही सीमा हमेशा सत्यापित कर लें।",
          "## योग्य गेम्स",
          "प्री-मैच और लाइव स्पोर्ट्स (योग्य odds पर) तथा अधिकांश स्लॉट्स आम तौर पर 100% योगदान देते हैं। लाइव कसीनो (Blackjack, Roulette, Baccarat) आम तौर पर बहुत कम — कुछ गेम पूरी तरह बाहर भी हो सकते हैं। बेट लगाने से पहले गेम की ‘contribution’ शर्त ज़रूर देखें।",
          "## क्लेम करने का चरण-दर-चरण तरीक़ा",
          "1. [Registration Guide](/registration-guide) के अनुसार अकाउंट खोलें।",
          "2. ऊपर के मेनू से Promotions खोलें।",
          "3. Sports या Casino — एक वेलकम चुनें।",
          "4. Opt In दबाएँ — डिपॉज़िट से **पहले** ही यह करना ज़रूरी है।",
          "5. [Deposit Guide](/deposit-guide) के अनुसार UPI/PhonePe/Paytm से योग्य डिपॉज़िट करें।",
          "6. बोनस क्रेडिट आम तौर पर कुछ क्षणों में Promotions वॉलेट में दिखाई देता है।",
          "7. योग्य odds पर बेट लगाकर wagering पूरा करें; प्रगति Promotions विजेट में दिखती है।",
          "8. क्लियर होने के बाद फंड मुख्य बैलेंस में आ जाते हैं; [Withdrawal Guide](/withdrawal-guide) के अनुसार विदड्रॉ करें।",
          "## कौन-सा बोनस आपके लिए?",
          "अगर आप वैसे भी IPL/घरेलू क्रिकेट सीज़न में नियमित बेटिंग करते हैं, तो Sports वेलकम तेज़ी से क्लियर होता है। अगर केवल मनोरंजन के लिए कभी-कभार स्लॉट खेलते हैं, Casino वेलकम उपयुक्त है — पर wagering ज़्यादा होने के कारण धैर्य रखना होगा। अगर आपकी खेल-शैली से wagering मेल नहीं खाता, तो बोनस छोड़कर सिर्फ़ अपने डिपॉज़िट से खेलना ही ज़्यादा फ़ायदेमंद है।",
          "## समय सीमा और आम ग़लतियाँ",
          "बोनस आम तौर पर निश्चित अवधि में wagering पूरा करना होता है (ऑफ़र अनुसार, कैशियर में दिखाया गया)। सक्रिय बोनस के दौरान विदड्रॉल करने पर बोनस और उसकी जीत ज़ब्त हो सकती है — इसलिए पहले wagering ख़त्म करें।",
          "## अगला क़दम",
          "[Welcome Bonus](/welcome-bonus) पेज पर मौजूदा मैच प्रतिशत देख लें, फिर [Deposit Guide](/deposit-guide) के अनुसार पहली डिपॉज़िट करें।",
          "> ऑफ़र अक्सर बदलते हैं — डिपॉज़िट से पहले ऑफ़िशियल Promotions पेज पर मौजूदा शर्तें सत्यापित कर लें। केवल 18+; कृपया [Responsible Gaming](/responsible-gaming) देखें।",
        ],
      }}
      articleHeadline="JeetBuzz Bonus & Promotions"
      articleDescription="Welcome bonus, reloads and wagering terms explained for BD, PK and IN players."
      articlePath="/bonus-and-promotions"
      faqs={[
        { q: "Can I claim more than one welcome bonus?", a: "No — you choose Sports OR Casino. After clearing the first, you become eligible for ongoing reloads and cashback." },
        { q: "Does live casino count toward wagering?", a: "Usually only 10% — meaning 1 BDT bet at live blackjack counts as 0.10 BDT toward the requirement. Slots and pre-match sports clear bonuses fastest." },
        { q: "What happens if I withdraw with an active bonus?", a: "The bonus and any unspent bonus-derived winnings are forfeited. Always finish wagering before cashing out." },
        { q: "Are bonuses available in Pakistan and India?", a: "Yes — JeetBuzz runs localized promotions in PKR and INR. Some offers are region-specific around PSL and IPL." },
        { q: "What is the max bet while a bonus is active?", a: "Typically 200–500 BDT per single bet. Exceeding the cap can void the entire bonus, including winnings." },
        { q: "Do free bets refund the stake?", a: "No. Free bets pay out winnings only — the stake amount is not returned." },
      ]}
      faqsByLocale={{
        bn: [
          { q: "একাধিক ওয়েলকাম বোনাস নেওয়া যাবে?", a: "না — Sports বা Casino একটি বেছে নিতে হবে। প্রথমটি ক্লিয়ার করার পর রিলোড ও ক্যাশব্যাক চালু হয়।" },
          { q: "Live casino কি wagering-এ গণনা হয়?", a: "সাধারণত মাত্র 10% — স্লট ও প্রি-ম্যাচ স্পোর্টস বোনাস দ্রুত ক্লিয়ার করে।" },
          { q: "অ্যাক্টিভ বোনাসে উইথড্র করলে কী হবে?", a: "বোনাস ও বোনাস থেকে আসা winnings বাতিল হবে। উইথড্রর আগে wagering শেষ করুন।" },
          { q: "Max bet সীমা কত?", a: "সাধারণত প্রতি বাজি 200–500 টাকা। সীমা ভাঙলে পুরো বোনাস বাতিল হতে পারে।" },
          { q: "Free bet stake ফেরত আসে?", a: "না — কেবল winnings জমা হয়, stake ফেরত নয়।" },
          { q: "ডিপোজিটের পরে কি বোনাস যোগ করা যায়?", a: "না — বোনাস অপ্ট-ইন ডিপোজিটের আগে করতে হয়; পরে retroactive যোগ হয় না।" },
          { q: "BPL বা IPL সময় বাড়তি অফার থাকে?", a: "ক্রিকেট মৌসুমে প্রায়ই স্পোর্টস-কেন্দ্রিক রিলোড বা অ্যাক্যুমুলেটর বোনাস চলে। চলমান অফার সবসময় অফিসিয়াল Promotions পেজে যাচাই করুন।" },
          { q: "Cashback কি ‘ফ্রি টাকা’?", a: "ক্যাশব্যাক সাধারণত নির্দিষ্ট সময়ের নেট লসের একটি অংশ ফেরত — wagering ছাড়া তোলা গেলেও এটি ক্ষতিপূরণ, লাভ নয়। সবসময় নিজের ব্যাংকরোল প্রথমে।" },
        ],
        ur: [
          { q: "کیا میں ایک سے زیادہ ویلکم بونس لے سکتا ہوں؟", a: "نہیں — Sports یا Casino میں سے ایک منتخب کریں۔" },
          { q: "کیا لائیو کیسینو ویجرنگ میں شمار ہوتا ہے؟", a: "عام طور پر صرف 10%۔ سلاٹس اور پری میچ اسپورٹس بونس کو سب سے تیز کلیئر کرتے ہیں۔" },
          { q: "فعال بونس کے ساتھ ودڈرا کرنے سے کیا ہوگا؟", a: "بونس اور بونس سے بنی جیت ضبط ہو جائے گی۔" },
          { q: "میکس بیٹ کی حد کیا ہے؟", a: "ہر بونس کی اپنی فی بیٹ حد ہوتی ہے جو کیشیئر میں دکھائی جاتی ہے۔ اس حد سے تجاوز پورے بونس اور جیت کو کالعدم کر سکتا ہے۔ ہمیشہ آپٹ-ان کرنے سے پہلے شرائط پڑھ لیں۔" },
          { q: "کیا فری بیٹ سٹیک واپس کرتا ہے؟", a: "نہیں — صرف جیت کی رقم ادا ہوتی ہے۔" },
          { q: "کیا ڈپازٹ کے بعد بونس شامل کیا جا سکتا ہے؟", a: "نہیں — بونس آپٹ-ان ڈپازٹ سے پہلے کرنا پڑتا ہے؛ بعد میں retroactive طور پر شامل نہیں ہوتا۔" },
          { q: "کیا PSL یا IPL کے دوران اضافی آفرز ہوتی ہیں؟", a: "کرکٹ سیزن میں اکثر اسپورٹس مرکوز ری لوڈ یا ایکیومولیٹر بونس چلتے ہیں۔ موجودہ آفر کی تصدیق ہمیشہ آفیشل Promotions پیج پر کریں۔" },
          { q: "کیا کیش بیک ‘مفت رقم’ ہے؟", a: "کیش بیک عام طور پر مقررہ مدت کے نیٹ نقصان کا ایک حصہ واپسی ہے — wagering کے بغیر نکالا جا سکتا ہے لیکن یہ معاوضہ ہے، منافع نہیں۔ ہمیشہ اپنا بینک رول پہلے رکھیں۔" },
        ],
        hi: [
          { q: "क्या मैं एक से ज़्यादा वेलकम बोनस ले सकता हूँ?", a: "नहीं — Sports या Casino में से एक चुनें।" },
          { q: "क्या लाइव कसीनो वेजरिंग में गिना जाता है?", a: "आम तौर पर सिर्फ़ 10%। स्लॉट्स और प्री-मैच स्पोर्ट्स बोनस सबसे तेज़ क्लियर करते हैं।" },
          { q: "सक्रिय बोनस के साथ विदड्रॉल करने पर क्या होगा?", a: "बोनस और बोनस से बनी जीत ज़ब्त हो जाएगी।" },
          { q: "मैक्स बेट सीमा क्या है?", a: "आम तौर पर प्रति बेट ₹200–500। सीमा से ऊपर बेट पूरा बोनस रद्द कर सकती है।" },
          { q: "क्या फ्री बेट स्टेक वापस करता है?", a: "नहीं — केवल जीत की राशि दी जाती है।" },
        ],
      }}
      related={[
        { to: "/registration-guide", title: "Registration Guide", desc: "Open an account to claim the welcome bonus." },
        { to: "/deposit-guide", title: "Deposit Guide", desc: "Fund your account before opting in." },
        { to: "/vip-program", title: "VIP Program", desc: "Long-term reward tiers beyond the welcome bonus." },
        { to: "/jeetbuzz-review", title: "JeetBuzz Review", desc: "Pillar review of the operator." },
      ]}
    />
  ),
});