import { createFileRoute } from "@tanstack/react-router";
import { GuidePage } from "@/components/GuidePage";
import { canonicalLink, hreflangLinks, ogUrl, jsonLdScript, articleSchema } from "@/lib/schema";
import { SIGNUP_CLUSTER, siblings } from "@/lib/clusters";

const PATH = "/deposit-guide";
const TITLE =
  "JeetBuzz Deposit Guide Bangladesh Pakistan India 2026 - bKash, Nagad, UPI";
const DESC =
  "How to deposit on JeetBuzz in 2026 from Bangladesh, Pakistan and India — bKash, Nagad, Rocket, EasyPaisa, JazzCash, UPI and USDT with minimums, fees and timing.";

export const Route = createFileRoute("/deposit-guide")({
  head: () => ({
    meta: [
      { title: TITLE + " | GetJeetBuzz" },
      { name: "description", content: DESC },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESC },
      { property: "og:type", content: "article" },
      ogUrl(PATH),
    ],
    links: [canonicalLink(PATH), ...hreflangLinks(PATH)],
    scripts: [jsonLdScript(articleSchema({ headline: TITLE, description: DESC, path: PATH }))],
  }),
  component: () => (
    <GuidePage
      eyebrow="Payments"
      title={<>JeetBuzz <span className="gold-text">Deposit Guide</span></>}
      subtitle="The complete deposit handbook for JeetBuzz Bangladesh — bKash, Nagad, Rocket and UPI minimums, processing times and common errors."
      breadcrumbs={[{ name: "Payments", path: "/payment-methods" }, { name: "Deposit Guide", path: PATH }]}
      articlePath={PATH}
      articleHeadline={TITLE}
      articleDescription={DESC}
      body={[
        "## Overview",
        "This jeetbuzz deposit guide covers every supported rail across Bangladesh, Pakistan and India for 2026, with minimums, processing times, fees, and the exact flow for each payment method. Deposits on JeetBuzz are usually instant when you follow the correct Send Money flow.",
        "## Universal step-by-step",
        "1. Log in to JeetBuzz via the [official site or app](/apk-download-guide).",
        "2. Open **Cashier > Deposit**.",
        "3. Pick your method — country tiles appear automatically based on your IP.",
        "4. Enter the amount (see the per-method minimum table below).",
        "5. Copy the merchant number/VPA/wallet address plus the unique reference code.",
        "6. Open your wallet app and use **Send Money** (never Mobile Recharge or Make Payment).",
        "7. Send the exact amount with the reference code in the note/reference field.",
        "8. Copy the TrxID / UTR from your wallet SMS or receipt.",
        "9. Paste it back into the JeetBuzz form and submit. Balance updates in 30–60 seconds.",
        "## Bangladesh: bKash, Nagad, Rocket",
        "Bangladesh players use mobile wallets exclusively. Read the in-depth [bKash guide](/bkash-guide), [Nagad guide](/nagad-guide) and [Rocket guide](/rocket-guide).",
        "| Method | Minimum | Max/Day | Time |",
        "|---|---|---|---|",
        "| bKash | 200 BDT | 50,000 BDT | Instant |",
        "| Nagad | 200 BDT | 75,000 BDT | Instant |",
        "| Rocket | 300 BDT | 50,000 BDT | Instant – 5 min |",
        "| Upay | 300 BDT | 30,000 BDT | Instant |",
        "## Pakistan: JazzCash, EasyPaisa",
        "Pakistan deposits flow through mobile money. See the [JazzCash guide](/jazzcash-guide) and [EasyPaisa guide](/easypaisa-guide).",
        "| Method | Minimum | Max/Day | Time |",
        "|---|---|---|---|",
        "| JazzCash | 500 PKR | 100,000 PKR | Instant |",
        "| EasyPaisa | 500 PKR | 100,000 PKR | Instant |",
        "| Bank Transfer | 1,000 PKR | 500,000 PKR | 1–3 hours |",
        "## India: UPI, PhonePe, Google Pay, Paytm",
        "India players default to UPI. See the [UPI guide](/upi-guide), [PhonePe guide](/phonepe-guide) and [Paytm guide](/paytm-guide).",
        "| Method | Minimum | Max/Day | Time |",
        "|---|---|---|---|",
        "| UPI | ₹300 | ₹1,00,000 | Instant |",
        "| PhonePe | ₹300 | ₹1,00,000 | Instant |",
        "| Google Pay | ₹300 | ₹1,00,000 | Instant |",
        "| Paytm | ₹300 | ₹1,00,000 | Instant |",
        "| IMPS / NEFT | ₹500 | ₹5,00,000 | 5–30 min |",
        "## Crypto: USDT",
        "USDT (TRC20 or BEP20) is the fastest option for large-stake players because it bypasses wallet caps.",
        "| Network | Minimum | Confirms | Time |",
        "|---|---|---|---|",
        "| USDT TRC20 | ~$10 | 1 | 2–5 min |",
        "| USDT BEP20 | ~$10 | 3 | 3–10 min |",
        "## Why deposits fail",
        "- Wrong TrxID / UTR — double-check the last 4 characters",
        "- Sending to a personal number instead of the merchant",
        "- Using someone else's wallet — JeetBuzz requires the wallet name to match your account",
        "- Below the minimum amount or rounded incorrectly (500.50 vs 500)",
        "- Reference code missing or with extra spaces",
        "## Fees",
        "JeetBuzz does not charge a deposit fee on any method. Your wallet provider may charge a small send-money fee (bKash ~5 BDT per 1,000 BDT, JazzCash ~10 PKR flat, UPI free, USDT network gas).",
        "## Bonus eligibility",
        "Opt into the [Welcome Bonus](/welcome-bonus) **before** depositing. The bonus-qualifying minimum may be higher than the cashier minimum (typically 500 BDT / 1,000 PKR / ₹500).",
        "## After your first deposit",
        "Place a small bet to confirm everything works, then read the [Withdrawal Guide](/withdrawal-guide) so you know how to cash out before you need to. New players should also review [Is JeetBuzz Safe](/is-jeetbuzz-safe) and [Registration Guide](/registration-guide).",
        "## Cross-country comparison",
        "| Country | Default Rail | Backup Rail | Avg Credit Time | Success Rate |",
        "|---|---|---|---|---|",
        "| Bangladesh | bKash | Nagad / Rocket | <30 sec | ~96% |",
        "| Pakistan | JazzCash | EasyPaisa / Bank | <60 sec | ~94% |",
        "| India | UPI (PhonePe) | Google Pay / Paytm | <30 sec | ~97% |",
        "| Global | USDT TRC20 | USDT BEP20 | 2–10 min | ~99% |",
        "## Screenshot walkthrough (what each step looks like)",
        "- **Cashier home:** dark JeetBuzz layout, country tiles pre-selected by IP, each tile shows logo and live status (green = open, amber = slow, red = maintenance).",
        "- **Amount entry:** numeric pad with quick-select chips (500 / 1,000 / 2,000 / 5,000) and a 15-minute countdown timer at the top of the merchant pane.",
        "- **Merchant pane:** copy-pill for the receiving number/VPA/address, copy-pill for the unique reference code (always begins with JB-), and a \"How to pay\" mini guide collapsed by default.",
        "- **Confirmation form:** field for the TrxID / UTR / hash, optional screenshot upload, and a Submit button that turns gold when the form is valid.",
        "## Country-specific tips",
        "- **Bangladesh:** Use Send Money only — never Make Payment or Mobile Recharge. Keep both bKash and Nagad funded as failover.",
        "- **Pakistan:** EasyPaisa wallet limits reset at midnight PKT — top up before evening kickoffs.",
        "- **India:** If a UPI VPA rejects, refresh the cashier to rotate to a fresh acquiring bank VPA. PhonePe and Google Pay sometimes whitelist different VPAs.",
        "## Ready to make your first deposit?",
        "Pick your country, follow the 9 universal steps, and screenshot every screen until you are comfortable. Activate the [Welcome Bonus](/welcome-bonus) first, then deposit — bonuses are not added retroactively.",
      ]}
      subtitleByLocale={{
        bn: "JeetBuzz বাংলাদেশ ডিপোজিট হ্যান্ডবুক — bKash, Nagad, Rocket-এর মিনিমাম, প্রসেসিং সময় ও ভুল।",
        ur: "JeetBuzz پاکستان ڈپازٹ گائیڈ — EasyPaisa, JazzCash کی کم از کم رقم اور پروسیسنگ ٹائم۔",
        hi: "JeetBuzz इंडिया डिपॉज़िट गाइड — UPI, PhonePe, Paytm की मिनिमम और प्रोसेसिंग टाइम।",
      }}
      bodyByLocale={{
        bn: [
          "## সংক্ষেপে",
          "JeetBuzz-এ ডিপোজিটের জনপ্রিয় মাধ্যম bKash, Nagad ও Rocket। সাধারণত ইনস্ট্যান্ট।",
          "## ধাপে ধাপে",
          "১. লগইন করুন।",
          "২. Cashier > Deposit খুলুন।",
          "৩. মাধ্যম বাছুন।",
          "৪. অ্যামাউন্ট দিন (মিনিমাম ২০০–৫০০ BDT)।",
          "৫. মার্চেন্ট নম্বরে রেফারেন্সসহ পাঠান।",
          "৬. TrxID সাবমিট করুন।",
          "## প্রসেসিং সময়",
          "- bKash/Nagad: ইনস্ট্যান্ট",
          "- Rocket: ৫ মিনিট পর্যন্ত",
          "- USDT: ১–৩ কনফার্মেশন",
          "## ফেইল হওয়ার কারণ",
          "- ভুল TrxID",
          "- পারসোনাল নম্বরে পাঠানো",
          "- অন্যের ওয়ালেট",
          "- মিনিমামের নিচে",
          "## ফি",
          "JeetBuzz ফি নেয় না।",
          "## বোনাস",
          "ডিপোজিটের আগে অপ্ট-ইন করুন।",
          "## প্রথম ডিপোজিটের পর",
          "ছোট বেট দিয়ে কনফার্ম, তারপর Withdrawal Guide পড়ুন।",
        ],
        ur: [
          "## مختصراً",
          "JeetBuzz پاکستان میں EasyPaisa اور JazzCash مقبول۔ عموماً فوری۔",
          "## مرحلہ وار",
          "1. لاگ ان کریں۔",
          "2. Cashier > Deposit کھولیں۔",
          "3. طریقہ منتخب کریں۔",
          "4. رقم درج کریں (کم از کم 500 PKR)۔",
          "5. مرچنٹ نمبر پر ریفرنس کے ساتھ بھیجیں۔",
          "6. TRX ID جمع کرائیں۔",
          "## پروسیسنگ ٹائم",
          "- EasyPaisa/JazzCash: فوری",
          "- USDT: 1–3 تصدیقات",
          "## ناکامی کی وجوہات",
          "- غلط TRX ID",
          "- ذاتی نمبر پر بھیجنا",
          "- کسی اور کا والیٹ",
          "- کم از کم سے کم رقم",
          "## فیس",
          "JeetBuzz فیس نہیں لیتا۔",
          "## بونس",
          "ڈپازٹ سے پہلے آپٹ ان کریں۔",
          "## پہلے ڈپازٹ کے بعد",
          "چھوٹا بیٹ لگائیں، پھر Withdrawal Guide پڑھیں۔",
        ],
        hi: [
          "## संक्षेप में",
          "JeetBuzz इंडिया में UPI सबसे लोकप्रिय — PhonePe, Google Pay, Paytm सब काम करते हैं।",
          "## स्टेप-बाय-स्टेप",
          "1. लॉगिन करें।",
          "2. Cashier > Deposit खोलें।",
          "3. तरीका चुनें।",
          "4. राशि डालें (मिनिमम ₹500)।",
          "5. मर्चेंट UPI ID पर रेफरेंस के साथ भेजें।",
          "6. UTR/TrxID सबमिट करें।",
          "## प्रोसेसिंग टाइम",
          "- UPI: इंस्टैंट",
          "- USDT: 1–3 पुष्टि",
          "## फेल होने के कारण",
          "- गलत UTR",
          "- पर्सनल UPI पर भेजना",
          "- किसी और का वॉलेट",
          "- मिनिमम से कम",
          "## फीस",
          "JeetBuzz फीस नहीं लेता।",
          "## बोनस",
          "डिपॉज़िट से पहले ऑप्ट-इन करें।",
          "## पहले डिपॉज़िट के बाद",
          "छोटा बेट लगाएँ, फिर Withdrawal Guide पढ़ें।",
        ],
      }}
      faqsByLocale={{
        bn: [
          { q: "ডিপোজিট ফি?", a: "JeetBuzz ফি নেয় না। ওয়ালেট প্রোভাইডারের ছোট ফি থাকতে পারে।" },
          { q: "bKash পেন্ডিং কেন?", a: "ভুল TrxID বা পারসোনাল নম্বর। স্ক্রিনশটসহ লাইভ চ্যাট।" },
          { q: "বন্ধুর ওয়ালেট?", a: "না। ওয়ালেট নাম অ্যাকাউন্টের সাথে মিলতে হবে।" },
          { q: "মিনিমাম?", a: "মোবাইল ওয়ালেটে ২০০–৫০০ BDT।" },
        ],
        ur: [
          { q: "ڈپازٹ فیس؟", a: "JeetBuzz فیس نہیں لیتا۔ والیٹ پروائڈر کی معمولی فیس ہو سکتی ہے۔" },
          { q: "EasyPaisa پینڈنگ کیوں؟", a: "غلط TRX ID یا ذاتی نمبر۔ سکرین شاٹ کے ساتھ لائیو چیٹ۔" },
          { q: "دوست کا والیٹ؟", a: "نہیں۔ نام میچ ہونا چاہیے۔" },
          { q: "کم از کم؟", a: "500 PKR۔" },
        ],
        hi: [
          { q: "डिपॉज़िट फीस?", a: "JeetBuzz फीस नहीं लेता।" },
          { q: "UPI पेंडिंग क्यों?", a: "गलत UTR या पर्सनल UPI। स्क्रीनशॉट के साथ लाइव चैट।" },
          { q: "दोस्त का वॉलेट?", a: "नहीं। नाम मेल खाना चाहिए।" },
          { q: "मिनिमम?", a: "₹500।" },
        ],
      }}
      faqs={[
        { q: "Is there a deposit fee?", a: "JeetBuzz does not typically charge a deposit fee. Your wallet provider may charge a small send-money fee, especially for non-merchant transfers." },
        { q: "Why is my bKash deposit pending?", a: "Most commonly the wrong TrxID was submitted, or money was sent to a personal number. Contact live chat with your TrxID screenshot." },
        { q: "Can I deposit from a friend's wallet?", a: "No. The depositing wallet must match your registered JeetBuzz account name, otherwise the deposit can be reversed." },
        { q: "What's the minimum deposit?", a: "Typically 200–500 BDT for mobile wallets. Confirm the current minimum on the official cashier page before sending money." },
        { q: "How long does the first deposit take?", a: "Local wallets credit in under 60 seconds. UPI is usually under 30 seconds. USDT depends on network confirmations (2–10 minutes typical)." },
        { q: "Can I deposit in a different currency?", a: "Deposit in your local currency (BDT, PKR, INR, USDT) — JeetBuzz auto-detects from your country. There is no FX markup." },
        { q: "What if the cashier times out before I send?", a: "The reference code expires after 15 minutes. Start a fresh deposit so the code stays valid — never reuse an expired code." },
        { q: "Are deposit bonuses automatic?", a: "No. You must opt into the bonus on the promotions page before the deposit, otherwise the qualifying transaction will not be tagged." },
      ]}
      related={[
        { to: "/withdrawal-guide", title: "JeetBuzz Withdrawal Guide" },
        { to: "/bkash-guide", title: "bKash on JeetBuzz" },
        { to: "/nagad-guide", title: "Nagad on JeetBuzz" },
        { to: "/rocket-guide", title: "Rocket on JeetBuzz" },
        { to: "/payment-methods", title: "All Payment Methods" },
        ...siblings(SIGNUP_CLUSTER, "/deposit-guide"),
      ]}
    />
  ),
});