import { createFileRoute } from "@tanstack/react-router";
import { GuidePage } from "@/components/GuidePage";
import { canonicalLink, hreflangLinks, ogUrl, jsonLdScript, articleSchema } from "@/lib/schema";
import { AFFILIATE_CLUSTER, siblings } from "@/lib/clusters";

const PATH = "/jeetbuzz-affiliate-payment-methods";
const TITLE = "JeetBuzz Affiliate Payment Methods 2026, bKash, Nagad, USDT, Bank";
const DESC = "Every JeetBuzz affiliate payout method for 2026, bKash, Nagad, Rocket, bank transfer and USDT (TRC-20), with minimums, fees, timing and KYC requirements.";

export const Route = createFileRoute("/jeetbuzz-affiliate-payment-methods")({
  head: () => ({
    meta: [
      { title: TITLE + " | GetJeetBuzz" },
      { name: "description", content: DESC },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESC },
      { property: "og:type", content: "article" },
      ogUrl(PATH),
    ],
    links: [canonicalLink(PATH)...hreflangLinks(PATH)],
    scripts: [jsonLdScript(articleSchema({ headline: TITLE, description: DESC, path: PATH }))],
  }),
  component: () => (
    <GuidePage
      eyebrow="Affiliate"
      title={<>Affiliate <span className="gold-text">Payment Methods</span></>}
      subtitle="Where JeetBuzz affiliate commission actually lands, bKash, Nagad, Rocket, bank transfer, USDT, with minimums, fees, expected timing and the KYC document each payout requires."
      ctaIntent="partners" ctaLabel="Open Partner Dashboard"
      breadcrumbs={[{ name: "Affiliate", path: "/affiliate-program" }, { name: "Payment Methods", path: PATH }]}
      articlePath={PATH} articleHeadline={TITLE} articleDescription={DESC}
      body={[
        "## The five affiliate payout rails",
        "JeetBuzz pays weekly commission through five channels: **bKash**, **Nagad**, **Rocket**, **local bank transfer** and **USDT (TRC-20)**. Each has different minimums, cut-off times and KYC requirements. Match your payout method to the size of your weekly commission, small partners on bKash, large partners on bank or USDT.",
        "## bKash, the default for small and mid partners",
        "- **Minimum payout**: BDT 2,000 (equivalent). Weekly commission below this rolls over.",
        "- **Fee**: 0 for partners; JeetBuzz absorbs the cash-out fee for verified affiliates.",
        "- **Timing**: 2–24 hours on business days.",
        "- **KYC**: Personal bKash account must match the name on your affiliate KYC.",
        "- **Best for**: Partners earning BDT 2,000–20,000 weekly.",
        "The bKash number registered on your affiliate profile is the only destination that will process. Changing it requires re-verification and takes 24–72 hours.",
        "## Nagad, same-day fallback",
        "- **Minimum payout**: BDT 2,000.",
        "- **Fee**: 0 to partners.",
        "- **Timing**: 2–12 hours on business days.",
        "- **KYC**: Nagad wallet name must match affiliate KYC.",
        "- **Best for**: A parallel option when bKash is under a service disruption.",
        "Some affiliates keep both bKash and Nagad on file so they can switch destination if one rail has an outage. Payout method is selectable per withdrawal request.",
        "## Rocket, smaller footprint, still reliable",
        "- **Minimum payout**: BDT 2,000.",
        "- **Fee**: 0 to partners.",
        "- **Timing**: 4–24 hours.",
        "- **KYC**: Name-matched Rocket account.",
        "- **Best for**: Partners already using Rocket for daily banking; less popular but functional.",
        "## Local bank transfer, the choice above BDT 50,000/week",
        "- **Minimum payout**: BDT 5,000.",
        "- **Fee**: 0 to partners (JeetBuzz covers the IFT fee).",
        "- **Timing**: 1–3 working days, subject to your bank's cut-off.",
        "- **KYC**: Account number, IFSC/routing code, account holder name must exactly match affiliate KYC.",
        "- **Best for**: Partners earning BDT 50,000+ weekly. Banks handle the volume cleanly and produce statements suitable for tax filing.",
        "Bank transfers require re-confirmation of the destination account annually, a security precaution against account takeover.",
        "## USDT (TRC-20), cross-border, high-volume partners",
        "- **Minimum payout**: USD 100 (approximately BDT 12,000).",
        "- **Fee**: TRC-20 network fee (typically <$1); JeetBuzz covers it for verified affiliates.",
        "- **Timing**: 30 minutes to 4 hours.",
        "- **KYC**: Wallet address whitelisted through affiliate manager. Requires TRC-20 (not ERC-20).",
        "- **Best for**: Partners operating outside Bangladesh or handling volumes above BDT 100,000/week where mobile wallets become impractical.",
        "USDT payouts are irreversible on-chain. Whitelist the wallet address once, in writing, and never change it via casual chat.",
        "## Payout frequency and cut-off",
        "Commission for a weekly period (Monday 00:00 UTC through Sunday 23:59 UTC) settles Tuesday and pays out Wednesday. If Wednesday is a bank holiday, bank transfers roll to the next business day; wallet payouts still process. See [Withdrawal Time](/jeetbuzz-withdrawal-time) for exact expected windows across BD payment methods.",
        "## What KYC each payout requires",
        "Affiliate KYC is required once at signup and reviewed if you change payment method. Required documents:",
        "1. **National ID (NID) front + back** or Passport bio page.",
        "2. **Live selfie holding the ID.**",
        "3. **Payout account proof**, a screenshot of the bKash/Nagad/Rocket profile page, or a bank statement showing your name and account number, or the USDT wallet address in a signed screenshot.",
        "4. **Address proof**, utility bill or bank statement dated within 90 days.",
        "Fail any of these and the payout goes on hold until re-verified. See our [KYC checklist](/jeetbuzz-account-verification) for the exact rejection patterns.",
        "## Choosing the right method",
        "- Under BDT 20,000/week → **bKash** (or Nagad as backup).",
        "- BDT 20,000–50,000/week → **bKash** for speed or **bank** for tax paperwork.",
        "- BDT 50,000–200,000/week → **bank transfer** for reliability and statements.",
        "- Over BDT 200,000/week → **USDT** for speed and cross-border flexibility.",
        "You can change payout method at any time via the dashboard, but changes take effect from the next weekly cycle, not the current one.",
        "## Related pages",
        "- [Affiliate Dashboard](/jeetbuzz-affiliate-dashboard), see your commission balance before requesting payout.",
        "- [Affiliate Commission](/jeetbuzz-affiliate-commission), how weekly NGR translates into your balance.",
        "- [Affiliate Withdrawal](/jeetbuzz-affiliate-withdrawal), the request flow and status states.",
        "- [Partner Login](/jeetbuzz-partner-login), sign in to submit a payout request.",
        "## Neutral disclosure",
        "GetJeetBuzz is an editorial affiliate. Minimums, fees and timing described here reflect the current program structure and may change; the live dashboard is authoritative for your account. Payout is not gambling winnings, it is revenue-share commission on referred player NGR.",
      ]}
      bodyByLocale={{
        bn: [
          "## পাঁচটি affiliate payout রেল",
          "JeetBuzz সাপ্তাহিক commission পাঁচটি রেলে দেয়: **bKash**, **Nagad**, **Rocket**, **লোকাল ব্যাংক ট্রান্সফার** এবং **USDT (TRC-20)**। প্রতিটির আলাদা minimum, cut-off এবং KYC আছে। ছোট পার্টনার bKash, বড় পার্টনার ব্যাংক বা USDT।",
          "## bKash, ছোট ও মাঝারি পার্টনারের ডিফল্ট",
          "- **Minimum**: BDT ২,০০০। এর কম রোলওভার হয়।",
          "- **ফি**: verified affiliate-দের জন্য শূন্য।",
          "- **সময়**: business day-এ ২–২৪ ঘণ্টা।",
          "- **KYC**: bKash অ্যাকাউন্টের নাম = affiliate KYC-এর নাম।",
          "- **উপযোগী**: সাপ্তাহিক BDT ২,০০০–২০,০০০।",
          "affiliate profile-এ নিবন্ধিত bKash নম্বরেই process হয়। বদল করলে ২৪–৭২ ঘণ্টার re-verification।",
          "## Nagad, same-day fallback",
          "- **Minimum**: BDT ২,০০০।",
          "- **ফি**: শূন্য।",
          "- **সময়**: ২–১২ ঘণ্টা।",
          "- **KYC**: Nagad wallet নাম match।",
          "- **উপযোগী**: bKash-এ সমস্যা হলে switch।",
          "অনেক affiliate দুটোই file-এ রাখেন, request-এ method বাছাই করা যায়।",
          "## Rocket, ছোট footprint, নির্ভরযোগ্য",
          "- **Minimum**: BDT ২,০০০।",
          "- **ফি**: শূন্য।",
          "- **সময়**: ৪–২৪ ঘণ্টা।",
          "- **KYC**: Name-matched।",
          "- **উপযোগী**: যারা daily banking-এ Rocket ব্যবহার করেন।",
          "## Local bank, সাপ্তাহিক BDT ৫০,০০০-এর উপরে",
          "- **Minimum**: BDT ৫,০০০।",
          "- **ফি**: শূন্য (IFT covered)।",
          "- **সময়**: bank cut-off অনুযায়ী ১–৩ working day।",
          "- **KYC**: account number, IFSC/routing, holder name, সব affiliate KYC-এর সাথে exact match।",
          "- **উপযোগী**: সাপ্তাহিক BDT ৫০,০০০+। ব্যাংক ভলিউম সামলায়, কর filing-উপযোগী statement দেয়।",
          "ব্যাংক destination বছরে একবার re-confirm করতে হয়।",
          "## USDT (TRC-20), cross-border, উচ্চ ভলিউম",
          "- **Minimum**: USD ১০০ (~BDT ১২,০০০)।",
          "- **ফি**: TRC-20 network fee (<$1); JeetBuzz cover করে।",
          "- **সময়**: ৩০ মিনিট – ৪ ঘণ্টা।",
          "- **KYC**: whitelisted wallet address। TRC-20 লাগবে, ERC-20 নয়।",
          "- **উপযোগী**: বাংলাদেশের বাইরে বা BDT ১,০০,০০০+/সপ্তাহ।",
          "USDT payout on-chain irreversible। wallet address লিখিতভাবে একবার whitelist করুন, casual chat-এ কখনো বদলাবেন না।",
          "## Payout ফ্রিকোয়েন্সি ও cut-off",
          "সাপ্তাহিক period (Mon ০০:০০ UTC – Sun ২৩:৫৯ UTC) মঙ্গলবার settle হয়, বুধবার payout। বুধবার bank holiday হলে ব্যাংক transfer পরের business day-এ, wallet তবু process হয়। প্রত্যাশিত সময় দেখুন [Withdrawal Time](/jeetbuzz-withdrawal-time)।",
          "## প্রতিটি payout-এর KYC",
          "১. **NID front + back** বা passport bio page।",
          "২. **ID পাশে ধরে live selfie।**",
          "৩. **Payout account proof**, bKash/Nagad/Rocket profile screenshot, ব্যাংক statement, বা signed screenshot-এ USDT wallet address।",
          "৪. **Address proof**, ৯০ দিনের মধ্যে utility bill বা bank statement।",
          "যেকোনো একটি fail হলে payout hold হয়। বিস্তারিত [KYC checklist](/jeetbuzz-account-verification)।",
          "## সঠিক method বাছাই",
          "- BDT ২০,০০০/সপ্তাহের নিচে → **bKash** (Nagad backup)।",
          "- BDT ২০,০০০–৫০,০০০ → **bKash** (গতি) বা **bank** (কর ডকুমেন্ট)।",
          "- BDT ৫০,০০০–২,০০,০০০ → **bank transfer**।",
          "- BDT ২,০০,০০০-এর উপরে → **USDT**।",
          "যেকোনো সময় dashboard থেকে method বদল করা যায়, তবে পরের weekly cycle থেকে কার্যকর।",
          "## সম্পর্কিত পেজ",
          "- [Affiliate Dashboard](/jeetbuzz-affiliate-dashboard)",
          "- [Affiliate Commission](/jeetbuzz-affiliate-commission)",
          "- [Affiliate Withdrawal](/jeetbuzz-affiliate-withdrawal)",
          "- [Partner Login](/jeetbuzz-partner-login)",
          "## নিরপেক্ষ ঘোষণা",
          "GetJeetBuzz সম্পাদকীয় affiliate। Minimum/ফি/সময় বর্তমান program structure অনুযায়ী; পরিবর্তন সম্ভব। লাইভ ড্যাশবোর্ড authoritative। Payout gambling winning নয়, referred player NGR-এর revenue-share commission।",
        ],
      }}
      related={siblings(AFFILIATE_CLUSTER, PATH)}
      faqs={[
        { q: "What's the minimum affiliate payout on bKash?", a: "BDT 2,000 per weekly cycle. Anything below that rolls over to the next week until the threshold is met." },
        { q: "Does JeetBuzz charge affiliates a payout fee?", a: "No. Verified affiliates receive the full commission. JeetBuzz absorbs bKash/Nagad cash-out, bank IFT and TRC-20 network fees." },
        { q: "Which payout is fastest?", a: "USDT (TRC-20) is fastest, 30 minutes to 4 hours. Nagad is the fastest fiat option at 2–12 hours." },
        { q: "Can I change my payout method?", a: "Yes, via the dashboard. The change applies from the next weekly cycle, not the current one. Bank and USDT changes require KYC re-review." },
        { q: "What if my payout name doesn't match my KYC?", a: "The payout is rejected and returned to your balance. Update your payment profile to match KYC exactly, or update the KYC, you can't run mismatched names for AML reasons." },
        { q: "Is USDT ERC-20 supported?", a: "No. Only TRC-20 (Tron network) is supported for USDT payouts. ERC-20 addresses are rejected on submission." },
        { q: "How do I get a payment statement for tax filing?", a: "Every payout appears in the dashboard's Payout History block with reference, method and amount. Export CSV for the period you need. Bank transfers also produce a bank-side reference." },
      ]}
      faqsByLocale={{
        bn: [
          { q: "bKash-এ minimum payout কত?", a: "সাপ্তাহিক BDT ২,০০০। এর কম হলে পরের সপ্তাহে রোলওভার।" },
          { q: "JeetBuzz কি affiliate-এর কাছে payout fee নেয়?", a: "না। verified affiliate পুরো commission পান, bKash/Nagad cash-out, bank IFT, TRC-20 fee সব JeetBuzz cover করে।" },
          { q: "সবচেয়ে দ্রুত payout?", a: "USDT (TRC-20), ৩০ মিনিট থেকে ৪ ঘণ্টা। Fiat-এ Nagad দ্রুততম (২–১২ ঘণ্টা)।" },
          { q: "Payout method বদলানো যায়?", a: "হ্যাঁ, dashboard থেকে। পরের weekly cycle থেকে কার্যকর। Bank ও USDT বদলে KYC re-review।" },
          { q: "Payout নাম KYC-এর সাথে না মিললে?", a: "Payout reject হয়ে balance-এ ফিরে আসে। KYC-র সাথে exact match করুন. AML কারণে mismatch চলবে না।" },
          { q: "USDT ERC-20 সমর্থিত?", a: "না। শুধু TRC-20 (Tron network)। ERC-20 address জমাদানেই reject।" },
          { q: "কর filing-এর statement কীভাবে পাবো?", a: "Dashboard-এর Payout History block-এ প্রতিটি payout reference সহ থাকে। CSV export নিন। Bank transfer-এ bank-side reference-ও পাওয়া যায়।" },
        ],
      }}
    />
  ),
});