import { createFileRoute } from "@tanstack/react-router";
import { GuidePage } from "@/components/GuidePage";
import { canonicalLink, hreflangLinks, ogUrl, jsonLdScript, articleSchema } from "@/lib/schema";
import { AFFILIATE_CLUSTER, siblings } from "@/lib/clusters";

const PATH = "/jeetbuzz-affiliate-commission-rate";
const TITLE = "JeetBuzz Affiliate Commission Rate 2026 — Up to 60% Weekly Revenue Share";
const DESC = "Full JeetBuzz affiliate commission rate breakdown for 2026 — tiered up to 60% weekly revenue share, minimum active players and how commission is calculated.";

export const Route = createFileRoute("/jeetbuzz-affiliate-commission-rate")({
  head: () => ({
    meta: [
      { title: TITLE + " | GetJeetBuzz" },
      { name: "description", content: DESC },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESC },
      { property: "og:type", content: "article" },
      ogUrl(PATH),
    ],
    links: [canonicalLink(PATH), ...hreflangLinks(PATH)],
    scripts: [jsonLdScript(articleSchema({ headline: TITLE, description: DESC, path: PATH }))],
  }),
  component: () => (
    <GuidePage
      eyebrow="Affiliate"
      title={<>JeetBuzz Affiliate <span className="gold-text">Commission Rate</span></>}
      titleByLocale={{ bn: <>জিতবাজ অ্যাফিলিয়েট <span className="gold-text">কমিশন রেট</span></> }}
      subtitle="How the JeetBuzz affiliate commission rate is tiered, how the 60% top rate is actually reached, and what NGR really means on your dashboard."
      subtitleByLocale={{ bn: "জিতবাজ অ্যাফিলিয়েট কমিশন কীভাবে টিয়ার হয়, ৬০% পর্যন্ত রেট কীভাবে পৌঁছায় এবং ড্যাশবোর্ডে NGR-এর অর্থ কী।" }}
      ctaIntent="partners" ctaLabel="Join Partner Program"
      breadcrumbs={[{ name: "Help", path: "/help" }, { name: "Affiliate Commission Rate", path: PATH }]}
      articlePath={PATH} articleHeadline={TITLE} articleDescription={DESC}
      body={[
        "## Quick answer",
        "The JeetBuzz affiliate program pays **up to 60% weekly revenue share** on Net Gaming Revenue (NGR) generated by the players you refer. The exact rate you unlock depends on how many active depositing players you bring in each month.",
        "## Commission tiers",
        "| Tier | Active players / month | Revenue share |",
        "|---|---|---|",
        "| Starter | 1–5 | 25% |",
        "| Growth | 6–20 | 35% |",
        "| Pro | 21–50 | 45% |",
        "| Elite | 51+ | up to 60% |",
        "*Active player = deposited within the calendar month and placed at least one qualifying bet.* Tier is recalculated each week.",
        "## What NGR means",
        "Commission is paid on **Net Gaming Revenue**, not on turnover. NGR = deposits − withdrawals − bonuses − chargebacks − processing fees. On a losing week for the referred players you earn from that loss; on a winning week the balance can carry to the next cycle (negative carryover applies).",
        "## Sub-affiliate commission",
        "You also earn 3.5% referral commission on any affiliate you personally refer to the program — a small tail on top of your direct player NGR.",
        "## How to actually reach 60%",
        "The top tier is reached by consistent player quality, not just quantity. Five best practices:",
        "1. Send only region-matched traffic (BD players to BD landing, IN players to UPI-first landing).",
        "2. Warm players up with the bonus and payments guides *before* the affiliate link.",
        "3. Retain — reload-bonus content lifts NGR far more than new signups.",
        "4. Avoid incentive traffic (\"free bonus for signup\") — those players trigger negative NGR.",
        "5. Track weekly and cut sources with high withdrawal-to-deposit ratios.",
        "## Payout terms",
        "Weekly cycle, minimum payout typically 30 USD equivalent. See [Affiliate Withdrawal](/jeetbuzz-affiliate-withdrawal) for the exact schedule and supported rails.",
        "## Get started",
        "Ready to apply? Read the [Affiliate Signup guide](/jeetbuzz-affiliate-signup), then submit your application from the [Affiliate Program overview](/affiliate-program).",
      ]}
      bodyByLocale={{
        bn: [
          "## দ্রুত উত্তর",
          "জিতবাজ অ্যাফিলিয়েট প্রোগ্রাম আপনার রেফার করা প্লেয়ারদের **Net Gaming Revenue (NGR)-এর উপর সর্বোচ্চ ৬০% পর্যন্ত সাপ্তাহিক রেভিনিউ শেয়ার** দেয়। কত রেট পাবেন তা নির্ভর করে আপনি প্রতি মাসে কতজন সক্রিয় ডিপোজিটকারী প্লেয়ার আনছেন তার উপর।",
          "## কমিশন টিয়ার",
          "| টিয়ার | মাসিক সক্রিয় প্লেয়ার | রেভিনিউ শেয়ার |",
          "|---|---|---|",
          "| Starter | ১–৫ | ২৫% |",
          "| Growth | ৬–২০ | ৩৫% |",
          "| Pro | ২১–৫০ | ৪৫% |",
          "| Elite | ৫১+ | সর্বোচ্চ ৬০% |",
          "*সক্রিয় প্লেয়ার = মাসের ভেতরে ডিপোজিট করেছে এবং অন্তত একটি বাজি ধরেছে।* টিয়ার প্রতি সপ্তাহে পুনঃগণনা হয়।",
          "## NGR-এর অর্থ",
          "কমিশন **Net Gaming Revenue**-এর উপর দেওয়া হয়, টার্নওভারের উপর নয়। NGR = ডিপোজিট − উইথড্রয়াল − বোনাস − চার্জব্যাক − প্রসেসিং ফি। প্লেয়াররা কোনো সপ্তাহে হেরে গেলে আপনি সেই ক্ষতি থেকে আয় করেন; জিতলে ব্যালেন্স পরের সাইকেলে ক্যারি হতে পারে (নেগেটিভ ক্যারিওভার প্রযোজ্য)।",
          "## সাব-অ্যাফিলিয়েট কমিশন",
          "আপনি নিজে যদি অন্য কোনো অ্যাফিলিয়েটকে প্রোগ্রামে যুক্ত করেন, তার আয়ের ৩.৫% আপনি অতিরিক্তভাবে পাবেন।",
          "## ৬০% রেট বাস্তবে কীভাবে পৌঁছাব",
          "টপ টিয়ার শুধু সংখ্যা দিয়ে নয়, প্লেয়ার কোয়ালিটি দিয়ে অর্জিত হয়। পাঁচটি প্র্যাক্টিস:",
          "১. রিজিয়ন-ম্যাচড ট্রাফিক পাঠান — বিডি প্লেয়ারকে বিডি ল্যান্ডিংয়ে, ভারতীয় প্লেয়ারকে UPI-ফার্স্ট ল্যান্ডিংয়ে।",
          "২. অ্যাফিলিয়েট লিংক দেওয়ার *আগে* বোনাস ও পেমেন্ট গাইড দিয়ে প্লেয়ারকে গরম করুন।",
          "৩. রিটেনশন — রিলোড-বোনাস কনটেন্ট নতুন সাইনআপের চেয়ে অনেক বেশি NGR তোলে।",
          "৪. \"ফ্রি বোনাস\" ধরনের ইনসেন্টিভ ট্রাফিক এড়ান — এসব প্লেয়ার নেগেটিভ NGR ট্রিগার করে।",
          "৫. সাপ্তাহিক ট্র্যাক করুন এবং যেসব সোর্সে উইথড্রয়াল/ডিপোজিট রেশিও বেশি সেগুলো বন্ধ করুন।",
          "## পেআউট শর্তাবলী",
          "সাপ্তাহিক সাইকেল, সাধারণত সর্বনিম্ন ৩০ USD সমতুল্য। বিস্তারিত সময়সূচি ও সাপোর্টেড রেলের জন্য [Affiliate Withdrawal](/jeetbuzz-affiliate-withdrawal) দেখুন।",
          "## শুরু করুন",
          "আবেদন করতে প্রস্তুত? আগে [Affiliate Signup গাইড](/jeetbuzz-affiliate-signup) পড়ুন, তারপর [Affiliate Program](/affiliate-program) পেজ থেকে আবেদন জমা দিন।",
        ],
      }}
      related={siblings(AFFILIATE_CLUSTER, PATH)}
      faqs={[
        { q: "Is 60% the guaranteed commission for everyone?", a: "No. 60% is the top-tier rate. Most affiliates start at 25% and unlock higher tiers as monthly active-player counts grow." },
        { q: "When is commission calculated?", a: "Weekly, on a rolling Monday-to-Sunday cycle. NGR is finalised on Monday and payouts are processed after review." },
        { q: "Does commission apply to bonus play?", a: "No. Bonus balance is deducted from NGR before commission is calculated — you earn only on real-money losses." },
        { q: "What is negative carryover?", a: "If your referred players win overall in a week, the negative NGR carries forward and reduces next week's commission until it is cleared." },
        { q: "Can I promote JeetBuzz on Google Ads?", a: "Brand bidding is not permitted per most operator T&C. Read the affiliate agreement carefully — violation can void commission." },
        { q: "What counts as an active player?", a: "A player who deposited at least once during the calendar month and placed at least one qualifying real-money bet." },
      ]}
      faqsByLocale={{
        bn: [
          { q: "৬০% কি সবার জন্য গ্যারান্টিড?", a: "না। ৬০% হলো সর্বোচ্চ টিয়ারের রেট। বেশিরভাগ অ্যাফিলিয়েট ২৫% থেকে শুরু করে এবং মাসিক সক্রিয় প্লেয়ার বাড়লে উচ্চ টিয়ার আনলক করে।" },
          { q: "কমিশন কবে গণনা হয়?", a: "সাপ্তাহিক, সোমবার থেকে রবিবার সাইকেলে। NGR সোমবার ফাইনাল হয় এবং রিভিউর পর পেআউট প্রসেস হয়।" },
          { q: "বোনাস প্লে-তে কি কমিশন প্রযোজ্য?", a: "না। বোনাস ব্যালেন্স NGR থেকে বাদ দেওয়া হয় — আপনি শুধু রিয়েল-মানি ক্ষতির উপর আয় করেন।" },
          { q: "নেগেটিভ ক্যারিওভার কী?", a: "আপনার রেফার করা প্লেয়াররা কোনো সপ্তাহে জিতে গেলে সেই নেগেটিভ NGR পরের সপ্তাহে ক্যারি হয় এবং সেটি ক্লিয়ার না হওয়া পর্যন্ত কমিশন কমায়।" },
          { q: "সক্রিয় প্লেয়ার বলতে কী বোঝায়?", a: "যে প্লেয়ার মাসের ভেতরে অন্তত একবার ডিপোজিট করেছে এবং অন্তত একটি বৈধ রিয়েল-মানি বাজি ধরেছে।" },
          { q: "গুগল অ্যাডসে জিতবাজ প্রচার করা যায়?", a: "বেশিরভাগ অপারেটর T&C-তে ব্র্যান্ড বিডিং নিষিদ্ধ। অ্যাফিলিয়েট চুক্তি ভালোভাবে পড়ুন — লঙ্ঘন করলে কমিশন বাতিল হতে পারে।" },
        ],
      }}
    />
  ),
});