import { createFileRoute } from "@tanstack/react-router";
import { GuidePage } from "@/components/GuidePage";
import { canonicalLink, hreflangLinks, ogUrl, jsonLdScript, articleSchema } from "@/lib/schema";

const PATH = "/jeetbuzz-nagad-withdrawal";
const TITLE = "JeetBuzz Nagad Withdrawal 2026. Steps, Minimum, Time & Fixes";
const DESC = "JeetBuzz Nagad withdrawal for 2026, exact 5-step cash-out flow, minimum amount, real credit timing, KYC requirements and how to fix a Pending or rejected withdrawal.";

export const Route = createFileRoute("/jeetbuzz-nagad-withdrawal")({
  head: () => ({
    meta: [
      { title: TITLE + " | GetJeetBuzz" },
      { name: "description", content: DESC },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESC },
      { property: "og:type", content: "article" },
      ogUrl(PATH),
    ],
    links: [canonicalLink(PATH), ...hreflangLinks(PATH)],
    scripts: [jsonLdScript(articleSchema({ headline: TITLE, description: DESC, path: PATH }))],
  }),
  component: () => (
    <GuidePage
      eyebrow="Payments"
      title={<>JeetBuzz <span className="gold-text">Nagad Withdrawal</span></>}
      subtitle="The complete 2026 Nagad withdrawal walkthrough, the exact cash-out steps, minimums and caps, real processing times, KYC traps, and how to unblock a Pending or rejected request."
      ctaIntent="signup" ctaLabel="Open Withdrawal Page"
      breadcrumbs={[{ name: "Payments", path: "/payments" }, { name: "Nagad Withdrawal", path: PATH }]}
      articlePath={PATH} articleHeadline={TITLE} articleDescription={DESC}
      body={[
        "## Why Nagad for withdrawals",
        "Nagad is one of the two dominant mobile wallets in Bangladesh, and JeetBuzz supports it for both deposit and withdrawal. Nagad's own cash-out is usually cheaper than bKash's, and the daily limits on higher KYC tiers are generous, which makes it a strong choice when your withdrawal is above BDT 10,000 or when bKash is under a rare service outage.",
        "## The 5-step Nagad withdrawal flow",
        "1. **Log in to JeetBuzz** and open Cashier → Withdrawal.",
        "2. **Select Nagad.** The cashier confirms the Nagad number registered on your account. If the number is empty, add it under Profile → Payment Methods, it must match your JeetBuzz KYC name.",
        "3. **Enter the withdrawal amount.** The cashier shows the fee (if any), the amount that will land in Nagad and any daily/weekly cap remaining on your account.",
        "4. **Confirm.** A 6-digit OTP is sent to your registered phone, enter it inside the withdrawal form to submit the request.",
        "5. **Wait for the SMS from Nagad.** Once the money is disbursed, Nagad sends its usual credit SMS with a TrxID. Typical timing: 30 minutes to 4 hours on business days.",
        "## Minimums, caps and fees",
        "- **Minimum withdrawal**: BDT 500 per request.",
        "- **Maximum per request**: BDT 25,000 on standard tier, larger amounts split into multiple requests automatically.",
        "- **Daily cap**: BDT 50,000 aggregate across all methods, subject to your Nagad KYC tier.",
        "- **Fee**: JeetBuzz doesn't add a withdrawal fee. Nagad's own cash-out charge applies when you eventually cash out the balance to your Nagad agent.",
        "See [Withdrawal Time](/jeetbuzz-withdrawal-time) for the timing tables across every JeetBuzz payment rail.",
        "## Real credit timing",
        "- **Small amount (up to BDT 5,000) during business hours**: 30 minutes to 2 hours.",
        "- **Mid amount (BDT 5,000–15,000)**: 1–4 hours.",
        "- **Large amount (BDT 15,000+)**: 2–8 hours; may trigger an extra risk review.",
        "- **Outside business hours (10 PM – 8 AM)**: queued for morning batch, count 6–12 hours.",
        "- **First withdrawal from a new account**: allow the full first-time review of 24–48 hours.",
        "The single biggest driver of speed is KYC completeness. See [Account Verification](/jeetbuzz-account-verification) for the exact document checklist.",
        "## What KYC Nagad withdrawal requires",
        "1. National ID (NID), front and back.",
        "2. Live selfie holding the NID.",
        "3. Nagad account registered in your own name (matching the NID above).",
        "4. For amounts above BDT 25,000 in aggregate, an address proof from the last 90 days.",
        "Nagad number and NID name must match exactly, no nicknames, no third-party wallets. A Nagad wallet registered in a family member's name will be rejected under AML rules.",
        "## Why a Nagad withdrawal goes to Pending",
        "1. **KYC missing or expired**, the most common reason. Complete or refresh KYC via Profile.",
        "2. **Name mismatch**, the Nagad wallet name doesn't equal the JeetBuzz KYC name. Update the Nagad number to a wallet you personally own.",
        "3. **Withdrawal above the cap**, the request exceeds your Nagad KYC tier's daily cap. Split into smaller amounts or upgrade the Nagad KYC.",
        "4. **Bonus wagering unmet**, funds you deposited under a bonus are locked until the wagering requirement is satisfied. Check the bonus terms; see [First Deposit Bonus](/jeetbuzz-first-deposit-bonus) for how rollover works.",
        "5. **Random risk review**, 3–5% of withdrawals are pulled for a manual second look. Nothing to do, the review clears within 24 hours in almost every case.",
        "6. **Nagad-side outage**, occasionally Nagad itself pauses disbursements. Refresh, don't resubmit.",
        "7. **Recent deposit not yet cleared**, deposits typically settle in minutes, but a rare longer settlement blocks withdrawal of that specific balance for 2–4 hours.",
        "The dedicated [Withdrawal Pending](/jeetbuzz-withdrawal-pending) page walks each of these with the live-chat script that unblocks them.",
        "## Recovering a rejected Nagad withdrawal",
        "Rejected withdrawals return the money to your JeetBuzz balance within an hour. To reissue:",
        "1. Open live chat and ask for the **specific rejection reason**, reasons like 'KYC insufficient' or 'name mismatch' tell you exactly what to fix.",
        "2. Fix the underlying issue (usually update KYC or the Nagad number).",
        "3. Submit a fresh withdrawal request. Do not resubmit the old one, it stays rejected in the log.",
        "## Playing safe with Nagad",
        "- Never share your Nagad PIN. JeetBuzz support does not need it.",
        "- Keep Nagad SMS notifications on so any unexpected credit is visible immediately.",
        "- If you receive a credit SMS but the JeetBuzz withdrawal still shows Pending, screenshot the SMS and share via live chat, the status refresh is manual in that rare case.",
        "## Related pages",
        "- [Nagad Guide](/nagad-guide), broader Nagad payment method overview.",
        "- [bKash Deposit](/jeetbuzz-bkash-deposit), the mirror-image deposit rail.",
        "- [Withdrawal Time](/jeetbuzz-withdrawal-time), timing tables across all rails.",
        "- [Withdrawal Pending](/jeetbuzz-withdrawal-pending), the seven real causes and fixes.",
        "- [Account Verification](/jeetbuzz-account-verification), the KYC checklist that unblocks fast withdrawals.",
        "- [Payments Hub](/payments), every payment method in one place.",
        "## Neutral disclosure",
        "GetJeetBuzz is an editorial affiliate. Nagad caps, KYC tiers and fees follow Nagad's own published tariff; the Nagad app and JeetBuzz cashier are the live source of truth. Withdraw only funds you're comfortable taking out of play; use [self-exclusion](/how-to-delete-jeetbuzz-account) if gambling is causing stress.",
      ]}
      bodyByLocale={{
        bn: [
          "## Nagad কেন withdrawal-এর জন্য",
          "Nagad বাংলাদেশের দুটি প্রধান mobile wallet-এর একটি, JeetBuzz এটা deposit ও withdrawal দুই দিকেই সমর্থন করে। Nagad-এর নিজের cash-out সাধারণত bKash-এর চেয়ে সস্তা, উচ্চ KYC tier-এ daily limit উদার. BDT ১০,০০০-এর উপরে withdrawal-এ বা bKash outage-এর সময় শক্ত পছন্দ।",
          "## ৫ ধাপ Nagad withdrawal",
          "১. **JeetBuzz-এ লগইন**, Cashier → Withdrawal।",
          "২. **Nagad select।** Cashier আপনার account-এ নিবন্ধিত Nagad নম্বর দেখাবে। খালি হলে Profile → Payment Methods থেকে যোগ করুন. JeetBuzz KYC-এর সাথে name match লাগবে।",
          "৩. **Amount দিন।** Cashier ফি (যদি থাকে), Nagad-এ যা যাবে, বাকি daily/weekly cap দেখাবে।",
          "৪. **Confirm।** নিবন্ধিত ফোনে ৬-অঙ্কের OTP আসবে, form-এ দিয়ে submit।",
          "৫. **Nagad SMS-এর অপেক্ষা।** টাকা disburse হলে Nagad TrxID সহ credit SMS পাঠাবে। Business day-এ সাধারণত ৩০ মিনিট–৪ ঘণ্টা।",
          "## Minimum, cap, ফি",
          "- **Minimum**: প্রতি request BDT ৫০০।",
          "- **Per request max**: standard tier-এ BDT ২৫,০০০, বেশি হলে auto-split।",
          "- **Daily cap**: সব method মিলিয়ে aggregate BDT ৫০,০০০, Nagad KYC tier-নির্ভর।",
          "- **ফি**: JeetBuzz withdrawal fee যোগ করে না। Nagad-এর নিজের cash-out charge agent থেকে তোলার সময় প্রযোজ্য।",
          "সব রেলের timing দেখুন [Withdrawal Time](/jeetbuzz-withdrawal-time)।",
          "## বাস্তব credit সময়",
          "- **ছোট (BDT ৫,০০০ পর্যন্ত), business hour**: ৩০ মিনিট–২ ঘণ্টা।",
          "- **মাঝারি (৫,০০০–১৫,০০০)**: ১–৪ ঘণ্টা।",
          "- **বড় (১৫,০০০+)**: ২–৮ ঘণ্টা; অতিরিক্ত risk review হতে পারে।",
          "- **Business hour-এর বাইরে (রাত ১০–সকাল ৮)**: সকালের batch-এ queued, ৬–১২ ঘণ্টা।",
          "- **নতুন অ্যাকাউন্টের প্রথম withdrawal**: প্রথমবারের review ২৪–৪৮ ঘণ্টা।",
          "গতির প্রধান নিয়ামক KYC সম্পূর্ণতা। [Account Verification](/jeetbuzz-account-verification) দেখুন।",
          "## Nagad withdrawal-এর KYC",
          "১. NID front ও back।",
          "২. NID পাশে ধরে live selfie।",
          "৩. নিজের নামে registered Nagad account (উপরের NID-এর সাথে match)।",
          "৪. Aggregate BDT ২৫,০০০-এর উপরে হলে ৯০ দিনের address proof।",
          "Nagad নম্বর ও NID name হুবহু মিলতে হবে, nickname/third-party wallet নয়। পরিবারের সদস্যের নামে wallet AML-এ reject।",
          "## Nagad withdrawal Pending কেন",
          "১. **KYC অসম্পূর্ণ/expired**, সবচেয়ে সাধারণ। Profile থেকে refresh।",
          "২. **Name mismatch**. Nagad wallet name = JeetBuzz KYC name হতে হবে।",
          "৩. **Cap-এর উপরে**. Nagad KYC tier-এর daily cap ছাড়িয়েছে। Split করুন বা Nagad KYC upgrade।",
          "৪. **Bonus wagering unmet**, bonus deposit rollover-এর আগে lock। [First Deposit Bonus](/jeetbuzz-first-deposit-bonus) দেখুন।",
          "৫. **Random risk review**, ৩–৫% withdrawal manual review-এ যায়। ২৪ ঘণ্টায় clear।",
          "৬. **Nagad-side outage**, refresh, resubmit নয়।",
          "৭. **সাম্প্রতিক deposit unsettled**, বিরল দীর্ঘ settlement সেই balance ২–৪ ঘণ্টা lock করে।",
          "প্রতিটির live-chat script [Withdrawal Pending](/jeetbuzz-withdrawal-pending)-এ।",
          "## Rejected withdrawal recovery",
          "Rejected withdrawal ১ ঘণ্টায় JeetBuzz balance-এ ফেরে। পুনরায়:",
          "১. Live chat-এ **specific rejection reason** চান, 'KYC insufficient', 'name mismatch', কী ঠিক করতে হবে বলে।",
          "২. মূল সমস্যা ঠিক করুন (সাধারণত KYC বা Nagad নম্বর)।",
          "৩. নতুন withdrawal request দিন, পুরনোটা resubmit নয়।",
          "## Nagad-এ নিরাপদ থাকা",
          "- Nagad PIN কখনো share নয়।",
          "- Nagad SMS on রাখুন, unexpected credit তাৎক্ষণিক দৃশ্যমান।",
          "- Credit SMS এসেছে কিন্তু JeetBuzz-এ এখনো Pending. SMS screenshot live chat-এ পাঠান।",
          "## সম্পর্কিত পেজ",
          "- [Nagad Guide](/nagad-guide)",
          "- [bKash Deposit](/jeetbuzz-bkash-deposit)",
          "- [Withdrawal Time](/jeetbuzz-withdrawal-time)",
          "- [Withdrawal Pending](/jeetbuzz-withdrawal-pending)",
          "- [Account Verification](/jeetbuzz-account-verification)",
          "- [Payments Hub](/payments)",
          "## নিরপেক্ষ ঘোষণা",
          "GetJeetBuzz সম্পাদকীয় affiliate। Nagad cap/KYC tier/fee Nagad-এর নিজস্ব tariff অনুসরণ করে। খেলার বাইরে আনতে স্বাচ্ছন্দ্য বোধ করা তহবিলই তুলুন; চাপ হলে [self-exclusion](/how-to-delete-jeetbuzz-account)।",
        ],
      }}
      related={[
        { to: "/nagad-guide", title: "Nagad Guide", desc: "Broader Nagad payment method overview." },
        { to: "/jeetbuzz-bkash-deposit", title: "bKash Deposit", desc: "Mirror-image deposit rail via bKash." },
        { to: "/jeetbuzz-withdrawal-time", title: "Withdrawal Time", desc: "Expected timing tables per payment rail." },
        { to: "/jeetbuzz-withdrawal-pending", title: "Withdrawal Pending", desc: "Seven real causes and fixes." },
        { to: "/jeetbuzz-account-verification", title: "Account Verification", desc: "KYC checklist for fast payouts." },
        { to: "/jeetbuzz-minimum-deposit", title: "Minimum Deposit", desc: "Thresholds per rail and per bonus." },
        { to: "/payments", title: "Payments Hub", desc: "Every JeetBuzz payment method mapped." },
        { to: "/help", title: "Help Center", desc: "Support pillar, deposits, withdrawals, appeals." },
      ]}
      faqs={[
        { q: "What's the minimum Nagad withdrawal?", a: "BDT 500 per request. Amounts smaller than that can't be sent as a standalone withdrawal, combine into a larger single request." },
        { q: "How long does a JeetBuzz-to-Nagad withdrawal actually take?", a: "During business hours, 30 minutes to 4 hours is typical. Requests submitted at night queue for the morning batch, count 6–12 hours." },
        { q: "Does JeetBuzz charge a fee for Nagad withdrawal?", a: "No. JeetBuzz doesn't add a withdrawal fee. Nagad's own cash-out charge applies when you cash out the balance to an agent." },
        { q: "Why is my Nagad withdrawal stuck on Pending?", a: "Usually KYC incomplete, name mismatch, cap exceeded, or unmet bonus wagering. A small percentage go to random review, which clears in 24 hours." },
        { q: "Can I withdraw to a family member's Nagad account?", a: "No. AML rules require the Nagad wallet name to match your JeetBuzz KYC. Third-party wallets are rejected." },
        { q: "What is the daily withdrawal cap?", a: "BDT 50,000 aggregate across all methods on the standard tier, subject to your Nagad KYC tier limits." },
        { q: "My withdrawal was rejected, do I lose the money?", a: "No. Rejected withdrawals return to your JeetBuzz balance within an hour. Ask support for the specific rejection reason, fix it, then submit a fresh request." },
      ]}
      faqsByLocale={{
        bn: [
          { q: "Nagad-এ minimum withdrawal কত?", a: "প্রতি request BDT ৫০০। এর কম standalone withdrawal হয় না, বড় request-এ combine করুন।" },
          { q: "JeetBuzz → Nagad withdrawal আসলে কতক্ষণ?", a: "Business hour-এ ৩০ মিনিট–৪ ঘণ্টা স্বাভাবিক। রাতে queued, ৬–১২ ঘণ্টা।" },
          { q: "Nagad withdrawal-এ JeetBuzz ফি নেয়?", a: "না। Nagad-এর নিজের agent cash-out charge প্রযোজ্য।" },
          { q: "Nagad withdrawal Pending কেন?", a: "সাধারণত KYC অসম্পূর্ণ, name mismatch, cap ছাড়িয়েছে বা bonus wagering unmet। কিছু random review-এ যায় (২৪ ঘণ্টায় clear)।" },
          { q: "পরিবারের সদস্যের Nagad-এ withdrawal করা যায়?", a: "না। AML-এ Nagad wallet name JeetBuzz KYC-এর সাথে মিলতে হবে। Third-party reject।" },
          { q: "Daily withdrawal cap?", a: "Standard tier-এ সব method মিলিয়ে aggregate BDT ৫০,০০০; Nagad KYC tier limit-নির্ভর।" },
          { q: "Withdrawal reject হলে টাকা কি হারিয়ে যায়?", a: "না। ১ ঘণ্টায় JeetBuzz balance-এ ফেরে। Specific reason নিয়ে ঠিক করে নতুন request দিন।" },
        ],
      }}
    />
  ),
});