import { createFileRoute } from "@tanstack/react-router";
import { GuidePage } from "@/components/GuidePage";
import { canonicalLink, hreflangLinks, ogUrl, jsonLdScript, articleSchema } from "@/lib/schema";
import { PROBLEMS_CLUSTER, siblings } from "@/lib/clusters";

const PATH = "/jeetbuzz-deposit-failed";
const TITLE = "JeetBuzz Deposit Failed 2026. Debited But Not Credited? Fix It Fast";
const DESC = "JeetBuzz deposit failed in 2026, money debited but not credited, wrong reference, name mismatch, expired session, every cause with the exact evidence support needs.";

export const Route = createFileRoute("/jeetbuzz-deposit-failed")({
  head: () => ({
    meta: [
      { title: TITLE + " | GetJeetBuzz" },
      { name: "description", content: DESC },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESC },
      { property: "og:type", content: "article" },
      ogUrl(PATH),
    ],
    links: [canonicalLink(PATH), ...hreflangLinks(PATH)],
    scripts: [jsonLdScript(articleSchema({ headline: TITLE, description: DESC, path: PATH }))],
  }),
  component: () => (
    <GuidePage
      eyebrow="Payments"
      title={<>JeetBuzz Deposit <span className="gold-text">Failed</span></>}
      subtitle="Money left your wallet but did not land in JeetBuzz? Work through the ranked causes below, with the four pieces of evidence support needs to recover it."
      ctaIntent="login" ctaLabel="Retry Deposit"
      breadcrumbs={[{ name: "Help", path: "/help" }, { name: "Deposit Failed", path: PATH }]}
      articlePath={PATH} articleHeadline={TITLE} articleDescription={DESC}
      body={[
        "## Do not deposit a second time",
        "The instinct after a failed deposit is to try again immediately with the same amount. **Don't.** Two deposits with the same TxID sequence often trigger fraud flags and freeze both. Wait 15 minutes and check three things before doing anything else:",
        "1. **Cashier → Deposit history.** Sometimes the deposit is marked 'Success' with a small delay, the balance updates but no notification fires.",
        "2. **Your wallet's outgoing transaction list.** Confirm the money actually left your side.",
        "3. **Refresh the JeetBuzz page.** Some balance updates need a reload to appear.",
        "If the money left your wallet but Cashier still shows nothing, work through the six causes below.",
        "## The six real causes of a failed deposit",
        "### 1. Wrong deposit reference",
        "Every deposit needs a unique reference number generated by JeetBuzz Cashier. Reusing an old reference, typing it wrong, or omitting it makes the payment untraceable. Symptom: money debited, no credit, no error. Fix: contact support with your wallet TxID; they can manually match it to your account. Full detail: [Deposit Problem](/jeetbuzz-deposit-problem).",
        "### 2. Deposit session expired",
        "Cashier deposit slots expire in 15–30 minutes. Paying against an expired slot is treated as an unrelated payment. Symptom: 'This deposit request has expired' on the confirm screen, or silent failure. Fix: always start a fresh deposit slot before initiating the wallet transfer.",
        "### 3. Name mismatch",
        "The wallet you deposit from must be in your own name matching KYC. A friend or family member's wallet triggers manual review. Symptom: deposit pending for hours, then rejected. Fix: use only wallets in your own legal name, see [Account Verification](/jeetbuzz-account-verification).",
        "### 4. Amount outside deposit limits",
        "Each method has a minimum and maximum per transaction (bKash typically 300–25,000 BDT for personal, EasyPaisa 100–100,000 PKR, UPI ₹100–₹100,000). Symptom: silent failure or 'transaction limit exceeded' on your wallet side. Fix: check the cashier's stated min/max before sending. Split large deposits into multiple within-limit transactions.",
        "### 5. Wrong recipient number / address",
        "Copy-pasting the wrong bKash number, USDT address or UPI ID sends money to a stranger. This is not recoverable through JeetBuzz, the funds went to an account outside their system. Fix: always copy the recipient details afresh from Cashier for each deposit; never save them from a previous session.",
        "### 6. Bank / wallet down for maintenance",
        "bKash, Nagad, EasyPaisa and UPI schedule maintenance windows (usually 2–4 AM local time). Symptom: transaction shows 'Pending' on the wallet side for over 30 minutes. Fix: wait for the wallet to resolve the pending status. Money is not lost, it will either credit or auto-refund within 24 hours.",
        "## The four pieces of evidence support needs",
        "When you contact support, include all four in your first message. Without them, expect a 30-minute back-and-forth:",
        "1. **Wallet TxID**, the transaction ID from your wallet's history (bKash calls it 'Transaction ID', UPI calls it 'UTR', USDT calls it 'Hash').",
        "2. **Amount sent**, exact figure in the wallet's currency.",
        "3. **Timestamp**, date and time you initiated the payment.",
        "4. **JeetBuzz deposit reference**, the reference number Cashier gave you (if any).",
        "Attach a screenshot of the wallet transaction if possible.",
        "## The support script",
        "> *Hello. My deposit to JeetBuzz failed. Money was debited from my [WALLET] but not credited to my account. Wallet TxID: [ID]. Amount: [AMOUNT] [CURRENCY]. Timestamp: [DATE TIME]. JeetBuzz deposit reference: [REF]. Username: [USERNAME]. Screenshot attached. Please investigate and credit the deposit.*",
        "Expect resolution within 2–6 hours. Failed deposits are the most common support ticket type, the finance team handles them daily.",
        "## When to request a wallet-side refund",
        "If the wallet transaction shows 'Failed' or 'Reversed' on your side (not on JeetBuzz's), the money never left, it will be auto-refunded to your wallet balance within 24 hours. If it doesn't auto-refund, contact your wallet's support (bKash *247, Nagad *167, EasyPaisa *786) rather than JeetBuzz.",
        "## Prevention checklist",
        "- Always start a fresh deposit slot in Cashier before paying.",
        "- Copy the recipient details fresh each time.",
        "- Keep the wallet TxID screenshot until the balance credits.",
        "- Stay within the stated min/max limits.",
        "- Use only your own KYC-matched wallet.",
        "- Avoid depositing during wallet maintenance windows (usually 2–4 AM local).",
        "## Related help",
        "- [Deposit Problem](/jeetbuzz-deposit-problem). Phase A companion.",
        "- [Deposit Guide](/deposit-guide), first-time deposit walkthrough.",
        "- [Withdrawal Pending](/jeetbuzz-withdrawal-pending), sister problem.",
        "- [bKash Deposit Guide](/jeetbuzz-bkash-deposit). BD-specific.",
        "## Neutral disclosure",
        "GetJeetBuzz is an editorial affiliate. Deposit success depends on your wallet provider, network conditions, and the operator's Cashier, most failures are recoverable, but only with correct evidence. Play within a fixed budget and use [self-exclusion](/how-to-delete-jeetbuzz-account) if it stops feeling optional.",
      ]}
      bodyByLocale={{
        bn: [
          "## দ্বিতীয়বার ডিপোজিট করবেন না",
          "Failed deposit-এর পর তৎক্ষণাৎ একই অ্যামাউন্ট আবার পাঠানোর প্রবৃত্তি হয়। **করবেন না।** একই TxID sequence-এ দুটি ডিপোজিট fraud flag ট্রিগার করে দুটোই freeze করতে পারে। ১৫ মিনিট অপেক্ষা করে ৩টি চেক করুন:",
          "১. **Cashier → Deposit history।** কখনো 'Success' দেখায় কিন্তু notification আসে না।",
          "২. **আপনার ওয়ালেটের outgoing transaction list।** টাকা আসলেই বেরিয়েছে কিনা নিশ্চিত হন।",
          "৩. **JeetBuzz পেজ refresh করুন।** কিছু balance update reload-এ আসে।",
          "তবুও ব্যালেন্স না এলে নিচের ৬ কারণ দেখুন।",
          "## ৬টি আসল কারণ",
          "### ১. ভুল ডিপোজিট reference",
          "প্রতিটি ডিপোজিটের একটি unique reference থাকে Cashier থেকে। পুরনো reference reuse বা ভুল লিখলে payment untraceable হয়। উপসর্গ: money গেছে, credit হয়নি, error নেই। সমাধান: wallet TxID সহ সাপোর্টকে জানান, [Deposit Problem](/jeetbuzz-deposit-problem)।",
          "### ২. Deposit session expired",
          "Cashier slot ১৫–৩০ মিনিটে expire হয়। Expired slot-এ pay করলে সেটা অন্য payment হিসেবে ধরা হয়। সমাধান: transfer শুরুর আগে সবসময় ফ্রেশ slot নিন।",
          "### ৩. নাম মিসম্যাচ",
          "যে ওয়ালেট থেকে ডিপোজিট করছেন সেটা আপনার KYC নামের সঙ্গে মিলতে হবে। বন্ধু/পরিবারের ওয়ালেট manual review ট্রিগার করে। শুধু নিজের নামের ওয়ালেট ব্যবহার করুন, [Account Verification](/jeetbuzz-account-verification)।",
          "### ৪. Deposit limit-এর বাইরে",
          "প্রতিটি মেথডের min/max থাকে (bKash ৩০০–২৫,০০০ BDT personal)। উপসর্গ: silent failure বা 'transaction limit exceeded'। Cashier-এর stated min/max দেখে পাঠান।",
          "### ৫. ভুল recipient নম্বর/address",
          "ভুল bKash নম্বর বা UPI ID কপি-পেস্ট করলে টাকা অচেনা কারো কাছে যায়। এটা JeetBuzz-এর মাধ্যমে recover হয় না। প্রতিটি ডিপোজিটে Cashier থেকে ফ্রেশ recipient details কপি করুন।",
          "### ৬. Bank/wallet maintenance",
          "bKash, Nagad, UPI স্থানীয় সময় সাধারণত ২–৪ AM maintenance-এ থাকে। উপসর্গ: ওয়ালেটে ৩০ মিনিটেরও বেশি Pending। ২৪ ঘণ্টার মধ্যে credit বা auto-refund হবে।",
          "## সাপোর্টে ৪টি evidence পাঠান",
          "প্রথম মেসেজেই সব ৪টি দিন, না হলে ৩০ মিনিট back-and-forth:",
          "১. **Wallet TxID**, ওয়ালেট history থেকে (bKash: Transaction ID, UPI: UTR, USDT: Hash)।",
          "২. **Amount sent**, exact অঙ্ক।",
          "৩. **Timestamp**, payment initiate-এর তারিখ ও সময়।",
          "৪. **JeetBuzz deposit reference**. Cashier-এর reference (থাকলে)।",
          "সম্ভব হলে wallet screenshot attach করুন।",
          "## সাপোর্ট script",
          "> *Hello. My deposit to JeetBuzz failed. Money was debited from my [WALLET] but not credited. Wallet TxID: [ID]. Amount: [AMOUNT] BDT. Timestamp: [DATE TIME]. JeetBuzz deposit reference: [REF]. Username: [USERNAME]. Screenshot attached. Please credit the deposit.*",
          "২–৬ ঘণ্টায় resolve হয় সাধারণত।",
          "## Wallet-side refund কখন",
          "ওয়ালেটে 'Failed' বা 'Reversed' দেখালে টাকা যায়নি, ২৪ ঘণ্টায় auto-refund হবে। না হলে ওয়ালেট সাপোর্ট (bKash *247, Nagad *167) কল করুন।",
          "## Prevention checklist",
          "- সবসময় ফ্রেশ Cashier slot নিন।",
          "- প্রতিবার recipient details ফ্রেশ কপি করুন।",
          "- ব্যালেন্স credit হওয়া পর্যন্ত TxID screenshot রাখুন।",
          "- Stated min/max-এর মধ্যে থাকুন।",
          "- শুধু নিজের KYC-matched ওয়ালেট ব্যবহার করুন।",
          "- Maintenance window (২–৪ AM) এড়িয়ে চলুন।",
          "## সম্পর্কিত সাহায্য",
          "- [Deposit Problem](/jeetbuzz-deposit-problem)",
          "- [Deposit Guide](/deposit-guide)",
          "- [Withdrawal Pending](/jeetbuzz-withdrawal-pending)",
          "- [bKash Deposit Guide](/jeetbuzz-bkash-deposit)",
          "## নিরপেক্ষ ঘোষণা",
          "GetJeetBuzz সম্পাদকীয় অ্যাফিলিয়েট। বেশিরভাগ failed deposit recoverable, কিন্তু সঠিক evidence ছাড়া নয়। জুয়া চাপ সৃষ্টি করলে [self-exclusion](/how-to-delete-jeetbuzz-account) ব্যবহার করুন।",
        ],
      }}
      related={siblings(PROBLEMS_CLUSTER, PATH)}
      faqs={[
        { q: "Money left my bKash but JeetBuzz shows nothing. Is it lost?", a: "Almost never. If your wallet shows a successful outgoing transaction, the money reached a valid recipient. Support can trace and manually credit it, provide the wallet TxID." },
        { q: "How fast should JeetBuzz recover a failed deposit?", a: "2–6 hours for straightforward cases with the four evidence items. Complex cases (wrong reference across multiple deposits, name mismatch) can take 24–48 hours." },
        { q: "Should I retry the deposit while waiting for support?", a: "No. A second identical deposit can trigger fraud flags and freeze both. Wait for support resolution first." },
        { q: "What if I sent to the wrong bKash number by mistake?", a: "That's not recoverable through JeetBuzz, the funds went outside their system. Contact bKash support to request a reversal, though wallet-to-wallet reversals are rarely granted." },
        { q: "Do I need to worry about tax on a failed and recovered deposit?", a: "No, a failed-then-recovered deposit is not a taxable event. The money simply took longer to credit than usual." },
        { q: "Can I dispute a failed deposit with my bank?", a: "Only as an absolute last resort. Chargebacks trigger account closure at JeetBuzz. Exhaust support channels first, they resolve almost all cases within a day." },
      ]}
      faqsByLocale={{
        bn: [
          { q: "bKash থেকে টাকা গেছে কিন্তু JeetBuzz-এ নেই, হারিয়ে গেছে?", a: "প্রায় কখনোই না। ওয়ালেটে successful outgoing দেখালে টাকা valid recipient-এ পৌঁছেছে। TxID দিয়ে সাপোর্ট trace ও credit করতে পারবে।" },
          { q: "Failed deposit recover-এ কত সময়?", a: "৪টি evidence থাকলে ২–৬ ঘণ্টা। জটিল case-এ ২৪–৪৮ ঘণ্টা।" },
          { q: "সাপোর্টের জন্য অপেক্ষা করার সময় আবার ডিপোজিট করব?", a: "না। দ্বিতীয় identical ডিপোজিট fraud flag ট্রিগার করে দুটোই freeze করতে পারে।" },
          { q: "ভুল bKash নম্বরে পাঠিয়েছি?", a: "JeetBuzz-এর মাধ্যমে recover হবে না। bKash *247-এ কল করে reversal চাইতে পারেন (কদাচিৎ granted হয়)।" },
          { q: "Failed ডিপোজিটে কি tax দিতে হবে?", a: "না, failed-then-recovered কোনো taxable event নয়।" },
          { q: "ব্যাংকে chargeback করব?", a: "শেষ অবলম্বন হিসেবে। Chargeback JeetBuzz অ্যাকাউন্ট বন্ধ করে দেয়। আগে সাপোর্ট exhaust করুন।" },
        ],
      }}
    />
  ),
});