import { createFileRoute } from "@tanstack/react-router";
import { GuidePage } from "@/components/GuidePage";
import { canonicalLink, hreflangLinks, ogUrl, jsonLdScript, articleSchema } from "@/lib/schema";

const PATH = "/withdrawal-guide";
const TITLE =
  "JeetBuzz Withdrawal Guide Bangladesh 2026 - bKash, Nagad, Rocket Cash Out";
const DESC =
  "JeetBuzz withdrawal guide for Bangladesh 2026, cash out to bKash, Nagad and Rocket, KYC checklist, daily limits, processing times and what to do if withdrawal is delayed.";

export const Route = createFileRoute("/withdrawal-guide")({
  head: () => ({
    meta: [
      { title: TITLE + " | GetJeetBuzz" },
      { name: "description", content: DESC },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESC },
      { property: "og:type", content: "article" },
      ogUrl(PATH),
    ],
    links: [canonicalLink(PATH), ...hreflangLinks(PATH)],
    scripts: [jsonLdScript(articleSchema({ headline: TITLE, description: DESC, path: PATH }))],
  }),
  component: () => (
    <GuidePage
      eyebrow="Payments"
      title={<>JeetBuzz <span className="gold-text">Withdrawal Guide</span></>}
      subtitle="Everything Bangladesh players need to know about cashing out from JeetBuzz. KYC, limits, processing times and troubleshooting."
      breadcrumbs={[{ name: "Payments", path: "/payment-methods" }, { name: "Withdrawal Guide", path: PATH }]}
      articlePath={PATH}
      articleHeadline={TITLE}
      articleDescription={DESC}
      body={[
        "> **Quick summary:** Finish KYC, clear any bonus wagering, then Cashier > Withdrawal > same wallet you deposited from. bKash/Nagad/Rocket and UPI clear in 5–30 minutes, USDT TRC20 in 10–20 minutes. Minimum 500 BDT / 1,000 PKR / ₹500 / ~$20. Wallet name must match your JeetBuzz profile or the withdrawal is reversed.",
        "## How JeetBuzz withdrawals work",
        "Withdrawals on JeetBuzz are usually processed within minutes to a few hours once KYC is complete. The fastest route for Bangladesh is bKash, Nagad or Rocket, the same wallet you used to deposit. India players cash out fastest via UPI; Pakistan via JazzCash or EasyPaisa.",
        "## KYC first",
        "Before your first cash-out, complete KYC: NID front and back, a selfie holding the NID, and proof of the registered phone number. Approval typically takes 1–24 hours.",
        "## How to withdraw, universal step-by-step",
        "1. Sign in via the [official login](/login-guide) and check that your account name matches the receiving wallet.",
        "2. Open **Cashier > Withdrawal**.",
        "3. Select the same payment method you used to deposit (bKash, Nagad, Rocket, JazzCash, EasyPaisa, UPI, USDT).",
        "4. Enter the amount (minimum 500 BDT / 1,000 PKR / ₹500 / $20 USDT).",
        "5. Confirm the receiving wallet number / VPA / USDT address. Triple-check the network for USDT (TRC20 vs BEP20).",
        "6. Submit. The cashier shows a pending ticket with an estimated time.",
        "7. Wait for the wallet SMS, it usually arrives within 5–30 minutes for BD wallets, 15–30 minutes for UPI, 10–30 minutes for USDT.",
        "8. If the SMS does not arrive within the window, open live chat with the ticket ID, never re-submit.",
        "## Limits and approval times",
        "Withdrawal limits and approval times may vary depending on your account status, VIP tier and the operator's current policies. Please check the cashier or contact customer support for the latest figures.",
        "## Country-specific notes",
        "- **Bangladesh:** Stick to the wallet you deposited from. bKash and Nagad clear fastest; Rocket is slightly slower but reliable in rural areas. Read the [bKash guide](/bkash-guide), [Nagad guide](/nagad-guide), [Rocket guide](/rocket-guide).",
        "- **Pakistan:** JazzCash withdrawals usually clear within 30 minutes. EasyPaisa is similar. Bank transfers take 1–3 hours and are best for larger sums above the wallet cap. See the [JazzCash guide](/jazzcash-guide) and [EasyPaisa guide](/easypaisa-guide).",
        "- **India:** UPI withdrawals to PhonePe / Google Pay / Paytm are usually credited in 15–30 minutes. For larger amounts above the daily UPI cap (₹1,00,000), use IMPS. See the [UPI guide](/upi-guide).",
        "- **Crypto (all countries):** USDT TRC20 typically arrives in 10–20 minutes. Always double-check the network, sending TRC20 funds to a BEP20 address loses them permanently.",
        "## Processing times",
        "- bKash / Nagad / Rocket: minutes to a few hours",
        "- UPI: same business day",
        "- USDT: depends on network congestion",
        "## Common reasons withdrawals get delayed",
        "| Method | Common Delay Cause |",
        "|---|---|",
        "| bKash | Name mismatch on wallet |",
        "| Nagad | KYC pending |",
        "| Rocket | Agent-side processing |",
        "| JazzCash | Wallet upper limit hit |",
        "| UPI | Bank-side rejection |",
        "| USDT TRC20 | Wrong network selected |",
        "## Withdrawal limits",
        "Daily and monthly limits apply, scaling with VIP level. Higher VIP tiers usually unlock larger single-cash-out caps and faster manual approvals.",
        "## Why withdrawals get delayed",
        "- KYC not yet approved",
        "- Bonus wagering not yet completed (withdrawing forfeits the bonus)",
        "- Wallet name does not match account name",
        "- Suspicious betting patterns triggering manual review",
        "- Requesting multiple small withdrawals instead of a single larger one",
        "- Withdrawing to a wallet different from the deposit wallet",
        "## Tips",
        "- Withdraw to the same wallet you deposited from",
        "- Don't request multiple small withdrawals, one larger withdrawal clears faster",
        "- If a withdrawal is stuck, open live chat with the transaction ID rather than re-submitting",
        "- Plan large cash-outs outside Friday late-night maintenance windows",
        "- Keep your KYC selfie and NID images saved, you may need to re-upload if support requests a refresh",
        "## Ready to cash out?",
        "Confirm KYC is approved, finish any active bonus wagering, then follow the 8-step flow above. If this is your first withdrawal, read the [Is JeetBuzz Safe](/is-jeetbuzz-safe) trust analysis for additional context.",
      ]}
      subtitleByLocale={{
        bn: "JeetBuzz বাংলাদেশের জন্য সম্পূর্ণ উইথড্রয়াল গাইড. KYC, লিমিট, প্রসেসিং সময় ও কেন কিছু উইথড্রয়াল আটকে যায় তার ব্যাখ্যা।",
        ur: "JeetBuzz سے کیش آؤٹ کے بارے میں پاکستانی کھلاڑیوں کے لیے مکمل گائیڈ۔",
        hi: "JeetBuzz से कैश-आउट के बारे में भारतीय खिलाड़ियों के लिए पूरा गाइड।",
      }}
      bodyByLocale={{
        bn: [
          "> **এক নজরে:** KYC শেষ করুন, যেকোনো অ্যাক্টিভ বোনাসের ওয়েজারিং পূরণ করুন, তারপর Cashier > Withdrawal থেকে যেই ওয়ালেট থেকে ডিপোজিট করেছেন সেটিতেই উইথড্র করুন। bKash/Nagad/Rocket সাধারণত ৫–৩০ মিনিটে ক্লিয়ার হয়, USDT TRC20 ১০–২০ মিনিটে। মিনিমাম ৫০০ টাকা। ওয়ালেট নাম JeetBuzz প্রোফাইলের সঙ্গে না মিললে উইথড্রয়াল রিভার্স হয়।",
          "## JeetBuzz উইথড্রয়াল যেভাবে কাজ করে",
          "KYC সম্পন্ন হলে JeetBuzz-এ বেশিরভাগ উইথড্রয়াল কয়েক মিনিট থেকে কয়েক ঘণ্টার মধ্যে প্রসেস হয়ে যায়। বাংলাদেশের জন্য দ্রুততম রুট হলো bKash, Nagad বা Rocket, যেই ওয়ালেট থেকে ডিপোজিট করেছেন।",
          "## প্রথমে KYC সম্পন্ন করুন",
          "প্রথম ক্যাশ-আউটের আগে KYC শেষ করতে হবে: NID-এর সামনে ও পিছনের ছবি, NID হাতে নিয়ে একটি সেলফি, এবং রেজিস্টার্ড ফোন নম্বরের প্রমাণ। অনুমোদন সাধারণত ১–২৪ ঘণ্টার মধ্যে হয়ে যায়।",
          "## কীভাবে উইথড্র করবেন, সর্বজনীন ধাপ",
          "১. [অফিশিয়াল লগইন](/login-guide) দিয়ে সাইন ইন করুন এবং প্রোফাইলের নাম রিসিভিং ওয়ালেটের সঙ্গে মিলিয়ে নিন।",
          "২. **Cashier > Withdrawal** খুলুন।",
          "৩. যেই মাধ্যমে ডিপোজিট করেছিলেন সেটিই বেছে নিন (bKash, Nagad, Rocket, USDT)।",
          "৪. পরিমাণ লিখুন (মিনিমাম ৫০০ টাকা / $২০ USDT)।",
          "৫. রিসিভিং ওয়ালেট নম্বর বা USDT অ্যাড্রেস কনফার্ম করুন। USDT-তে নেটওয়ার্ক (TRC20 না BEP20) তিনবার মিলিয়ে দেখুন।",
          "৬. সাবমিট করুন। ক্যাশিয়ারে পেন্ডিং টিকেট দেখাবে।",
          "৭. ওয়ালেট SMS-এর অপেক্ষা করুন. BD ওয়ালেটে ৫–৩০ মিনিট, USDT-এ ১০–৩০ মিনিট।",
          "৮. নির্ধারিত সময়ের মধ্যে SMS না এলে টিকেট আইডিসহ লাইভ চ্যাটে যোগাযোগ করুন, কখনই পুনরায় সাবমিট করবেন না।",
          "## লিমিট ও অনুমোদনের সময়",
          "উইথড্রয়াল লিমিট এবং অনুমোদনের সময় অ্যাকাউন্ট স্ট্যাটাস, VIP টিয়ার ও অপারেটরের বর্তমান নীতিমালার উপর নির্ভর করে। সর্বশেষ তথ্যের জন্য ক্যাশিয়ার দেখুন বা কাস্টমার সাপোর্টে যোগাযোগ করুন।",
          "## বাংলাদেশের জন্য নির্দিষ্ট টিপস",
          "- যেই ওয়ালেট থেকে ডিপোজিট করেছেন সেটিতেই উইথড্র করুন। bKash এবং Nagad সবচেয়ে দ্রুত; Rocket একটু ধীর কিন্তু গ্রামাঞ্চলে নির্ভরযোগ্য। বিস্তারিত: [bKash গাইড](/bkash-guide), [Nagad গাইড](/nagad-guide), [Rocket গাইড](/rocket-guide)।",
          "- USDT TRC20 সাধারণত ১০–২০ মিনিটে আসে। সব সময় নেটওয়ার্ক যাচাই করুন. TRC20 ফান্ড BEP20 অ্যাড্রেসে গেলে চিরতরে হারিয়ে যায়।",
          "## প্রসেসিং সময়",
          "- bKash / Nagad / Rocket: মিনিট থেকে কয়েক ঘণ্টা",
          "- USDT: নেটওয়ার্ক কনজেশনের উপর নির্ভর",
          "## সাধারণ বিলম্বের কারণ",
          "| মাধ্যম | সাধারণ কারণ |",
          "|---|---|",
          "| bKash | ওয়ালেট নাম মিসম্যাচ |",
          "| Nagad | KYC পেন্ডিং |",
          "| Rocket | এজেন্ট-সাইড প্রসেসিং |",
          "| USDT TRC20 | ভুল নেটওয়ার্ক |",
          "## কেন উইথড্রয়াল বিলম্বিত হয়",
          "- KYC এখনো অনুমোদিত নয়",
          "- বোনাসের ওয়েজারিং সম্পন্ন হয়নি (উইথড্র করলে বোনাস বাতিল)",
          "- ওয়ালেট নাম অ্যাকাউন্ট নামের সঙ্গে মেলে না",
          "- সন্দেহজনক বেটিং প্যাটার্নে ম্যানুয়াল রিভিউ",
          "- একসাথে অনেক ছোট উইথড্রয়াল",
          "- ডিপোজিটের ওয়ালেট থেকে ভিন্ন ওয়ালেটে উইথড্র চেষ্টা",
          "## টিপস",
          "- ডিপোজিটের ওয়ালেটেই উইথড্র করুন",
          "- একাধিক ছোট না করে একবারে বড় উইথড্রয়াল দ্রুত ক্লিয়ার হয়",
          "- আটকে গেলে পুনরায় সাবমিট না করে লাইভ চ্যাটে TrxID দিন",
          "- বড় ক্যাশ-আউট শুক্রবার গভীর রাতের মেইনটেন্যান্সের বাইরে রাখুন",
          "- KYC সেলফি ও NID-এর কপি সেভ করে রাখুন, সাপোর্ট রি-আপলোড চাইতে পারে",
          "## ক্যাশ আউটের জন্য প্রস্তুত?",
          "KYC অনুমোদন নিশ্চিত করুন, অ্যাক্টিভ বোনাসের ওয়েজারিং শেষ করুন, তারপর উপরের ৮ ধাপ অনুসরণ করুন। প্রথম উইথড্রয়াল হলে [Is JeetBuzz Safe](/is-jeetbuzz-safe) দেখে নিন।",
        ],
        ur: [
          "> **ایک نظر میں:** KYC مکمل کریں، کوئی فعال بونس ویجرنگ پوری کریں، پھر Cashier > Withdrawal سے اسی والیٹ پر کیش آؤٹ کریں جس سے ڈپازٹ کیا تھا۔ JazzCash اور EasyPaisa عموماً چند منٹ سے چند گھنٹوں میں کلیئر ہو جاتے ہیں، USDT TRC20 بھی اسی طرح۔ کم از کم 1,000 PKR / تقریباً $20 USDT۔ والیٹ کا نام آپ کے JeetBuzz پروفائل (CNIC نام) سے میچ ہونا چاہیے، ورنہ ودڈرا ریورس ہو جاتی ہے۔",
          "## JeetBuzz ودڈرا کیسے کام کرتی ہے",
          "KYC مکمل ہونے کے بعد JeetBuzz پر زیادہ تر ودڈرا عام طور پر چند منٹ سے چند گھنٹوں میں پراسس ہو جاتی ہیں۔ پاکستان کے لیے تیز ترین راستہ JazzCash یا EasyPaisa ہے, وہی والیٹ جو ڈپازٹ کے لیے استعمال ہوا تھا۔",
          "## پہلے KYC مکمل کریں",
          "پہلی کیش آؤٹ سے پہلے KYC ضروری ہے: CNIC کا فرنٹ اور بیک، CNIC ہاتھ میں پکڑ کر سیلفی، اور رجسٹرڈ فون نمبر کا ثبوت۔ منظوری عموماً 1–24 گھنٹے میں۔",
          "## ودڈرا کا عمومی طریقہ",
          "1. [آفیشل لاگ ان](/login-guide) سے سائن ان کریں اور تصدیق کریں کہ پروفائل کا نام رسیونگ والیٹ سے میچ کرتا ہے۔",
          "2. **Cashier > Withdrawal** کھولیں۔",
          "3. وہی طریقہ منتخب کریں جس سے ڈپازٹ کیا تھا (JazzCash، EasyPaisa، بینک، USDT)۔",
          "4. رقم درج کریں (کم از کم 1,000 PKR / $20 USDT)۔",
          "5. رسیونگ والیٹ نمبر یا USDT ایڈریس کی تصدیق کریں۔ USDT میں نیٹ ورک (TRC20 یا BEP20) تین بار چیک کریں۔",
          "6. Submit دبائیں۔ کیشیئر پر پینڈنگ ٹکٹ متوقع وقت کے ساتھ نظر آئے گا۔",
          "7. والیٹ SMS کا انتظار کریں, موبائل والیٹس میں عام طور پر چند منٹ سے چند گھنٹے، USDT میں 10–30 منٹ۔",
          "8. مقررہ وقت میں SMS نہ آئے تو ٹکٹ ID کے ساتھ لائیو چیٹ کھولیں, کبھی دوبارہ Submit مت کریں۔",
          "## حدود اور منظوری کا وقت",
          "ودڈرا کی حدود اور منظوری کا وقت آپ کے اکاؤنٹ کی حالت، VIP ٹیئر اور آپریٹر کی موجودہ پالیسی پر منحصر ہے۔ تازہ ترین معلومات کے لیے کیشیئر دیکھیں یا کسٹمر سپورٹ سے رابطہ کریں۔",
          "## پاکستان کے لیے خاص نوٹس",
          "- JazzCash اور EasyPaisa کی ودڈرا عام طور پر چند منٹ سے چند گھنٹوں میں کلیئر ہوتی ہیں۔ تفصیلات: [JazzCash گائیڈ](/jazzcash-guide)، [EasyPaisa گائیڈ](/easypaisa-guide)۔",
          "- بینک ٹرانسفر چند گھنٹے سے ایک کاروباری دن لیتا ہے اور والیٹ کیپ سے زیادہ بڑی رقم کے لیے بہترین ہے۔",
          "- USDT TRC20 عام طور پر 10–20 منٹ میں آتی ہے۔ نیٹ ورک ہمیشہ چیک کریں. TRC20 فنڈز BEP20 ایڈریس پر بھیجنے سے ہمیشہ کے لیے ضائع ہو جاتے ہیں۔",
          "## پروسیسنگ کا وقت",
          "- JazzCash / EasyPaisa: چند منٹ سے چند گھنٹے",
          "- بینک ٹرانسفر: چند گھنٹے سے ایک کاروباری دن",
          "- USDT: نیٹ ورک کی صورتحال پر منحصر",
          "## تاخیر کی عام وجوہات",
          "| طریقہ | عام وجہ |",
          "|---|---|",
          "| JazzCash | والیٹ کی اوپری حد پر پہنچ جانا |",
          "| EasyPaisa | CNIC نام مماثل نہ ہونا |",
          "| بینک | بینک کی جانب سے ریجیکشن |",
          "| USDT TRC20 | غلط نیٹ ورک منتخب |",
          "## ودڈرا کی حدود",
          "روزانہ اور ماہانہ حدود لاگو ہیں اور VIP لیول کے ساتھ بڑھتی ہیں۔ اعلیٰ VIP ٹیئر عام طور پر بڑی سنگل کیش آؤٹ کیپ اور تیز تر دستی منظوری کھولتے ہیں۔",
          "## تاخیر کیوں ہوتی ہے",
          "- KYC ابھی منظور نہیں",
          "- بونس ویجرنگ پوری نہیں (ودڈرا کرنے سے بونس ضبط ہو جاتا ہے)",
          "- والیٹ کا نام اکاؤنٹ کے نام سے میچ نہیں کرتا",
          "- مشکوک بیٹنگ پیٹرن پر دستی جائزہ",
          "- کئی چھوٹی ودڈرا کے بجائے ایک بڑی درخواست کریں",
          "- ڈپازٹ والے سے مختلف والیٹ پر ودڈرا کی کوشش",
          "## ٹپس",
          "- اسی والیٹ پر ودڈرا کریں جس سے ڈپازٹ کیا تھا",
          "- کئی چھوٹی کے بجائے ایک بڑی ودڈرا تیز کلیئر ہوتی ہے",
          "- اگر اٹک جائے تو دوبارہ Submit کرنے کے بجائے لائیو چیٹ پر ٹرانزیکشن ID دیں",
          "- بڑی کیش آؤٹ جمعہ کی رات کی مینٹیننس وِنڈو سے باہر پلان کریں",
          "- KYC سیلفی اور CNIC امیجز محفوظ رکھیں, سپورٹ ری اپ لوڈ کا کہہ سکتا ہے",
          "## کیش آؤٹ کے لیے تیار ہیں؟",
          "تصدیق کریں کہ KYC منظور ہے، فعال بونس کی ویجرنگ پوری کریں، پھر اوپر دیے گئے 8 مراحل پر عمل کریں۔ اگر یہ آپ کی پہلی ودڈرا ہے تو [Is JeetBuzz Safe](/is-jeetbuzz-safe) ٹرسٹ تجزیہ ضرور پڑھیں۔",
        ],
        hi: [
          "## संक्षेप में",
          "KYC पूरा हो तो विदड्रॉल कुछ घंटों में। भारत के लिए UPI सबसे तेज़।",
          "## पहले KYC",
          "आधार/PAN, सेल्फी, फोन प्रमाण। 1–24 घंटे।",
          "## UPI उदाहरण",
          "1. Cashier > Withdrawal।",
          "2. UPI चुनें, राशि डालें।",
          "3. अपनी UPI ID पुष्टि करें।",
          "4. सबमिट, SMS का इंतज़ार।",
          "## प्रोसेसिंग टाइम",
          "- UPI: मिनटों से कुछ घंटे",
          "- USDT: नेटवर्क पर निर्भर",
          "## लिमिट",
          "दैनिक/मासिक लिमिट VIP के अनुसार।",
          "## देरी के कारण",
          "- KYC अधूरा",
          "- बोनस वेजरिंग बाकी",
          "- वॉलेट नाम मेल नहीं",
          "- संदिग्ध पैटर्न",
          "## टिप्स",
          "- वही वॉलेट इस्तेमाल करें",
          "- एक बड़ा विदड्रॉल",
          "- अटक जाए तो लाइव चैट पर TrxID",
        ],
      }}
      faqsByLocale={{
        bn: [
          { q: "আমার উইথড্রয়াল পেন্ডিং কেন?", a: "সাধারণত KYC অসম্পূর্ণ, একটি অ্যাক্টিভ বোনাস চলমান, অথবা রিসিভিং ওয়ালেটের নাম মিলছে না। ট্রানজ্যাকশন আইডিসহ লাইভ চ্যাটে যোগাযোগ করুন।" },
          { q: "JeetBuzz কি উইথড্রয়াল ফি নেয়?", a: "না, স্ট্যান্ডার্ড লিমিটের মধ্যে JeetBuzz কোনো উইথড্রয়াল ফি নেয় না। তবে ওয়ালেট প্রোভাইডার তাদের নিয়মিত ক্যাশ-আউট ফি কাটতে পারে।" },
          { q: "প্রথম উইথড্রয়ালে কতক্ষণ লাগে?", a: "সাধারণত KYC অনুমোদনের পর কয়েক ঘণ্টা। পরবর্তী উইথড্রয়াল দ্রুততর হয়।" },
          { q: "ডিপোজিটের চেয়ে ভিন্ন ওয়ালেটে উইথড্র করা যাবে?", a: "সাধারণত না. JeetBuzz দাবি করে উইথড্রয়াল ওয়ালেট ডিপোজিট ওয়ালেট ও অ্যাকাউন্ট নামের সঙ্গে মিলবে।" },
          { q: "মিনিমাম উইথড্রয়াল কত?", a: "বাংলাদেশে ৫০০ টাকা, USDT-তে আনুমানিক $২০। টিয়ার ও মাধ্যম অনুযায়ী পরিবর্তন হতে পারে।" },
          { q: "পেন্ডিং উইথড্রয়াল ক্যানসেল করা যায়?", a: "হ্যাঁ, শুধু Pending থাকা অবস্থায়। Processing-এ চলে গেলে আর বাতিল করা যায় না।" },
          { q: "উইথড্র করলে কি বোনাস বাতিল হবে?", a: "বোনাসের ওয়েজারিং পূরণের আগে উইথড্র করলে বোনাস এবং বোনাস ব্যালেন্স সংক্রান্ত জিতে যাওয়া সব ফরফিট হবে।" },
          { q: "USDT উইথড্রয়ালে কেন দেরি হচ্ছে?", a: "Tron/BSC নেটওয়ার্ক কনজেশনের কারণে। সাপোর্টে যোগাযোগের আগে Tronscan/BscScan-এ হ্যাশ যাচাই করুন।" },
        ],
        ur: [
          { q: "میری ودڈرا پینڈنگ کیوں ہے؟", a: "عام طور پر KYC نامکمل ہے، کوئی فعال بونس چل رہا ہے، یا رسیونگ والیٹ کا نام میچ نہیں کرتا۔ ٹرانزیکشن ID کے ساتھ لائیو چیٹ پر رابطہ کریں۔" },
          { q: "کیا JeetBuzz ودڈرا فیس لیتا ہے؟", a: "اگر کوئی فیس قابل اطلاق ہو تو کیشیئر میں ودڈرا کنفرم کرنے سے پہلے دکھا دی جاتی ہے۔ آپ کا والیٹ پروائڈر اپنی معمولی کیش آؤٹ فیس بھی لگا سکتا ہے۔" },
          { q: "پہلی ودڈرا میں کتنا وقت لگتا ہے؟", a: "KYC منظوری کے بعد عام طور پر چند گھنٹے۔ بعد کی ودڈرا تیز تر ہوتی ہیں۔" },
          { q: "کیا میں ڈپازٹ سے مختلف والیٹ پر ودڈرا کر سکتا ہوں؟", a: "عام طور پر نہیں. JeetBuzz چاہتا ہے کہ ودڈرا والیٹ ڈپازٹ والیٹ اور اکاؤنٹ نام سے میچ کرے۔" },
          { q: "کم از کم ودڈرا کتنی ہے؟", a: "پاکستان میں 1,000 PKR، USDT میں تقریباً $20۔ ٹیئر اور طریقہ کے مطابق فلور تبدیل ہو سکتا ہے۔" },
          { q: "کیا پینڈنگ ودڈرا منسوخ ہو سکتی ہے؟", a: "ہاں، صرف اس وقت تک جب اسٹیٹس Pending ہے۔ Processing میں جانے کے بعد درخواست پیمنٹ پروائڈر کو بھیجی جا چکی ہوتی ہے اور واپس نہیں ہو سکتی۔" },
          { q: "کیا ودڈرا کرنے سے میرا بونس ضائع ہو جائے گا؟", a: "اگر آپ ویجرنگ پوری کیے بغیر ودڈرا کرتے ہیں تو بونس اور بونس بیلنس سے جیتی گئی رقم ضبط ہو جاتی ہے۔" },
          { q: "USDT ودڈرا میں دیر کیوں ہو رہی ہے؟", a: "Tron/BSC نیٹ ورک کی بھیڑ سے اثر پڑتا ہے۔ سپورٹ سے رابطے سے پہلے بلاک ایکسپلورر (Tronscan/BscScan) پر ہیش تصدیق کریں۔" },
        ],
        hi: [
          { q: "विदड्रॉल पेंडिंग क्यों?", a: "KYC अधूरा, सक्रिय बोनस, या वॉलेट नाम मेल नहीं।" },
          { q: "विदड्रॉल फीस?", a: "मानक सीमा में JeetBuzz फीस नहीं लेता।" },
          { q: "पहले विदड्रॉल में समय?", a: "KYC अप्रूवल के बाद कुछ घंटे।" },
          { q: "अलग वॉलेट?", a: "आमतौर पर नहीं।" },
        ],
      }}
      faqs={[
        { q: "Why is my withdrawal pending?", a: "Usually KYC is incomplete, you have an active bonus, or the receiving wallet name doesn't match. Open live chat with your transaction ID." },
        { q: "Is there a withdrawal fee?", a: "Applicable fees, if any, are displayed in the cashier before you confirm the withdrawal. Your wallet provider may also apply its standard cash-out fees." },
        { q: "How long does the first withdrawal take?", a: "Typically a few hours after KYC approval. Subsequent withdrawals are faster." },
        { q: "Can I withdraw to a different wallet than my deposit?", a: "Generally no. JeetBuzz requires the withdrawal wallet to match the deposit wallet and account name." },
        { q: "What is the minimum withdrawal?", a: "500 BDT in Bangladesh, 1,000 PKR in Pakistan, ₹500 in India, and roughly $20 in USDT. Tier and method may adjust the floor." },
        { q: "Can I cancel a pending withdrawal?", a: "Yes, only while the status is Pending. Once it moves to Processing, the request is sent to the payment provider and cannot be reversed." },
        { q: "Will withdrawing cancel my bonus?", a: "If you withdraw before completing the wagering requirement, the bonus and any winnings tied to the bonus balance are forfeited." },
        { q: "Why is the USDT withdrawal taking long?", a: "Network congestion on Tron/BSC affects timing. Confirm the hash on a block explorer (Tronscan / BscScan) before contacting support." },
      ]}
      related={[
        { to: "/deposit-guide", title: "JeetBuzz Deposit Guide" },
        { to: "/payment-methods", title: "All Payment Methods" },
        { to: "/security-guide", title: "JeetBuzz Security Guide" },
        { to: "/vip-program", title: "JeetBuzz VIP Program" },
      ]}
    />
  ),
});