/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char2460Char2495Char2468Char2476Char2494Char2460RouteImport } from './routes/জিতবাজ'
import { Route as WithdrawalGuideRouteImport } from './routes/withdrawal-guide'
import { Route as WelcomeBonusRouteImport } from './routes/welcome-bonus'
import { Route as VipProgramRouteImport } from './routes/vip-program'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as UpiGuideRouteImport } from './routes/upi-guide'
import { Route as UpdatePolicyRouteImport } from './routes/update-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SportsBettingRouteImport } from './routes/sports-betting'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapSolutionsDotxmlRouteImport } from './routes/sitemap-solutions[.]xml'
import { Route as SitemapPkDotxmlRouteImport } from './routes/sitemap-pk[.]xml'
import { Route as SitemapPaymentsDotxmlRouteImport } from './routes/sitemap-payments[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapInDotxmlRouteImport } from './routes/sitemap-in[.]xml'
import { Route as SitemapGuidesDotxmlRouteImport } from './routes/sitemap-guides[.]xml'
import { Route as SitemapBlogDotxmlRouteImport } from './routes/sitemap-blog[.]xml'
import { Route as SitemapBdDotxmlRouteImport } from './routes/sitemap-bd[.]xml'
import { Route as SitemapAffiliateDotxmlRouteImport } from './routes/sitemap-affiliate[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityGuideRouteImport } from './routes/security-guide'
import { Route as RocketGuideRouteImport } from './routes/rocket-guide'
import { Route as ReviewPolicyRouteImport } from './routes/review-policy'
import { Route as ResponsibleGamingRouteImport } from './routes/responsible-gaming'
import { Route as RegistrationGuideRouteImport } from './routes/registration-guide'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PhonepeGuideRouteImport } from './routes/phonepe-guide'
import { Route as PaytmGuideRouteImport } from './routes/paytm-guide'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as NagadGuideRouteImport } from './routes/nagad-guide'
import { Route as MobileAppGuideRouteImport } from './routes/mobile-app-guide'
import { Route as LoginSecurityRouteImport } from './routes/login-security'
import { Route as LoginProblemsRouteImport } from './routes/login-problems'
import { Route as LoginGuideRouteImport } from './routes/login-guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveCricketBettingRouteImport } from './routes/live-cricket-betting'
import { Route as JitbuzzRouteImport } from './routes/jitbuzz'
import { Route as JetbuzzRouteImport } from './routes/jetbuzz'
import { Route as JestBuzzRouteImport } from './routes/jest-buzz'
import { Route as JeetbuzzWithdrawalTimeRouteImport } from './routes/jeetbuzz-withdrawal-time'
import { Route as JeetbuzzWithdrawalPendingRouteImport } from './routes/jeetbuzz-withdrawal-pending'
import { Route as JeetbuzzSignUpRouteImport } from './routes/jeetbuzz-sign-up'
import { Route as JeetbuzzReviewRouteImport } from './routes/jeetbuzz-review'
import { Route as JeetbuzzReferralCodeRouteImport } from './routes/jeetbuzz-referral-code'
import { Route as JeetbuzzReferBonusRouteImport } from './routes/jeetbuzz-refer-bonus'
import { Route as JeetbuzzPromoCodeRouteImport } from './routes/jeetbuzz-promo-code'
import { Route as JeetbuzzPasswordResetRouteImport } from './routes/jeetbuzz-password-reset'
import { Route as JeetbuzzPartnerLoginRouteImport } from './routes/jeetbuzz-partner-login'
import { Route as JeetbuzzOtpNotReceivedRouteImport } from './routes/jeetbuzz-otp-not-received'
import { Route as JeetbuzzNagadWithdrawalRouteImport } from './routes/jeetbuzz-nagad-withdrawal'
import { Route as JeetbuzzMinimumDepositRouteImport } from './routes/jeetbuzz-minimum-deposit'
import { Route as JeetbuzzLiveCricketRouteImport } from './routes/jeetbuzz-live-cricket'
import { Route as JeetbuzzFirstDepositBonusRouteImport } from './routes/jeetbuzz-first-deposit-bonus'
import { Route as JeetbuzzDownloadForIosRouteImport } from './routes/jeetbuzz-download-for-ios'
import { Route as JeetbuzzDownloadForAndroidRouteImport } from './routes/jeetbuzz-download-for-android'
import { Route as JeetbuzzDepositProblemRouteImport } from './routes/jeetbuzz-deposit-problem'
import { Route as JeetbuzzDepositFailedRouteImport } from './routes/jeetbuzz-deposit-failed'
import { Route as JeetbuzzComLoginRouteImport } from './routes/jeetbuzz-com-login'
import { Route as JeetbuzzBkashDepositRouteImport } from './routes/jeetbuzz-bkash-deposit'
import { Route as JeetbuzzAppUpdateRouteImport } from './routes/jeetbuzz-app-update'
import { Route as JeetbuzzAppNotOpeningRouteImport } from './routes/jeetbuzz-app-not-opening'
import { Route as JeetbuzzApkDownloadRouteImport } from './routes/jeetbuzz-apk-download'
import { Route as JeetbuzzAlternativesRouteImport } from './routes/jeetbuzz-alternatives'
import { Route as JeetbuzzAffiliateWithdrawalRouteImport } from './routes/jeetbuzz-affiliate-withdrawal'
import { Route as JeetbuzzAffiliateSignupRouteImport } from './routes/jeetbuzz-affiliate-signup'
import { Route as JeetbuzzAffiliatePaymentMethodsRouteImport } from './routes/jeetbuzz-affiliate-payment-methods'
import { Route as JeetbuzzAffiliateDashboardRouteImport } from './routes/jeetbuzz-affiliate-dashboard'
import { Route as JeetbuzzAffiliateCommissionRateRouteImport } from './routes/jeetbuzz-affiliate-commission-rate'
import { Route as JeetbuzzAffiliateCommissionRouteImport } from './routes/jeetbuzz-affiliate-commission'
import { Route as JeetbuzzAffiliateAppRouteImport } from './routes/jeetbuzz-affiliate-app'
import { Route as JeetbuzzAccountVerificationRouteImport } from './routes/jeetbuzz-account-verification'
import { Route as JeetbuzzAccountLockedRouteImport } from './routes/jeetbuzz-account-locked'
import { Route as JeetbuzRouteImport } from './routes/jeetbuz'
import { Route as JeetBuzzRouteImport } from './routes/jeet-buzz'
import { Route as JazzcashGuideRouteImport } from './routes/jazzcash-guide'
import { Route as IsJeetbuzzSafeRouteImport } from './routes/is-jeetbuzz-safe'
import { Route as IosAppGuideRouteImport } from './routes/ios-app-guide'
import { Route as HowToDeleteJeetbuzzAccountRouteImport } from './routes/how-to-delete-jeetbuzz-account'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FactCheckingRouteImport } from './routes/fact-checking'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as EasypaisaGuideRouteImport } from './routes/easypaisa-guide'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DepositWithdrawalGuideRouteImport } from './routes/deposit-withdrawal-guide'
import { Route as DepositGuideRouteImport } from './routes/deposit-guide'
import { Route as CricketExchangeGuideRouteImport } from './routes/cricket-exchange-guide'
import { Route as ContentPolicyRouteImport } from './routes/content-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CasinoGuideRouteImport } from './routes/casino-guide'
import { Route as BonusesRouteImport } from './routes/bonuses'
import { Route as BonusAndPromotionsRouteImport } from './routes/bonus-and-promotions'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BkashGuideRouteImport } from './routes/bkash-guide'
import { Route as AviatorGuideRouteImport } from './routes/aviator-guide'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as ApkDownloadGuideRouteImport } from './routes/apk-download-guide'
import { Route as AndroidWebAppGuideRouteImport } from './routes/android-web-app-guide'
import { Route as AgentEarningGuideRouteImport } from './routes/agent-earning-guide'
import { Route as AffiliateProgramRouteImport } from './routes/affiliate-program'
import { Route as AffiliateLoginRouteImport } from './routes/affiliate-login'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as GoSignupRouteImport } from './routes/go.signup'
import { Route as GoLoginRouteImport } from './routes/go.login'
import { Route as GoAffiliateRouteImport } from './routes/go.affiliate'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppLaunchRouteImport } from './routes/app.launch'
import { Route as CountryLangIndexRouteImport } from './routes/$country.$lang.index'
import { Route as CountryLangSplatRouteImport } from './routes/$country.$lang.$'

const Char2460Char2495Char2468Char2476Char2494Char2460Route =
  Char2460Char2495Char2468Char2476Char2494Char2460RouteImport.update({
    id: '/জিতবাজ',
    path: '/জিতবাজ',
    getParentRoute: () => rootRouteImport,
  } as any)
const WithdrawalGuideRoute = WithdrawalGuideRouteImport.update({
  id: '/withdrawal-guide',
  path: '/withdrawal-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeBonusRoute = WelcomeBonusRouteImport.update({
  id: '/welcome-bonus',
  path: '/welcome-bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const VipProgramRoute = VipProgramRouteImport.update({
  id: '/vip-program',
  path: '/vip-program',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const UpiGuideRoute = UpiGuideRouteImport.update({
  id: '/upi-guide',
  path: '/upi-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePolicyRoute = UpdatePolicyRouteImport.update({
  id: '/update-policy',
  path: '/update-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsBettingRoute = SportsBettingRouteImport.update({
  id: '/sports-betting',
  path: '/sports-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapSolutionsDotxmlRoute = SitemapSolutionsDotxmlRouteImport.update({
  id: '/sitemap-solutions.xml',
  path: '/sitemap-solutions.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPkDotxmlRoute = SitemapPkDotxmlRouteImport.update({
  id: '/sitemap-pk.xml',
  path: '/sitemap-pk.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPaymentsDotxmlRoute = SitemapPaymentsDotxmlRouteImport.update({
  id: '/sitemap-payments.xml',
  path: '/sitemap-payments.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapInDotxmlRoute = SitemapInDotxmlRouteImport.update({
  id: '/sitemap-in.xml',
  path: '/sitemap-in.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapGuidesDotxmlRoute = SitemapGuidesDotxmlRouteImport.update({
  id: '/sitemap-guides.xml',
  path: '/sitemap-guides.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapBlogDotxmlRoute = SitemapBlogDotxmlRouteImport.update({
  id: '/sitemap-blog.xml',
  path: '/sitemap-blog.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapBdDotxmlRoute = SitemapBdDotxmlRouteImport.update({
  id: '/sitemap-bd.xml',
  path: '/sitemap-bd.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapAffiliateDotxmlRoute = SitemapAffiliateDotxmlRouteImport.update({
  id: '/sitemap-affiliate.xml',
  path: '/sitemap-affiliate.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityGuideRoute = SecurityGuideRouteImport.update({
  id: '/security-guide',
  path: '/security-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const RocketGuideRoute = RocketGuideRouteImport.update({
  id: '/rocket-guide',
  path: '/rocket-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewPolicyRoute = ReviewPolicyRouteImport.update({
  id: '/review-policy',
  path: '/review-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamingRoute = ResponsibleGamingRouteImport.update({
  id: '/responsible-gaming',
  path: '/responsible-gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationGuideRoute = RegistrationGuideRouteImport.update({
  id: '/registration-guide',
  path: '/registration-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PhonepeGuideRoute = PhonepeGuideRouteImport.update({
  id: '/phonepe-guide',
  path: '/phonepe-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PaytmGuideRoute = PaytmGuideRouteImport.update({
  id: '/paytm-guide',
  path: '/paytm-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const NagadGuideRoute = NagadGuideRouteImport.update({
  id: '/nagad-guide',
  path: '/nagad-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppGuideRoute = MobileAppGuideRouteImport.update({
  id: '/mobile-app-guide',
  path: '/mobile-app-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSecurityRoute = LoginSecurityRouteImport.update({
  id: '/login-security',
  path: '/login-security',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginProblemsRoute = LoginProblemsRouteImport.update({
  id: '/login-problems',
  path: '/login-problems',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginGuideRoute = LoginGuideRouteImport.update({
  id: '/login-guide',
  path: '/login-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveCricketBettingRoute = LiveCricketBettingRouteImport.update({
  id: '/live-cricket-betting',
  path: '/live-cricket-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const JitbuzzRoute = JitbuzzRouteImport.update({
  id: '/jitbuzz',
  path: '/jitbuzz',
  getParentRoute: () => rootRouteImport,
} as any)
const JetbuzzRoute = JetbuzzRouteImport.update({
  id: '/jetbuzz',
  path: '/jetbuzz',
  getParentRoute: () => rootRouteImport,
} as any)
const JestBuzzRoute = JestBuzzRouteImport.update({
  id: '/jest-buzz',
  path: '/jest-buzz',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzWithdrawalTimeRoute = JeetbuzzWithdrawalTimeRouteImport.update({
  id: '/jeetbuzz-withdrawal-time',
  path: '/jeetbuzz-withdrawal-time',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzWithdrawalPendingRoute =
  JeetbuzzWithdrawalPendingRouteImport.update({
    id: '/jeetbuzz-withdrawal-pending',
    path: '/jeetbuzz-withdrawal-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const JeetbuzzSignUpRoute = JeetbuzzSignUpRouteImport.update({
  id: '/jeetbuzz-sign-up',
  path: '/jeetbuzz-sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzReviewRoute = JeetbuzzReviewRouteImport.update({
  id: '/jeetbuzz-review',
  path: '/jeetbuzz-review',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzReferralCodeRoute = JeetbuzzReferralCodeRouteImport.update({
  id: '/jeetbuzz-referral-code',
  path: '/jeetbuzz-referral-code',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzReferBonusRoute = JeetbuzzReferBonusRouteImport.update({
  id: '/jeetbuzz-refer-bonus',
  path: '/jeetbuzz-refer-bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzPromoCodeRoute = JeetbuzzPromoCodeRouteImport.update({
  id: '/jeetbuzz-promo-code',
  path: '/jeetbuzz-promo-code',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzPasswordResetRoute = JeetbuzzPasswordResetRouteImport.update({
  id: '/jeetbuzz-password-reset',
  path: '/jeetbuzz-password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzPartnerLoginRoute = JeetbuzzPartnerLoginRouteImport.update({
  id: '/jeetbuzz-partner-login',
  path: '/jeetbuzz-partner-login',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzOtpNotReceivedRoute = JeetbuzzOtpNotReceivedRouteImport.update({
  id: '/jeetbuzz-otp-not-received',
  path: '/jeetbuzz-otp-not-received',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzNagadWithdrawalRoute = JeetbuzzNagadWithdrawalRouteImport.update({
  id: '/jeetbuzz-nagad-withdrawal',
  path: '/jeetbuzz-nagad-withdrawal',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzMinimumDepositRoute = JeetbuzzMinimumDepositRouteImport.update({
  id: '/jeetbuzz-minimum-deposit',
  path: '/jeetbuzz-minimum-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzLiveCricketRoute = JeetbuzzLiveCricketRouteImport.update({
  id: '/jeetbuzz-live-cricket',
  path: '/jeetbuzz-live-cricket',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzFirstDepositBonusRoute =
  JeetbuzzFirstDepositBonusRouteImport.update({
    id: '/jeetbuzz-first-deposit-bonus',
    path: '/jeetbuzz-first-deposit-bonus',
    getParentRoute: () => rootRouteImport,
  } as any)
const JeetbuzzDownloadForIosRoute = JeetbuzzDownloadForIosRouteImport.update({
  id: '/jeetbuzz-download-for-ios',
  path: '/jeetbuzz-download-for-ios',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzDownloadForAndroidRoute =
  JeetbuzzDownloadForAndroidRouteImport.update({
    id: '/jeetbuzz-download-for-android',
    path: '/jeetbuzz-download-for-android',
    getParentRoute: () => rootRouteImport,
  } as any)
const JeetbuzzDepositProblemRoute = JeetbuzzDepositProblemRouteImport.update({
  id: '/jeetbuzz-deposit-problem',
  path: '/jeetbuzz-deposit-problem',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzDepositFailedRoute = JeetbuzzDepositFailedRouteImport.update({
  id: '/jeetbuzz-deposit-failed',
  path: '/jeetbuzz-deposit-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzComLoginRoute = JeetbuzzComLoginRouteImport.update({
  id: '/jeetbuzz-com-login',
  path: '/jeetbuzz-com-login',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzBkashDepositRoute = JeetbuzzBkashDepositRouteImport.update({
  id: '/jeetbuzz-bkash-deposit',
  path: '/jeetbuzz-bkash-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzAppUpdateRoute = JeetbuzzAppUpdateRouteImport.update({
  id: '/jeetbuzz-app-update',
  path: '/jeetbuzz-app-update',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzAppNotOpeningRoute = JeetbuzzAppNotOpeningRouteImport.update({
  id: '/jeetbuzz-app-not-opening',
  path: '/jeetbuzz-app-not-opening',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzApkDownloadRoute = JeetbuzzApkDownloadRouteImport.update({
  id: '/jeetbuzz-apk-download',
  path: '/jeetbuzz-apk-download',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzAlternativesRoute = JeetbuzzAlternativesRouteImport.update({
  id: '/jeetbuzz-alternatives',
  path: '/jeetbuzz-alternatives',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzAffiliateWithdrawalRoute =
  JeetbuzzAffiliateWithdrawalRouteImport.update({
    id: '/jeetbuzz-affiliate-withdrawal',
    path: '/jeetbuzz-affiliate-withdrawal',
    getParentRoute: () => rootRouteImport,
  } as any)
const JeetbuzzAffiliateSignupRoute = JeetbuzzAffiliateSignupRouteImport.update({
  id: '/jeetbuzz-affiliate-signup',
  path: '/jeetbuzz-affiliate-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzAffiliatePaymentMethodsRoute =
  JeetbuzzAffiliatePaymentMethodsRouteImport.update({
    id: '/jeetbuzz-affiliate-payment-methods',
    path: '/jeetbuzz-affiliate-payment-methods',
    getParentRoute: () => rootRouteImport,
  } as any)
const JeetbuzzAffiliateDashboardRoute =
  JeetbuzzAffiliateDashboardRouteImport.update({
    id: '/jeetbuzz-affiliate-dashboard',
    path: '/jeetbuzz-affiliate-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const JeetbuzzAffiliateCommissionRateRoute =
  JeetbuzzAffiliateCommissionRateRouteImport.update({
    id: '/jeetbuzz-affiliate-commission-rate',
    path: '/jeetbuzz-affiliate-commission-rate',
    getParentRoute: () => rootRouteImport,
  } as any)
const JeetbuzzAffiliateCommissionRoute =
  JeetbuzzAffiliateCommissionRouteImport.update({
    id: '/jeetbuzz-affiliate-commission',
    path: '/jeetbuzz-affiliate-commission',
    getParentRoute: () => rootRouteImport,
  } as any)
const JeetbuzzAffiliateAppRoute = JeetbuzzAffiliateAppRouteImport.update({
  id: '/jeetbuzz-affiliate-app',
  path: '/jeetbuzz-affiliate-app',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzAccountVerificationRoute =
  JeetbuzzAccountVerificationRouteImport.update({
    id: '/jeetbuzz-account-verification',
    path: '/jeetbuzz-account-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const JeetbuzzAccountLockedRoute = JeetbuzzAccountLockedRouteImport.update({
  id: '/jeetbuzz-account-locked',
  path: '/jeetbuzz-account-locked',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzRoute = JeetbuzRouteImport.update({
  id: '/jeetbuz',
  path: '/jeetbuz',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetBuzzRoute = JeetBuzzRouteImport.update({
  id: '/jeet-buzz',
  path: '/jeet-buzz',
  getParentRoute: () => rootRouteImport,
} as any)
const JazzcashGuideRoute = JazzcashGuideRouteImport.update({
  id: '/jazzcash-guide',
  path: '/jazzcash-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IsJeetbuzzSafeRoute = IsJeetbuzzSafeRouteImport.update({
  id: '/is-jeetbuzz-safe',
  path: '/is-jeetbuzz-safe',
  getParentRoute: () => rootRouteImport,
} as any)
const IosAppGuideRoute = IosAppGuideRouteImport.update({
  id: '/ios-app-guide',
  path: '/ios-app-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToDeleteJeetbuzzAccountRoute =
  HowToDeleteJeetbuzzAccountRouteImport.update({
    id: '/how-to-delete-jeetbuzz-account',
    path: '/how-to-delete-jeetbuzz-account',
    getParentRoute: () => rootRouteImport,
  } as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FactCheckingRoute = FactCheckingRouteImport.update({
  id: '/fact-checking',
  path: '/fact-checking',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EasypaisaGuideRoute = EasypaisaGuideRouteImport.update({
  id: '/easypaisa-guide',
  path: '/easypaisa-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositWithdrawalGuideRoute = DepositWithdrawalGuideRouteImport.update({
  id: '/deposit-withdrawal-guide',
  path: '/deposit-withdrawal-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositGuideRoute = DepositGuideRouteImport.update({
  id: '/deposit-guide',
  path: '/deposit-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketExchangeGuideRoute = CricketExchangeGuideRouteImport.update({
  id: '/cricket-exchange-guide',
  path: '/cricket-exchange-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentPolicyRoute = ContentPolicyRouteImport.update({
  id: '/content-policy',
  path: '/content-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoGuideRoute = CasinoGuideRouteImport.update({
  id: '/casino-guide',
  path: '/casino-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusesRoute = BonusesRouteImport.update({
  id: '/bonuses',
  path: '/bonuses',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusAndPromotionsRoute = BonusAndPromotionsRouteImport.update({
  id: '/bonus-and-promotions',
  path: '/bonus-and-promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BkashGuideRoute = BkashGuideRouteImport.update({
  id: '/bkash-guide',
  path: '/bkash-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AviatorGuideRoute = AviatorGuideRouteImport.update({
  id: '/aviator-guide',
  path: '/aviator-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const ApkDownloadGuideRoute = ApkDownloadGuideRouteImport.update({
  id: '/apk-download-guide',
  path: '/apk-download-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidWebAppGuideRoute = AndroidWebAppGuideRouteImport.update({
  id: '/android-web-app-guide',
  path: '/android-web-app-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentEarningGuideRoute = AgentEarningGuideRouteImport.update({
  id: '/agent-earning-guide',
  path: '/agent-earning-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateProgramRoute = AffiliateProgramRouteImport.update({
  id: '/affiliate-program',
  path: '/affiliate-program',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateLoginRoute = AffiliateLoginRouteImport.update({
  id: '/affiliate-login',
  path: '/affiliate-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const GoSignupRoute = GoSignupRouteImport.update({
  id: '/go/signup',
  path: '/go/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLoginRoute = GoLoginRouteImport.update({
  id: '/go/login',
  path: '/go/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GoAffiliateRoute = GoAffiliateRouteImport.update({
  id: '/go/affiliate',
  path: '/go/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AppLaunchRoute = AppLaunchRouteImport.update({
  id: '/app/launch',
  path: '/app/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryLangIndexRoute = CountryLangIndexRouteImport.update({
  id: '/$country/$lang/',
  path: '/$country/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryLangSplatRoute = CountryLangSplatRouteImport.update({
  id: '/$country/$lang/$',
  path: '/$country/$lang/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/affiliate-login': typeof AffiliateLoginRoute
  '/affiliate-program': typeof AffiliateProgramRoute
  '/agent-earning-guide': typeof AgentEarningGuideRoute
  '/android-web-app-guide': typeof AndroidWebAppGuideRoute
  '/apk-download-guide': typeof ApkDownloadGuideRoute
  '/author': typeof AuthorRoute
  '/aviator-guide': typeof AviatorGuideRoute
  '/bkash-guide': typeof BkashGuideRoute
  '/blog': typeof BlogRouteWithChildren
  '/bonus-and-promotions': typeof BonusAndPromotionsRoute
  '/bonuses': typeof BonusesRoute
  '/casino-guide': typeof CasinoGuideRoute
  '/contact': typeof ContactRoute
  '/content-policy': typeof ContentPolicyRoute
  '/cricket-exchange-guide': typeof CricketExchangeGuideRoute
  '/deposit-guide': typeof DepositGuideRoute
  '/deposit-withdrawal-guide': typeof DepositWithdrawalGuideRoute
  '/download': typeof DownloadRoute
  '/easypaisa-guide': typeof EasypaisaGuideRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking': typeof FactCheckingRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/help': typeof HelpRoute
  '/how-to-delete-jeetbuzz-account': typeof HowToDeleteJeetbuzzAccountRoute
  '/ios-app-guide': typeof IosAppGuideRoute
  '/is-jeetbuzz-safe': typeof IsJeetbuzzSafeRoute
  '/jazzcash-guide': typeof JazzcashGuideRoute
  '/jeet-buzz': typeof JeetBuzzRoute
  '/jeetbuz': typeof JeetbuzRoute
  '/jeetbuzz-account-locked': typeof JeetbuzzAccountLockedRoute
  '/jeetbuzz-account-verification': typeof JeetbuzzAccountVerificationRoute
  '/jeetbuzz-affiliate-app': typeof JeetbuzzAffiliateAppRoute
  '/jeetbuzz-affiliate-commission': typeof JeetbuzzAffiliateCommissionRoute
  '/jeetbuzz-affiliate-commission-rate': typeof JeetbuzzAffiliateCommissionRateRoute
  '/jeetbuzz-affiliate-dashboard': typeof JeetbuzzAffiliateDashboardRoute
  '/jeetbuzz-affiliate-payment-methods': typeof JeetbuzzAffiliatePaymentMethodsRoute
  '/jeetbuzz-affiliate-signup': typeof JeetbuzzAffiliateSignupRoute
  '/jeetbuzz-affiliate-withdrawal': typeof JeetbuzzAffiliateWithdrawalRoute
  '/jeetbuzz-alternatives': typeof JeetbuzzAlternativesRoute
  '/jeetbuzz-apk-download': typeof JeetbuzzApkDownloadRoute
  '/jeetbuzz-app-not-opening': typeof JeetbuzzAppNotOpeningRoute
  '/jeetbuzz-app-update': typeof JeetbuzzAppUpdateRoute
  '/jeetbuzz-bkash-deposit': typeof JeetbuzzBkashDepositRoute
  '/jeetbuzz-com-login': typeof JeetbuzzComLoginRoute
  '/jeetbuzz-deposit-failed': typeof JeetbuzzDepositFailedRoute
  '/jeetbuzz-deposit-problem': typeof JeetbuzzDepositProblemRoute
  '/jeetbuzz-download-for-android': typeof JeetbuzzDownloadForAndroidRoute
  '/jeetbuzz-download-for-ios': typeof JeetbuzzDownloadForIosRoute
  '/jeetbuzz-first-deposit-bonus': typeof JeetbuzzFirstDepositBonusRoute
  '/jeetbuzz-live-cricket': typeof JeetbuzzLiveCricketRoute
  '/jeetbuzz-minimum-deposit': typeof JeetbuzzMinimumDepositRoute
  '/jeetbuzz-nagad-withdrawal': typeof JeetbuzzNagadWithdrawalRoute
  '/jeetbuzz-otp-not-received': typeof JeetbuzzOtpNotReceivedRoute
  '/jeetbuzz-partner-login': typeof JeetbuzzPartnerLoginRoute
  '/jeetbuzz-password-reset': typeof JeetbuzzPasswordResetRoute
  '/jeetbuzz-promo-code': typeof JeetbuzzPromoCodeRoute
  '/jeetbuzz-refer-bonus': typeof JeetbuzzReferBonusRoute
  '/jeetbuzz-referral-code': typeof JeetbuzzReferralCodeRoute
  '/jeetbuzz-review': typeof JeetbuzzReviewRoute
  '/jeetbuzz-sign-up': typeof JeetbuzzSignUpRoute
  '/jeetbuzz-withdrawal-pending': typeof JeetbuzzWithdrawalPendingRoute
  '/jeetbuzz-withdrawal-time': typeof JeetbuzzWithdrawalTimeRoute
  '/jest-buzz': typeof JestBuzzRoute
  '/jetbuzz': typeof JetbuzzRoute
  '/jitbuzz': typeof JitbuzzRoute
  '/live-cricket-betting': typeof LiveCricketBettingRoute
  '/login': typeof LoginRoute
  '/login-guide': typeof LoginGuideRoute
  '/login-problems': typeof LoginProblemsRoute
  '/login-security': typeof LoginSecurityRoute
  '/mobile-app-guide': typeof MobileAppGuideRoute
  '/nagad-guide': typeof NagadGuideRoute
  '/password-reset': typeof PasswordResetRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/payments': typeof PaymentsRoute
  '/paytm-guide': typeof PaytmGuideRoute
  '/phonepe-guide': typeof PhonepeGuideRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/registration-guide': typeof RegistrationGuideRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/review-policy': typeof ReviewPolicyRoute
  '/rocket-guide': typeof RocketGuideRoute
  '/security-guide': typeof SecurityGuideRoute
  '/signup': typeof SignupRoute
  '/sitemap-affiliate.xml': typeof SitemapAffiliateDotxmlRoute
  '/sitemap-bd.xml': typeof SitemapBdDotxmlRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-guides.xml': typeof SitemapGuidesDotxmlRoute
  '/sitemap-in.xml': typeof SitemapInDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-payments.xml': typeof SitemapPaymentsDotxmlRoute
  '/sitemap-pk.xml': typeof SitemapPkDotxmlRoute
  '/sitemap-solutions.xml': typeof SitemapSolutionsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports-betting': typeof SportsBettingRoute
  '/terms': typeof TermsRoute
  '/update-policy': typeof UpdatePolicyRoute
  '/upi-guide': typeof UpiGuideRoute
  '/verification': typeof VerificationRoute
  '/vip-program': typeof VipProgramRoute
  '/welcome-bonus': typeof WelcomeBonusRoute
  '/withdrawal-guide': typeof WithdrawalGuideRoute
  '/জিতবাজ': typeof Char2460Char2495Char2468Char2476Char2494Char2460Route
  '/app/launch': typeof AppLaunchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/affiliate': typeof GoAffiliateRoute
  '/go/login': typeof GoLoginRoute
  '/go/signup': typeof GoSignupRoute
  '/blog/': typeof BlogIndexRoute
  '/$country/$lang/$': typeof CountryLangSplatRoute
  '/$country/$lang/': typeof CountryLangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/affiliate-login': typeof AffiliateLoginRoute
  '/affiliate-program': typeof AffiliateProgramRoute
  '/agent-earning-guide': typeof AgentEarningGuideRoute
  '/android-web-app-guide': typeof AndroidWebAppGuideRoute
  '/apk-download-guide': typeof ApkDownloadGuideRoute
  '/author': typeof AuthorRoute
  '/aviator-guide': typeof AviatorGuideRoute
  '/bkash-guide': typeof BkashGuideRoute
  '/bonus-and-promotions': typeof BonusAndPromotionsRoute
  '/bonuses': typeof BonusesRoute
  '/casino-guide': typeof CasinoGuideRoute
  '/contact': typeof ContactRoute
  '/content-policy': typeof ContentPolicyRoute
  '/cricket-exchange-guide': typeof CricketExchangeGuideRoute
  '/deposit-guide': typeof DepositGuideRoute
  '/deposit-withdrawal-guide': typeof DepositWithdrawalGuideRoute
  '/download': typeof DownloadRoute
  '/easypaisa-guide': typeof EasypaisaGuideRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking': typeof FactCheckingRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/help': typeof HelpRoute
  '/how-to-delete-jeetbuzz-account': typeof HowToDeleteJeetbuzzAccountRoute
  '/ios-app-guide': typeof IosAppGuideRoute
  '/is-jeetbuzz-safe': typeof IsJeetbuzzSafeRoute
  '/jazzcash-guide': typeof JazzcashGuideRoute
  '/jeet-buzz': typeof JeetBuzzRoute
  '/jeetbuz': typeof JeetbuzRoute
  '/jeetbuzz-account-locked': typeof JeetbuzzAccountLockedRoute
  '/jeetbuzz-account-verification': typeof JeetbuzzAccountVerificationRoute
  '/jeetbuzz-affiliate-app': typeof JeetbuzzAffiliateAppRoute
  '/jeetbuzz-affiliate-commission': typeof JeetbuzzAffiliateCommissionRoute
  '/jeetbuzz-affiliate-commission-rate': typeof JeetbuzzAffiliateCommissionRateRoute
  '/jeetbuzz-affiliate-dashboard': typeof JeetbuzzAffiliateDashboardRoute
  '/jeetbuzz-affiliate-payment-methods': typeof JeetbuzzAffiliatePaymentMethodsRoute
  '/jeetbuzz-affiliate-signup': typeof JeetbuzzAffiliateSignupRoute
  '/jeetbuzz-affiliate-withdrawal': typeof JeetbuzzAffiliateWithdrawalRoute
  '/jeetbuzz-alternatives': typeof JeetbuzzAlternativesRoute
  '/jeetbuzz-apk-download': typeof JeetbuzzApkDownloadRoute
  '/jeetbuzz-app-not-opening': typeof JeetbuzzAppNotOpeningRoute
  '/jeetbuzz-app-update': typeof JeetbuzzAppUpdateRoute
  '/jeetbuzz-bkash-deposit': typeof JeetbuzzBkashDepositRoute
  '/jeetbuzz-com-login': typeof JeetbuzzComLoginRoute
  '/jeetbuzz-deposit-failed': typeof JeetbuzzDepositFailedRoute
  '/jeetbuzz-deposit-problem': typeof JeetbuzzDepositProblemRoute
  '/jeetbuzz-download-for-android': typeof JeetbuzzDownloadForAndroidRoute
  '/jeetbuzz-download-for-ios': typeof JeetbuzzDownloadForIosRoute
  '/jeetbuzz-first-deposit-bonus': typeof JeetbuzzFirstDepositBonusRoute
  '/jeetbuzz-live-cricket': typeof JeetbuzzLiveCricketRoute
  '/jeetbuzz-minimum-deposit': typeof JeetbuzzMinimumDepositRoute
  '/jeetbuzz-nagad-withdrawal': typeof JeetbuzzNagadWithdrawalRoute
  '/jeetbuzz-otp-not-received': typeof JeetbuzzOtpNotReceivedRoute
  '/jeetbuzz-partner-login': typeof JeetbuzzPartnerLoginRoute
  '/jeetbuzz-password-reset': typeof JeetbuzzPasswordResetRoute
  '/jeetbuzz-promo-code': typeof JeetbuzzPromoCodeRoute
  '/jeetbuzz-refer-bonus': typeof JeetbuzzReferBonusRoute
  '/jeetbuzz-referral-code': typeof JeetbuzzReferralCodeRoute
  '/jeetbuzz-review': typeof JeetbuzzReviewRoute
  '/jeetbuzz-sign-up': typeof JeetbuzzSignUpRoute
  '/jeetbuzz-withdrawal-pending': typeof JeetbuzzWithdrawalPendingRoute
  '/jeetbuzz-withdrawal-time': typeof JeetbuzzWithdrawalTimeRoute
  '/jest-buzz': typeof JestBuzzRoute
  '/jetbuzz': typeof JetbuzzRoute
  '/jitbuzz': typeof JitbuzzRoute
  '/live-cricket-betting': typeof LiveCricketBettingRoute
  '/login': typeof LoginRoute
  '/login-guide': typeof LoginGuideRoute
  '/login-problems': typeof LoginProblemsRoute
  '/login-security': typeof LoginSecurityRoute
  '/mobile-app-guide': typeof MobileAppGuideRoute
  '/nagad-guide': typeof NagadGuideRoute
  '/password-reset': typeof PasswordResetRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/payments': typeof PaymentsRoute
  '/paytm-guide': typeof PaytmGuideRoute
  '/phonepe-guide': typeof PhonepeGuideRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/registration-guide': typeof RegistrationGuideRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/review-policy': typeof ReviewPolicyRoute
  '/rocket-guide': typeof RocketGuideRoute
  '/security-guide': typeof SecurityGuideRoute
  '/signup': typeof SignupRoute
  '/sitemap-affiliate.xml': typeof SitemapAffiliateDotxmlRoute
  '/sitemap-bd.xml': typeof SitemapBdDotxmlRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-guides.xml': typeof SitemapGuidesDotxmlRoute
  '/sitemap-in.xml': typeof SitemapInDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-payments.xml': typeof SitemapPaymentsDotxmlRoute
  '/sitemap-pk.xml': typeof SitemapPkDotxmlRoute
  '/sitemap-solutions.xml': typeof SitemapSolutionsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports-betting': typeof SportsBettingRoute
  '/terms': typeof TermsRoute
  '/update-policy': typeof UpdatePolicyRoute
  '/upi-guide': typeof UpiGuideRoute
  '/verification': typeof VerificationRoute
  '/vip-program': typeof VipProgramRoute
  '/welcome-bonus': typeof WelcomeBonusRoute
  '/withdrawal-guide': typeof WithdrawalGuideRoute
  '/জিতবাজ': typeof Char2460Char2495Char2468Char2476Char2494Char2460Route
  '/app/launch': typeof AppLaunchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/affiliate': typeof GoAffiliateRoute
  '/go/login': typeof GoLoginRoute
  '/go/signup': typeof GoSignupRoute
  '/blog': typeof BlogIndexRoute
  '/$country/$lang/$': typeof CountryLangSplatRoute
  '/$country/$lang': typeof CountryLangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/affiliate-login': typeof AffiliateLoginRoute
  '/affiliate-program': typeof AffiliateProgramRoute
  '/agent-earning-guide': typeof AgentEarningGuideRoute
  '/android-web-app-guide': typeof AndroidWebAppGuideRoute
  '/apk-download-guide': typeof ApkDownloadGuideRoute
  '/author': typeof AuthorRoute
  '/aviator-guide': typeof AviatorGuideRoute
  '/bkash-guide': typeof BkashGuideRoute
  '/blog': typeof BlogRouteWithChildren
  '/bonus-and-promotions': typeof BonusAndPromotionsRoute
  '/bonuses': typeof BonusesRoute
  '/casino-guide': typeof CasinoGuideRoute
  '/contact': typeof ContactRoute
  '/content-policy': typeof ContentPolicyRoute
  '/cricket-exchange-guide': typeof CricketExchangeGuideRoute
  '/deposit-guide': typeof DepositGuideRoute
  '/deposit-withdrawal-guide': typeof DepositWithdrawalGuideRoute
  '/download': typeof DownloadRoute
  '/easypaisa-guide': typeof EasypaisaGuideRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking': typeof FactCheckingRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/help': typeof HelpRoute
  '/how-to-delete-jeetbuzz-account': typeof HowToDeleteJeetbuzzAccountRoute
  '/ios-app-guide': typeof IosAppGuideRoute
  '/is-jeetbuzz-safe': typeof IsJeetbuzzSafeRoute
  '/jazzcash-guide': typeof JazzcashGuideRoute
  '/jeet-buzz': typeof JeetBuzzRoute
  '/jeetbuz': typeof JeetbuzRoute
  '/jeetbuzz-account-locked': typeof JeetbuzzAccountLockedRoute
  '/jeetbuzz-account-verification': typeof JeetbuzzAccountVerificationRoute
  '/jeetbuzz-affiliate-app': typeof JeetbuzzAffiliateAppRoute
  '/jeetbuzz-affiliate-commission': typeof JeetbuzzAffiliateCommissionRoute
  '/jeetbuzz-affiliate-commission-rate': typeof JeetbuzzAffiliateCommissionRateRoute
  '/jeetbuzz-affiliate-dashboard': typeof JeetbuzzAffiliateDashboardRoute
  '/jeetbuzz-affiliate-payment-methods': typeof JeetbuzzAffiliatePaymentMethodsRoute
  '/jeetbuzz-affiliate-signup': typeof JeetbuzzAffiliateSignupRoute
  '/jeetbuzz-affiliate-withdrawal': typeof JeetbuzzAffiliateWithdrawalRoute
  '/jeetbuzz-alternatives': typeof JeetbuzzAlternativesRoute
  '/jeetbuzz-apk-download': typeof JeetbuzzApkDownloadRoute
  '/jeetbuzz-app-not-opening': typeof JeetbuzzAppNotOpeningRoute
  '/jeetbuzz-app-update': typeof JeetbuzzAppUpdateRoute
  '/jeetbuzz-bkash-deposit': typeof JeetbuzzBkashDepositRoute
  '/jeetbuzz-com-login': typeof JeetbuzzComLoginRoute
  '/jeetbuzz-deposit-failed': typeof JeetbuzzDepositFailedRoute
  '/jeetbuzz-deposit-problem': typeof JeetbuzzDepositProblemRoute
  '/jeetbuzz-download-for-android': typeof JeetbuzzDownloadForAndroidRoute
  '/jeetbuzz-download-for-ios': typeof JeetbuzzDownloadForIosRoute
  '/jeetbuzz-first-deposit-bonus': typeof JeetbuzzFirstDepositBonusRoute
  '/jeetbuzz-live-cricket': typeof JeetbuzzLiveCricketRoute
  '/jeetbuzz-minimum-deposit': typeof JeetbuzzMinimumDepositRoute
  '/jeetbuzz-nagad-withdrawal': typeof JeetbuzzNagadWithdrawalRoute
  '/jeetbuzz-otp-not-received': typeof JeetbuzzOtpNotReceivedRoute
  '/jeetbuzz-partner-login': typeof JeetbuzzPartnerLoginRoute
  '/jeetbuzz-password-reset': typeof JeetbuzzPasswordResetRoute
  '/jeetbuzz-promo-code': typeof JeetbuzzPromoCodeRoute
  '/jeetbuzz-refer-bonus': typeof JeetbuzzReferBonusRoute
  '/jeetbuzz-referral-code': typeof JeetbuzzReferralCodeRoute
  '/jeetbuzz-review': typeof JeetbuzzReviewRoute
  '/jeetbuzz-sign-up': typeof JeetbuzzSignUpRoute
  '/jeetbuzz-withdrawal-pending': typeof JeetbuzzWithdrawalPendingRoute
  '/jeetbuzz-withdrawal-time': typeof JeetbuzzWithdrawalTimeRoute
  '/jest-buzz': typeof JestBuzzRoute
  '/jetbuzz': typeof JetbuzzRoute
  '/jitbuzz': typeof JitbuzzRoute
  '/live-cricket-betting': typeof LiveCricketBettingRoute
  '/login': typeof LoginRoute
  '/login-guide': typeof LoginGuideRoute
  '/login-problems': typeof LoginProblemsRoute
  '/login-security': typeof LoginSecurityRoute
  '/mobile-app-guide': typeof MobileAppGuideRoute
  '/nagad-guide': typeof NagadGuideRoute
  '/password-reset': typeof PasswordResetRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/payments': typeof PaymentsRoute
  '/paytm-guide': typeof PaytmGuideRoute
  '/phonepe-guide': typeof PhonepeGuideRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/registration-guide': typeof RegistrationGuideRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/review-policy': typeof ReviewPolicyRoute
  '/rocket-guide': typeof RocketGuideRoute
  '/security-guide': typeof SecurityGuideRoute
  '/signup': typeof SignupRoute
  '/sitemap-affiliate.xml': typeof SitemapAffiliateDotxmlRoute
  '/sitemap-bd.xml': typeof SitemapBdDotxmlRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-guides.xml': typeof SitemapGuidesDotxmlRoute
  '/sitemap-in.xml': typeof SitemapInDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-payments.xml': typeof SitemapPaymentsDotxmlRoute
  '/sitemap-pk.xml': typeof SitemapPkDotxmlRoute
  '/sitemap-solutions.xml': typeof SitemapSolutionsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports-betting': typeof SportsBettingRoute
  '/terms': typeof TermsRoute
  '/update-policy': typeof UpdatePolicyRoute
  '/upi-guide': typeof UpiGuideRoute
  '/verification': typeof VerificationRoute
  '/vip-program': typeof VipProgramRoute
  '/welcome-bonus': typeof WelcomeBonusRoute
  '/withdrawal-guide': typeof WithdrawalGuideRoute
  '/জিতবাজ': typeof Char2460Char2495Char2468Char2476Char2494Char2460Route
  '/app/launch': typeof AppLaunchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/affiliate': typeof GoAffiliateRoute
  '/go/login': typeof GoLoginRoute
  '/go/signup': typeof GoSignupRoute
  '/blog/': typeof BlogIndexRoute
  '/$country/$lang/$': typeof CountryLangSplatRoute
  '/$country/$lang/': typeof CountryLangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/affiliate-login'
    | '/affiliate-program'
    | '/agent-earning-guide'
    | '/android-web-app-guide'
    | '/apk-download-guide'
    | '/author'
    | '/aviator-guide'
    | '/bkash-guide'
    | '/blog'
    | '/bonus-and-promotions'
    | '/bonuses'
    | '/casino-guide'
    | '/contact'
    | '/content-policy'
    | '/cricket-exchange-guide'
    | '/deposit-guide'
    | '/deposit-withdrawal-guide'
    | '/download'
    | '/easypaisa-guide'
    | '/editorial-policy'
    | '/fact-checking'
    | '/faq'
    | '/games'
    | '/help'
    | '/how-to-delete-jeetbuzz-account'
    | '/ios-app-guide'
    | '/is-jeetbuzz-safe'
    | '/jazzcash-guide'
    | '/jeet-buzz'
    | '/jeetbuz'
    | '/jeetbuzz-account-locked'
    | '/jeetbuzz-account-verification'
    | '/jeetbuzz-affiliate-app'
    | '/jeetbuzz-affiliate-commission'
    | '/jeetbuzz-affiliate-commission-rate'
    | '/jeetbuzz-affiliate-dashboard'
    | '/jeetbuzz-affiliate-payment-methods'
    | '/jeetbuzz-affiliate-signup'
    | '/jeetbuzz-affiliate-withdrawal'
    | '/jeetbuzz-alternatives'
    | '/jeetbuzz-apk-download'
    | '/jeetbuzz-app-not-opening'
    | '/jeetbuzz-app-update'
    | '/jeetbuzz-bkash-deposit'
    | '/jeetbuzz-com-login'
    | '/jeetbuzz-deposit-failed'
    | '/jeetbuzz-deposit-problem'
    | '/jeetbuzz-download-for-android'
    | '/jeetbuzz-download-for-ios'
    | '/jeetbuzz-first-deposit-bonus'
    | '/jeetbuzz-live-cricket'
    | '/jeetbuzz-minimum-deposit'
    | '/jeetbuzz-nagad-withdrawal'
    | '/jeetbuzz-otp-not-received'
    | '/jeetbuzz-partner-login'
    | '/jeetbuzz-password-reset'
    | '/jeetbuzz-promo-code'
    | '/jeetbuzz-refer-bonus'
    | '/jeetbuzz-referral-code'
    | '/jeetbuzz-review'
    | '/jeetbuzz-sign-up'
    | '/jeetbuzz-withdrawal-pending'
    | '/jeetbuzz-withdrawal-time'
    | '/jest-buzz'
    | '/jetbuzz'
    | '/jitbuzz'
    | '/live-cricket-betting'
    | '/login'
    | '/login-guide'
    | '/login-problems'
    | '/login-security'
    | '/mobile-app-guide'
    | '/nagad-guide'
    | '/password-reset'
    | '/payment-methods'
    | '/payments'
    | '/paytm-guide'
    | '/phonepe-guide'
    | '/privacy-policy'
    | '/register'
    | '/registration-guide'
    | '/responsible-gaming'
    | '/review-policy'
    | '/rocket-guide'
    | '/security-guide'
    | '/signup'
    | '/sitemap-affiliate.xml'
    | '/sitemap-bd.xml'
    | '/sitemap-blog.xml'
    | '/sitemap-guides.xml'
    | '/sitemap-in.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-payments.xml'
    | '/sitemap-pk.xml'
    | '/sitemap-solutions.xml'
    | '/sitemap.xml'
    | '/sports-betting'
    | '/terms'
    | '/update-policy'
    | '/upi-guide'
    | '/verification'
    | '/vip-program'
    | '/welcome-bonus'
    | '/withdrawal-guide'
    | '/জিতবাজ'
    | '/app/launch'
    | '/blog/$slug'
    | '/go/affiliate'
    | '/go/login'
    | '/go/signup'
    | '/blog/'
    | '/$country/$lang/$'
    | '/$country/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/affiliate-login'
    | '/affiliate-program'
    | '/agent-earning-guide'
    | '/android-web-app-guide'
    | '/apk-download-guide'
    | '/author'
    | '/aviator-guide'
    | '/bkash-guide'
    | '/bonus-and-promotions'
    | '/bonuses'
    | '/casino-guide'
    | '/contact'
    | '/content-policy'
    | '/cricket-exchange-guide'
    | '/deposit-guide'
    | '/deposit-withdrawal-guide'
    | '/download'
    | '/easypaisa-guide'
    | '/editorial-policy'
    | '/fact-checking'
    | '/faq'
    | '/games'
    | '/help'
    | '/how-to-delete-jeetbuzz-account'
    | '/ios-app-guide'
    | '/is-jeetbuzz-safe'
    | '/jazzcash-guide'
    | '/jeet-buzz'
    | '/jeetbuz'
    | '/jeetbuzz-account-locked'
    | '/jeetbuzz-account-verification'
    | '/jeetbuzz-affiliate-app'
    | '/jeetbuzz-affiliate-commission'
    | '/jeetbuzz-affiliate-commission-rate'
    | '/jeetbuzz-affiliate-dashboard'
    | '/jeetbuzz-affiliate-payment-methods'
    | '/jeetbuzz-affiliate-signup'
    | '/jeetbuzz-affiliate-withdrawal'
    | '/jeetbuzz-alternatives'
    | '/jeetbuzz-apk-download'
    | '/jeetbuzz-app-not-opening'
    | '/jeetbuzz-app-update'
    | '/jeetbuzz-bkash-deposit'
    | '/jeetbuzz-com-login'
    | '/jeetbuzz-deposit-failed'
    | '/jeetbuzz-deposit-problem'
    | '/jeetbuzz-download-for-android'
    | '/jeetbuzz-download-for-ios'
    | '/jeetbuzz-first-deposit-bonus'
    | '/jeetbuzz-live-cricket'
    | '/jeetbuzz-minimum-deposit'
    | '/jeetbuzz-nagad-withdrawal'
    | '/jeetbuzz-otp-not-received'
    | '/jeetbuzz-partner-login'
    | '/jeetbuzz-password-reset'
    | '/jeetbuzz-promo-code'
    | '/jeetbuzz-refer-bonus'
    | '/jeetbuzz-referral-code'
    | '/jeetbuzz-review'
    | '/jeetbuzz-sign-up'
    | '/jeetbuzz-withdrawal-pending'
    | '/jeetbuzz-withdrawal-time'
    | '/jest-buzz'
    | '/jetbuzz'
    | '/jitbuzz'
    | '/live-cricket-betting'
    | '/login'
    | '/login-guide'
    | '/login-problems'
    | '/login-security'
    | '/mobile-app-guide'
    | '/nagad-guide'
    | '/password-reset'
    | '/payment-methods'
    | '/payments'
    | '/paytm-guide'
    | '/phonepe-guide'
    | '/privacy-policy'
    | '/register'
    | '/registration-guide'
    | '/responsible-gaming'
    | '/review-policy'
    | '/rocket-guide'
    | '/security-guide'
    | '/signup'
    | '/sitemap-affiliate.xml'
    | '/sitemap-bd.xml'
    | '/sitemap-blog.xml'
    | '/sitemap-guides.xml'
    | '/sitemap-in.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-payments.xml'
    | '/sitemap-pk.xml'
    | '/sitemap-solutions.xml'
    | '/sitemap.xml'
    | '/sports-betting'
    | '/terms'
    | '/update-policy'
    | '/upi-guide'
    | '/verification'
    | '/vip-program'
    | '/welcome-bonus'
    | '/withdrawal-guide'
    | '/জিতবাজ'
    | '/app/launch'
    | '/blog/$slug'
    | '/go/affiliate'
    | '/go/login'
    | '/go/signup'
    | '/blog'
    | '/$country/$lang/$'
    | '/$country/$lang'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/affiliate-login'
    | '/affiliate-program'
    | '/agent-earning-guide'
    | '/android-web-app-guide'
    | '/apk-download-guide'
    | '/author'
    | '/aviator-guide'
    | '/bkash-guide'
    | '/blog'
    | '/bonus-and-promotions'
    | '/bonuses'
    | '/casino-guide'
    | '/contact'
    | '/content-policy'
    | '/cricket-exchange-guide'
    | '/deposit-guide'
    | '/deposit-withdrawal-guide'
    | '/download'
    | '/easypaisa-guide'
    | '/editorial-policy'
    | '/fact-checking'
    | '/faq'
    | '/games'
    | '/help'
    | '/how-to-delete-jeetbuzz-account'
    | '/ios-app-guide'
    | '/is-jeetbuzz-safe'
    | '/jazzcash-guide'
    | '/jeet-buzz'
    | '/jeetbuz'
    | '/jeetbuzz-account-locked'
    | '/jeetbuzz-account-verification'
    | '/jeetbuzz-affiliate-app'
    | '/jeetbuzz-affiliate-commission'
    | '/jeetbuzz-affiliate-commission-rate'
    | '/jeetbuzz-affiliate-dashboard'
    | '/jeetbuzz-affiliate-payment-methods'
    | '/jeetbuzz-affiliate-signup'
    | '/jeetbuzz-affiliate-withdrawal'
    | '/jeetbuzz-alternatives'
    | '/jeetbuzz-apk-download'
    | '/jeetbuzz-app-not-opening'
    | '/jeetbuzz-app-update'
    | '/jeetbuzz-bkash-deposit'
    | '/jeetbuzz-com-login'
    | '/jeetbuzz-deposit-failed'
    | '/jeetbuzz-deposit-problem'
    | '/jeetbuzz-download-for-android'
    | '/jeetbuzz-download-for-ios'
    | '/jeetbuzz-first-deposit-bonus'
    | '/jeetbuzz-live-cricket'
    | '/jeetbuzz-minimum-deposit'
    | '/jeetbuzz-nagad-withdrawal'
    | '/jeetbuzz-otp-not-received'
    | '/jeetbuzz-partner-login'
    | '/jeetbuzz-password-reset'
    | '/jeetbuzz-promo-code'
    | '/jeetbuzz-refer-bonus'
    | '/jeetbuzz-referral-code'
    | '/jeetbuzz-review'
    | '/jeetbuzz-sign-up'
    | '/jeetbuzz-withdrawal-pending'
    | '/jeetbuzz-withdrawal-time'
    | '/jest-buzz'
    | '/jetbuzz'
    | '/jitbuzz'
    | '/live-cricket-betting'
    | '/login'
    | '/login-guide'
    | '/login-problems'
    | '/login-security'
    | '/mobile-app-guide'
    | '/nagad-guide'
    | '/password-reset'
    | '/payment-methods'
    | '/payments'
    | '/paytm-guide'
    | '/phonepe-guide'
    | '/privacy-policy'
    | '/register'
    | '/registration-guide'
    | '/responsible-gaming'
    | '/review-policy'
    | '/rocket-guide'
    | '/security-guide'
    | '/signup'
    | '/sitemap-affiliate.xml'
    | '/sitemap-bd.xml'
    | '/sitemap-blog.xml'
    | '/sitemap-guides.xml'
    | '/sitemap-in.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-payments.xml'
    | '/sitemap-pk.xml'
    | '/sitemap-solutions.xml'
    | '/sitemap.xml'
    | '/sports-betting'
    | '/terms'
    | '/update-policy'
    | '/upi-guide'
    | '/verification'
    | '/vip-program'
    | '/welcome-bonus'
    | '/withdrawal-guide'
    | '/জিতবাজ'
    | '/app/launch'
    | '/blog/$slug'
    | '/go/affiliate'
    | '/go/login'
    | '/go/signup'
    | '/blog/'
    | '/$country/$lang/$'
    | '/$country/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  AffiliateLoginRoute: typeof AffiliateLoginRoute
  AffiliateProgramRoute: typeof AffiliateProgramRoute
  AgentEarningGuideRoute: typeof AgentEarningGuideRoute
  AndroidWebAppGuideRoute: typeof AndroidWebAppGuideRoute
  ApkDownloadGuideRoute: typeof ApkDownloadGuideRoute
  AuthorRoute: typeof AuthorRoute
  AviatorGuideRoute: typeof AviatorGuideRoute
  BkashGuideRoute: typeof BkashGuideRoute
  BlogRoute: typeof BlogRouteWithChildren
  BonusAndPromotionsRoute: typeof BonusAndPromotionsRoute
  BonusesRoute: typeof BonusesRoute
  CasinoGuideRoute: typeof CasinoGuideRoute
  ContactRoute: typeof ContactRoute
  ContentPolicyRoute: typeof ContentPolicyRoute
  CricketExchangeGuideRoute: typeof CricketExchangeGuideRoute
  DepositGuideRoute: typeof DepositGuideRoute
  DepositWithdrawalGuideRoute: typeof DepositWithdrawalGuideRoute
  DownloadRoute: typeof DownloadRoute
  EasypaisaGuideRoute: typeof EasypaisaGuideRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FactCheckingRoute: typeof FactCheckingRoute
  FaqRoute: typeof FaqRoute
  GamesRoute: typeof GamesRoute
  HelpRoute: typeof HelpRoute
  HowToDeleteJeetbuzzAccountRoute: typeof HowToDeleteJeetbuzzAccountRoute
  IosAppGuideRoute: typeof IosAppGuideRoute
  IsJeetbuzzSafeRoute: typeof IsJeetbuzzSafeRoute
  JazzcashGuideRoute: typeof JazzcashGuideRoute
  JeetBuzzRoute: typeof JeetBuzzRoute
  JeetbuzRoute: typeof JeetbuzRoute
  JeetbuzzAccountLockedRoute: typeof JeetbuzzAccountLockedRoute
  JeetbuzzAccountVerificationRoute: typeof JeetbuzzAccountVerificationRoute
  JeetbuzzAffiliateAppRoute: typeof JeetbuzzAffiliateAppRoute
  JeetbuzzAffiliateCommissionRoute: typeof JeetbuzzAffiliateCommissionRoute
  JeetbuzzAffiliateCommissionRateRoute: typeof JeetbuzzAffiliateCommissionRateRoute
  JeetbuzzAffiliateDashboardRoute: typeof JeetbuzzAffiliateDashboardRoute
  JeetbuzzAffiliatePaymentMethodsRoute: typeof JeetbuzzAffiliatePaymentMethodsRoute
  JeetbuzzAffiliateSignupRoute: typeof JeetbuzzAffiliateSignupRoute
  JeetbuzzAffiliateWithdrawalRoute: typeof JeetbuzzAffiliateWithdrawalRoute
  JeetbuzzAlternativesRoute: typeof JeetbuzzAlternativesRoute
  JeetbuzzApkDownloadRoute: typeof JeetbuzzApkDownloadRoute
  JeetbuzzAppNotOpeningRoute: typeof JeetbuzzAppNotOpeningRoute
  JeetbuzzAppUpdateRoute: typeof JeetbuzzAppUpdateRoute
  JeetbuzzBkashDepositRoute: typeof JeetbuzzBkashDepositRoute
  JeetbuzzComLoginRoute: typeof JeetbuzzComLoginRoute
  JeetbuzzDepositFailedRoute: typeof JeetbuzzDepositFailedRoute
  JeetbuzzDepositProblemRoute: typeof JeetbuzzDepositProblemRoute
  JeetbuzzDownloadForAndroidRoute: typeof JeetbuzzDownloadForAndroidRoute
  JeetbuzzDownloadForIosRoute: typeof JeetbuzzDownloadForIosRoute
  JeetbuzzFirstDepositBonusRoute: typeof JeetbuzzFirstDepositBonusRoute
  JeetbuzzLiveCricketRoute: typeof JeetbuzzLiveCricketRoute
  JeetbuzzMinimumDepositRoute: typeof JeetbuzzMinimumDepositRoute
  JeetbuzzNagadWithdrawalRoute: typeof JeetbuzzNagadWithdrawalRoute
  JeetbuzzOtpNotReceivedRoute: typeof JeetbuzzOtpNotReceivedRoute
  JeetbuzzPartnerLoginRoute: typeof JeetbuzzPartnerLoginRoute
  JeetbuzzPasswordResetRoute: typeof JeetbuzzPasswordResetRoute
  JeetbuzzPromoCodeRoute: typeof JeetbuzzPromoCodeRoute
  JeetbuzzReferBonusRoute: typeof JeetbuzzReferBonusRoute
  JeetbuzzReferralCodeRoute: typeof JeetbuzzReferralCodeRoute
  JeetbuzzReviewRoute: typeof JeetbuzzReviewRoute
  JeetbuzzSignUpRoute: typeof JeetbuzzSignUpRoute
  JeetbuzzWithdrawalPendingRoute: typeof JeetbuzzWithdrawalPendingRoute
  JeetbuzzWithdrawalTimeRoute: typeof JeetbuzzWithdrawalTimeRoute
  JestBuzzRoute: typeof JestBuzzRoute
  JetbuzzRoute: typeof JetbuzzRoute
  JitbuzzRoute: typeof JitbuzzRoute
  LiveCricketBettingRoute: typeof LiveCricketBettingRoute
  LoginRoute: typeof LoginRoute
  LoginGuideRoute: typeof LoginGuideRoute
  LoginProblemsRoute: typeof LoginProblemsRoute
  LoginSecurityRoute: typeof LoginSecurityRoute
  MobileAppGuideRoute: typeof MobileAppGuideRoute
  NagadGuideRoute: typeof NagadGuideRoute
  PasswordResetRoute: typeof PasswordResetRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  PaymentsRoute: typeof PaymentsRoute
  PaytmGuideRoute: typeof PaytmGuideRoute
  PhonepeGuideRoute: typeof PhonepeGuideRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  RegistrationGuideRoute: typeof RegistrationGuideRoute
  ResponsibleGamingRoute: typeof ResponsibleGamingRoute
  ReviewPolicyRoute: typeof ReviewPolicyRoute
  RocketGuideRoute: typeof RocketGuideRoute
  SecurityGuideRoute: typeof SecurityGuideRoute
  SignupRoute: typeof SignupRoute
  SitemapAffiliateDotxmlRoute: typeof SitemapAffiliateDotxmlRoute
  SitemapBdDotxmlRoute: typeof SitemapBdDotxmlRoute
  SitemapBlogDotxmlRoute: typeof SitemapBlogDotxmlRoute
  SitemapGuidesDotxmlRoute: typeof SitemapGuidesDotxmlRoute
  SitemapInDotxmlRoute: typeof SitemapInDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapPaymentsDotxmlRoute: typeof SitemapPaymentsDotxmlRoute
  SitemapPkDotxmlRoute: typeof SitemapPkDotxmlRoute
  SitemapSolutionsDotxmlRoute: typeof SitemapSolutionsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsBettingRoute: typeof SportsBettingRoute
  TermsRoute: typeof TermsRoute
  UpdatePolicyRoute: typeof UpdatePolicyRoute
  UpiGuideRoute: typeof UpiGuideRoute
  VerificationRoute: typeof VerificationRoute
  VipProgramRoute: typeof VipProgramRoute
  WelcomeBonusRoute: typeof WelcomeBonusRoute
  WithdrawalGuideRoute: typeof WithdrawalGuideRoute
  Char2460Char2495Char2468Char2476Char2494Char2460Route: typeof Char2460Char2495Char2468Char2476Char2494Char2460Route
  AppLaunchRoute: typeof AppLaunchRoute
  GoAffiliateRoute: typeof GoAffiliateRoute
  GoLoginRoute: typeof GoLoginRoute
  GoSignupRoute: typeof GoSignupRoute
  CountryLangSplatRoute: typeof CountryLangSplatRoute
  CountryLangIndexRoute: typeof CountryLangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/জিতবাজ': {
      id: '/জিতবাজ'
      path: '/জিতবাজ'
      fullPath: '/জিতবাজ'
      preLoaderRoute: typeof Char2460Char2495Char2468Char2476Char2494Char2460RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawal-guide': {
      id: '/withdrawal-guide'
      path: '/withdrawal-guide'
      fullPath: '/withdrawal-guide'
      preLoaderRoute: typeof WithdrawalGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome-bonus': {
      id: '/welcome-bonus'
      path: '/welcome-bonus'
      fullPath: '/welcome-bonus'
      preLoaderRoute: typeof WelcomeBonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-program': {
      id: '/vip-program'
      path: '/vip-program'
      fullPath: '/vip-program'
      preLoaderRoute: typeof VipProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upi-guide': {
      id: '/upi-guide'
      path: '/upi-guide'
      fullPath: '/upi-guide'
      preLoaderRoute: typeof UpiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-policy': {
      id: '/update-policy'
      path: '/update-policy'
      fullPath: '/update-policy'
      preLoaderRoute: typeof UpdatePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-betting': {
      id: '/sports-betting'
      path: '/sports-betting'
      fullPath: '/sports-betting'
      preLoaderRoute: typeof SportsBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-solutions.xml': {
      id: '/sitemap-solutions.xml'
      path: '/sitemap-solutions.xml'
      fullPath: '/sitemap-solutions.xml'
      preLoaderRoute: typeof SitemapSolutionsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pk.xml': {
      id: '/sitemap-pk.xml'
      path: '/sitemap-pk.xml'
      fullPath: '/sitemap-pk.xml'
      preLoaderRoute: typeof SitemapPkDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-payments.xml': {
      id: '/sitemap-payments.xml'
      path: '/sitemap-payments.xml'
      fullPath: '/sitemap-payments.xml'
      preLoaderRoute: typeof SitemapPaymentsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-in.xml': {
      id: '/sitemap-in.xml'
      path: '/sitemap-in.xml'
      fullPath: '/sitemap-in.xml'
      preLoaderRoute: typeof SitemapInDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-guides.xml': {
      id: '/sitemap-guides.xml'
      path: '/sitemap-guides.xml'
      fullPath: '/sitemap-guides.xml'
      preLoaderRoute: typeof SitemapGuidesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-blog.xml': {
      id: '/sitemap-blog.xml'
      path: '/sitemap-blog.xml'
      fullPath: '/sitemap-blog.xml'
      preLoaderRoute: typeof SitemapBlogDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-bd.xml': {
      id: '/sitemap-bd.xml'
      path: '/sitemap-bd.xml'
      fullPath: '/sitemap-bd.xml'
      preLoaderRoute: typeof SitemapBdDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-affiliate.xml': {
      id: '/sitemap-affiliate.xml'
      path: '/sitemap-affiliate.xml'
      fullPath: '/sitemap-affiliate.xml'
      preLoaderRoute: typeof SitemapAffiliateDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-guide': {
      id: '/security-guide'
      path: '/security-guide'
      fullPath: '/security-guide'
      preLoaderRoute: typeof SecurityGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rocket-guide': {
      id: '/rocket-guide'
      path: '/rocket-guide'
      fullPath: '/rocket-guide'
      preLoaderRoute: typeof RocketGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-policy': {
      id: '/review-policy'
      path: '/review-policy'
      fullPath: '/review-policy'
      preLoaderRoute: typeof ReviewPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gaming': {
      id: '/responsible-gaming'
      path: '/responsible-gaming'
      fullPath: '/responsible-gaming'
      preLoaderRoute: typeof ResponsibleGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-guide': {
      id: '/registration-guide'
      path: '/registration-guide'
      fullPath: '/registration-guide'
      preLoaderRoute: typeof RegistrationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phonepe-guide': {
      id: '/phonepe-guide'
      path: '/phonepe-guide'
      fullPath: '/phonepe-guide'
      preLoaderRoute: typeof PhonepeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paytm-guide': {
      id: '/paytm-guide'
      path: '/paytm-guide'
      fullPath: '/paytm-guide'
      preLoaderRoute: typeof PaytmGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nagad-guide': {
      id: '/nagad-guide'
      path: '/nagad-guide'
      fullPath: '/nagad-guide'
      preLoaderRoute: typeof NagadGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-app-guide': {
      id: '/mobile-app-guide'
      path: '/mobile-app-guide'
      fullPath: '/mobile-app-guide'
      preLoaderRoute: typeof MobileAppGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-security': {
      id: '/login-security'
      path: '/login-security'
      fullPath: '/login-security'
      preLoaderRoute: typeof LoginSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-problems': {
      id: '/login-problems'
      path: '/login-problems'
      fullPath: '/login-problems'
      preLoaderRoute: typeof LoginProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-guide': {
      id: '/login-guide'
      path: '/login-guide'
      fullPath: '/login-guide'
      preLoaderRoute: typeof LoginGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-cricket-betting': {
      id: '/live-cricket-betting'
      path: '/live-cricket-betting'
      fullPath: '/live-cricket-betting'
      preLoaderRoute: typeof LiveCricketBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jitbuzz': {
      id: '/jitbuzz'
      path: '/jitbuzz'
      fullPath: '/jitbuzz'
      preLoaderRoute: typeof JitbuzzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jetbuzz': {
      id: '/jetbuzz'
      path: '/jetbuzz'
      fullPath: '/jetbuzz'
      preLoaderRoute: typeof JetbuzzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jest-buzz': {
      id: '/jest-buzz'
      path: '/jest-buzz'
      fullPath: '/jest-buzz'
      preLoaderRoute: typeof JestBuzzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-withdrawal-time': {
      id: '/jeetbuzz-withdrawal-time'
      path: '/jeetbuzz-withdrawal-time'
      fullPath: '/jeetbuzz-withdrawal-time'
      preLoaderRoute: typeof JeetbuzzWithdrawalTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-withdrawal-pending': {
      id: '/jeetbuzz-withdrawal-pending'
      path: '/jeetbuzz-withdrawal-pending'
      fullPath: '/jeetbuzz-withdrawal-pending'
      preLoaderRoute: typeof JeetbuzzWithdrawalPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-sign-up': {
      id: '/jeetbuzz-sign-up'
      path: '/jeetbuzz-sign-up'
      fullPath: '/jeetbuzz-sign-up'
      preLoaderRoute: typeof JeetbuzzSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-review': {
      id: '/jeetbuzz-review'
      path: '/jeetbuzz-review'
      fullPath: '/jeetbuzz-review'
      preLoaderRoute: typeof JeetbuzzReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-referral-code': {
      id: '/jeetbuzz-referral-code'
      path: '/jeetbuzz-referral-code'
      fullPath: '/jeetbuzz-referral-code'
      preLoaderRoute: typeof JeetbuzzReferralCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-refer-bonus': {
      id: '/jeetbuzz-refer-bonus'
      path: '/jeetbuzz-refer-bonus'
      fullPath: '/jeetbuzz-refer-bonus'
      preLoaderRoute: typeof JeetbuzzReferBonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-promo-code': {
      id: '/jeetbuzz-promo-code'
      path: '/jeetbuzz-promo-code'
      fullPath: '/jeetbuzz-promo-code'
      preLoaderRoute: typeof JeetbuzzPromoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-password-reset': {
      id: '/jeetbuzz-password-reset'
      path: '/jeetbuzz-password-reset'
      fullPath: '/jeetbuzz-password-reset'
      preLoaderRoute: typeof JeetbuzzPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-partner-login': {
      id: '/jeetbuzz-partner-login'
      path: '/jeetbuzz-partner-login'
      fullPath: '/jeetbuzz-partner-login'
      preLoaderRoute: typeof JeetbuzzPartnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-otp-not-received': {
      id: '/jeetbuzz-otp-not-received'
      path: '/jeetbuzz-otp-not-received'
      fullPath: '/jeetbuzz-otp-not-received'
      preLoaderRoute: typeof JeetbuzzOtpNotReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-nagad-withdrawal': {
      id: '/jeetbuzz-nagad-withdrawal'
      path: '/jeetbuzz-nagad-withdrawal'
      fullPath: '/jeetbuzz-nagad-withdrawal'
      preLoaderRoute: typeof JeetbuzzNagadWithdrawalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-minimum-deposit': {
      id: '/jeetbuzz-minimum-deposit'
      path: '/jeetbuzz-minimum-deposit'
      fullPath: '/jeetbuzz-minimum-deposit'
      preLoaderRoute: typeof JeetbuzzMinimumDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-live-cricket': {
      id: '/jeetbuzz-live-cricket'
      path: '/jeetbuzz-live-cricket'
      fullPath: '/jeetbuzz-live-cricket'
      preLoaderRoute: typeof JeetbuzzLiveCricketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-first-deposit-bonus': {
      id: '/jeetbuzz-first-deposit-bonus'
      path: '/jeetbuzz-first-deposit-bonus'
      fullPath: '/jeetbuzz-first-deposit-bonus'
      preLoaderRoute: typeof JeetbuzzFirstDepositBonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-download-for-ios': {
      id: '/jeetbuzz-download-for-ios'
      path: '/jeetbuzz-download-for-ios'
      fullPath: '/jeetbuzz-download-for-ios'
      preLoaderRoute: typeof JeetbuzzDownloadForIosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-download-for-android': {
      id: '/jeetbuzz-download-for-android'
      path: '/jeetbuzz-download-for-android'
      fullPath: '/jeetbuzz-download-for-android'
      preLoaderRoute: typeof JeetbuzzDownloadForAndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-deposit-problem': {
      id: '/jeetbuzz-deposit-problem'
      path: '/jeetbuzz-deposit-problem'
      fullPath: '/jeetbuzz-deposit-problem'
      preLoaderRoute: typeof JeetbuzzDepositProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-deposit-failed': {
      id: '/jeetbuzz-deposit-failed'
      path: '/jeetbuzz-deposit-failed'
      fullPath: '/jeetbuzz-deposit-failed'
      preLoaderRoute: typeof JeetbuzzDepositFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-com-login': {
      id: '/jeetbuzz-com-login'
      path: '/jeetbuzz-com-login'
      fullPath: '/jeetbuzz-com-login'
      preLoaderRoute: typeof JeetbuzzComLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-bkash-deposit': {
      id: '/jeetbuzz-bkash-deposit'
      path: '/jeetbuzz-bkash-deposit'
      fullPath: '/jeetbuzz-bkash-deposit'
      preLoaderRoute: typeof JeetbuzzBkashDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-app-update': {
      id: '/jeetbuzz-app-update'
      path: '/jeetbuzz-app-update'
      fullPath: '/jeetbuzz-app-update'
      preLoaderRoute: typeof JeetbuzzAppUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-app-not-opening': {
      id: '/jeetbuzz-app-not-opening'
      path: '/jeetbuzz-app-not-opening'
      fullPath: '/jeetbuzz-app-not-opening'
      preLoaderRoute: typeof JeetbuzzAppNotOpeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-apk-download': {
      id: '/jeetbuzz-apk-download'
      path: '/jeetbuzz-apk-download'
      fullPath: '/jeetbuzz-apk-download'
      preLoaderRoute: typeof JeetbuzzApkDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-alternatives': {
      id: '/jeetbuzz-alternatives'
      path: '/jeetbuzz-alternatives'
      fullPath: '/jeetbuzz-alternatives'
      preLoaderRoute: typeof JeetbuzzAlternativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-affiliate-withdrawal': {
      id: '/jeetbuzz-affiliate-withdrawal'
      path: '/jeetbuzz-affiliate-withdrawal'
      fullPath: '/jeetbuzz-affiliate-withdrawal'
      preLoaderRoute: typeof JeetbuzzAffiliateWithdrawalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-affiliate-signup': {
      id: '/jeetbuzz-affiliate-signup'
      path: '/jeetbuzz-affiliate-signup'
      fullPath: '/jeetbuzz-affiliate-signup'
      preLoaderRoute: typeof JeetbuzzAffiliateSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-affiliate-payment-methods': {
      id: '/jeetbuzz-affiliate-payment-methods'
      path: '/jeetbuzz-affiliate-payment-methods'
      fullPath: '/jeetbuzz-affiliate-payment-methods'
      preLoaderRoute: typeof JeetbuzzAffiliatePaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-affiliate-dashboard': {
      id: '/jeetbuzz-affiliate-dashboard'
      path: '/jeetbuzz-affiliate-dashboard'
      fullPath: '/jeetbuzz-affiliate-dashboard'
      preLoaderRoute: typeof JeetbuzzAffiliateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-affiliate-commission-rate': {
      id: '/jeetbuzz-affiliate-commission-rate'
      path: '/jeetbuzz-affiliate-commission-rate'
      fullPath: '/jeetbuzz-affiliate-commission-rate'
      preLoaderRoute: typeof JeetbuzzAffiliateCommissionRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-affiliate-commission': {
      id: '/jeetbuzz-affiliate-commission'
      path: '/jeetbuzz-affiliate-commission'
      fullPath: '/jeetbuzz-affiliate-commission'
      preLoaderRoute: typeof JeetbuzzAffiliateCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-affiliate-app': {
      id: '/jeetbuzz-affiliate-app'
      path: '/jeetbuzz-affiliate-app'
      fullPath: '/jeetbuzz-affiliate-app'
      preLoaderRoute: typeof JeetbuzzAffiliateAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-account-verification': {
      id: '/jeetbuzz-account-verification'
      path: '/jeetbuzz-account-verification'
      fullPath: '/jeetbuzz-account-verification'
      preLoaderRoute: typeof JeetbuzzAccountVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-account-locked': {
      id: '/jeetbuzz-account-locked'
      path: '/jeetbuzz-account-locked'
      fullPath: '/jeetbuzz-account-locked'
      preLoaderRoute: typeof JeetbuzzAccountLockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuz': {
      id: '/jeetbuz'
      path: '/jeetbuz'
      fullPath: '/jeetbuz'
      preLoaderRoute: typeof JeetbuzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeet-buzz': {
      id: '/jeet-buzz'
      path: '/jeet-buzz'
      fullPath: '/jeet-buzz'
      preLoaderRoute: typeof JeetBuzzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jazzcash-guide': {
      id: '/jazzcash-guide'
      path: '/jazzcash-guide'
      fullPath: '/jazzcash-guide'
      preLoaderRoute: typeof JazzcashGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/is-jeetbuzz-safe': {
      id: '/is-jeetbuzz-safe'
      path: '/is-jeetbuzz-safe'
      fullPath: '/is-jeetbuzz-safe'
      preLoaderRoute: typeof IsJeetbuzzSafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ios-app-guide': {
      id: '/ios-app-guide'
      path: '/ios-app-guide'
      fullPath: '/ios-app-guide'
      preLoaderRoute: typeof IosAppGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-delete-jeetbuzz-account': {
      id: '/how-to-delete-jeetbuzz-account'
      path: '/how-to-delete-jeetbuzz-account'
      fullPath: '/how-to-delete-jeetbuzz-account'
      preLoaderRoute: typeof HowToDeleteJeetbuzzAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fact-checking': {
      id: '/fact-checking'
      path: '/fact-checking'
      fullPath: '/fact-checking'
      preLoaderRoute: typeof FactCheckingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/easypaisa-guide': {
      id: '/easypaisa-guide'
      path: '/easypaisa-guide'
      fullPath: '/easypaisa-guide'
      preLoaderRoute: typeof EasypaisaGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit-withdrawal-guide': {
      id: '/deposit-withdrawal-guide'
      path: '/deposit-withdrawal-guide'
      fullPath: '/deposit-withdrawal-guide'
      preLoaderRoute: typeof DepositWithdrawalGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit-guide': {
      id: '/deposit-guide'
      path: '/deposit-guide'
      fullPath: '/deposit-guide'
      preLoaderRoute: typeof DepositGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket-exchange-guide': {
      id: '/cricket-exchange-guide'
      path: '/cricket-exchange-guide'
      fullPath: '/cricket-exchange-guide'
      preLoaderRoute: typeof CricketExchangeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-policy': {
      id: '/content-policy'
      path: '/content-policy'
      fullPath: '/content-policy'
      preLoaderRoute: typeof ContentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino-guide': {
      id: '/casino-guide'
      path: '/casino-guide'
      fullPath: '/casino-guide'
      preLoaderRoute: typeof CasinoGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonuses': {
      id: '/bonuses'
      path: '/bonuses'
      fullPath: '/bonuses'
      preLoaderRoute: typeof BonusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus-and-promotions': {
      id: '/bonus-and-promotions'
      path: '/bonus-and-promotions'
      fullPath: '/bonus-and-promotions'
      preLoaderRoute: typeof BonusAndPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bkash-guide': {
      id: '/bkash-guide'
      path: '/bkash-guide'
      fullPath: '/bkash-guide'
      preLoaderRoute: typeof BkashGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviator-guide': {
      id: '/aviator-guide'
      path: '/aviator-guide'
      fullPath: '/aviator-guide'
      preLoaderRoute: typeof AviatorGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apk-download-guide': {
      id: '/apk-download-guide'
      path: '/apk-download-guide'
      fullPath: '/apk-download-guide'
      preLoaderRoute: typeof ApkDownloadGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android-web-app-guide': {
      id: '/android-web-app-guide'
      path: '/android-web-app-guide'
      fullPath: '/android-web-app-guide'
      preLoaderRoute: typeof AndroidWebAppGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-earning-guide': {
      id: '/agent-earning-guide'
      path: '/agent-earning-guide'
      fullPath: '/agent-earning-guide'
      preLoaderRoute: typeof AgentEarningGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-program': {
      id: '/affiliate-program'
      path: '/affiliate-program'
      fullPath: '/affiliate-program'
      preLoaderRoute: typeof AffiliateProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-login': {
      id: '/affiliate-login'
      path: '/affiliate-login'
      fullPath: '/affiliate-login'
      preLoaderRoute: typeof AffiliateLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/go/signup': {
      id: '/go/signup'
      path: '/go/signup'
      fullPath: '/go/signup'
      preLoaderRoute: typeof GoSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/login': {
      id: '/go/login'
      path: '/go/login'
      fullPath: '/go/login'
      preLoaderRoute: typeof GoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/affiliate': {
      id: '/go/affiliate'
      path: '/go/affiliate'
      fullPath: '/go/affiliate'
      preLoaderRoute: typeof GoAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/app/launch': {
      id: '/app/launch'
      path: '/app/launch'
      fullPath: '/app/launch'
      preLoaderRoute: typeof AppLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/$lang/': {
      id: '/$country/$lang/'
      path: '/$country/$lang'
      fullPath: '/$country/$lang/'
      preLoaderRoute: typeof CountryLangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/$lang/$': {
      id: '/$country/$lang/$'
      path: '/$country/$lang/$'
      fullPath: '/$country/$lang/$'
      preLoaderRoute: typeof CountryLangSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  AffiliateLoginRoute: AffiliateLoginRoute,
  AffiliateProgramRoute: AffiliateProgramRoute,
  AgentEarningGuideRoute: AgentEarningGuideRoute,
  AndroidWebAppGuideRoute: AndroidWebAppGuideRoute,
  ApkDownloadGuideRoute: ApkDownloadGuideRoute,
  AuthorRoute: AuthorRoute,
  AviatorGuideRoute: AviatorGuideRoute,
  BkashGuideRoute: BkashGuideRoute,
  BlogRoute: BlogRouteWithChildren,
  BonusAndPromotionsRoute: BonusAndPromotionsRoute,
  BonusesRoute: BonusesRoute,
  CasinoGuideRoute: CasinoGuideRoute,
  ContactRoute: ContactRoute,
  ContentPolicyRoute: ContentPolicyRoute,
  CricketExchangeGuideRoute: CricketExchangeGuideRoute,
  DepositGuideRoute: DepositGuideRoute,
  DepositWithdrawalGuideRoute: DepositWithdrawalGuideRoute,
  DownloadRoute: DownloadRoute,
  EasypaisaGuideRoute: EasypaisaGuideRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FactCheckingRoute: FactCheckingRoute,
  FaqRoute: FaqRoute,
  GamesRoute: GamesRoute,
  HelpRoute: HelpRoute,
  HowToDeleteJeetbuzzAccountRoute: HowToDeleteJeetbuzzAccountRoute,
  IosAppGuideRoute: IosAppGuideRoute,
  IsJeetbuzzSafeRoute: IsJeetbuzzSafeRoute,
  JazzcashGuideRoute: JazzcashGuideRoute,
  JeetBuzzRoute: JeetBuzzRoute,
  JeetbuzRoute: JeetbuzRoute,
  JeetbuzzAccountLockedRoute: JeetbuzzAccountLockedRoute,
  JeetbuzzAccountVerificationRoute: JeetbuzzAccountVerificationRoute,
  JeetbuzzAffiliateAppRoute: JeetbuzzAffiliateAppRoute,
  JeetbuzzAffiliateCommissionRoute: JeetbuzzAffiliateCommissionRoute,
  JeetbuzzAffiliateCommissionRateRoute: JeetbuzzAffiliateCommissionRateRoute,
  JeetbuzzAffiliateDashboardRoute: JeetbuzzAffiliateDashboardRoute,
  JeetbuzzAffiliatePaymentMethodsRoute: JeetbuzzAffiliatePaymentMethodsRoute,
  JeetbuzzAffiliateSignupRoute: JeetbuzzAffiliateSignupRoute,
  JeetbuzzAffiliateWithdrawalRoute: JeetbuzzAffiliateWithdrawalRoute,
  JeetbuzzAlternativesRoute: JeetbuzzAlternativesRoute,
  JeetbuzzApkDownloadRoute: JeetbuzzApkDownloadRoute,
  JeetbuzzAppNotOpeningRoute: JeetbuzzAppNotOpeningRoute,
  JeetbuzzAppUpdateRoute: JeetbuzzAppUpdateRoute,
  JeetbuzzBkashDepositRoute: JeetbuzzBkashDepositRoute,
  JeetbuzzComLoginRoute: JeetbuzzComLoginRoute,
  JeetbuzzDepositFailedRoute: JeetbuzzDepositFailedRoute,
  JeetbuzzDepositProblemRoute: JeetbuzzDepositProblemRoute,
  JeetbuzzDownloadForAndroidRoute: JeetbuzzDownloadForAndroidRoute,
  JeetbuzzDownloadForIosRoute: JeetbuzzDownloadForIosRoute,
  JeetbuzzFirstDepositBonusRoute: JeetbuzzFirstDepositBonusRoute,
  JeetbuzzLiveCricketRoute: JeetbuzzLiveCricketRoute,
  JeetbuzzMinimumDepositRoute: JeetbuzzMinimumDepositRoute,
  JeetbuzzNagadWithdrawalRoute: JeetbuzzNagadWithdrawalRoute,
  JeetbuzzOtpNotReceivedRoute: JeetbuzzOtpNotReceivedRoute,
  JeetbuzzPartnerLoginRoute: JeetbuzzPartnerLoginRoute,
  JeetbuzzPasswordResetRoute: JeetbuzzPasswordResetRoute,
  JeetbuzzPromoCodeRoute: JeetbuzzPromoCodeRoute,
  JeetbuzzReferBonusRoute: JeetbuzzReferBonusRoute,
  JeetbuzzReferralCodeRoute: JeetbuzzReferralCodeRoute,
  JeetbuzzReviewRoute: JeetbuzzReviewRoute,
  JeetbuzzSignUpRoute: JeetbuzzSignUpRoute,
  JeetbuzzWithdrawalPendingRoute: JeetbuzzWithdrawalPendingRoute,
  JeetbuzzWithdrawalTimeRoute: JeetbuzzWithdrawalTimeRoute,
  JestBuzzRoute: JestBuzzRoute,
  JetbuzzRoute: JetbuzzRoute,
  JitbuzzRoute: JitbuzzRoute,
  LiveCricketBettingRoute: LiveCricketBettingRoute,
  LoginRoute: LoginRoute,
  LoginGuideRoute: LoginGuideRoute,
  LoginProblemsRoute: LoginProblemsRoute,
  LoginSecurityRoute: LoginSecurityRoute,
  MobileAppGuideRoute: MobileAppGuideRoute,
  NagadGuideRoute: NagadGuideRoute,
  PasswordResetRoute: PasswordResetRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  PaymentsRoute: PaymentsRoute,
  PaytmGuideRoute: PaytmGuideRoute,
  PhonepeGuideRoute: PhonepeGuideRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  RegistrationGuideRoute: RegistrationGuideRoute,
  ResponsibleGamingRoute: ResponsibleGamingRoute,
  ReviewPolicyRoute: ReviewPolicyRoute,
  RocketGuideRoute: RocketGuideRoute,
  SecurityGuideRoute: SecurityGuideRoute,
  SignupRoute: SignupRoute,
  SitemapAffiliateDotxmlRoute: SitemapAffiliateDotxmlRoute,
  SitemapBdDotxmlRoute: SitemapBdDotxmlRoute,
  SitemapBlogDotxmlRoute: SitemapBlogDotxmlRoute,
  SitemapGuidesDotxmlRoute: SitemapGuidesDotxmlRoute,
  SitemapInDotxmlRoute: SitemapInDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapPaymentsDotxmlRoute: SitemapPaymentsDotxmlRoute,
  SitemapPkDotxmlRoute: SitemapPkDotxmlRoute,
  SitemapSolutionsDotxmlRoute: SitemapSolutionsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsBettingRoute: SportsBettingRoute,
  TermsRoute: TermsRoute,
  UpdatePolicyRoute: UpdatePolicyRoute,
  UpiGuideRoute: UpiGuideRoute,
  VerificationRoute: VerificationRoute,
  VipProgramRoute: VipProgramRoute,
  WelcomeBonusRoute: WelcomeBonusRoute,
  WithdrawalGuideRoute: WithdrawalGuideRoute,
  Char2460Char2495Char2468Char2476Char2494Char2460Route:
    Char2460Char2495Char2468Char2476Char2494Char2460Route,
  AppLaunchRoute: AppLaunchRoute,
  GoAffiliateRoute: GoAffiliateRoute,
  GoLoginRoute: GoLoginRoute,
  GoSignupRoute: GoSignupRoute,
  CountryLangSplatRoute: CountryLangSplatRoute,
  CountryLangIndexRoute: CountryLangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
