/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawalGuideRouteImport } from './routes/withdrawal-guide'
import { Route as WelcomeBonusRouteImport } from './routes/welcome-bonus'
import { Route as VipProgramRouteImport } from './routes/vip-program'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as UpdatePolicyRouteImport } from './routes/update-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SportsBettingRouteImport } from './routes/sports-betting'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityGuideRouteImport } from './routes/security-guide'
import { Route as RocketGuideRouteImport } from './routes/rocket-guide'
import { Route as ReviewPolicyRouteImport } from './routes/review-policy'
import { Route as ResponsibleGamingRouteImport } from './routes/responsible-gaming'
import { Route as RegistrationGuideRouteImport } from './routes/registration-guide'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as NagadGuideRouteImport } from './routes/nagad-guide'
import { Route as MobileAppGuideRouteImport } from './routes/mobile-app-guide'
import { Route as LoginSecurityRouteImport } from './routes/login-security'
import { Route as LoginProblemsRouteImport } from './routes/login-problems'
import { Route as LoginGuideRouteImport } from './routes/login-guide'
import { Route as LiveCricketBettingRouteImport } from './routes/live-cricket-betting'
import { Route as JeetbuzzReviewRouteImport } from './routes/jeetbuzz-review'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FactCheckingRouteImport } from './routes/fact-checking'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as DepositWithdrawalGuideRouteImport } from './routes/deposit-withdrawal-guide'
import { Route as DepositGuideRouteImport } from './routes/deposit-guide'
import { Route as ContentPolicyRouteImport } from './routes/content-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CasinoGuideRouteImport } from './routes/casino-guide'
import { Route as BonusAndPromotionsRouteImport } from './routes/bonus-and-promotions'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BkashGuideRouteImport } from './routes/bkash-guide'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as ApkDownloadGuideRouteImport } from './routes/apk-download-guide'
import { Route as AffiliateProgramRouteImport } from './routes/affiliate-program'
import { Route as AffiliateLoginRouteImport } from './routes/affiliate-login'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as GoSignupRouteImport } from './routes/go.signup'
import { Route as GoLoginRouteImport } from './routes/go.login'
import { Route as GoAffiliateRouteImport } from './routes/go.affiliate'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CountryLangIndexRouteImport } from './routes/$country.$lang.index'
import { Route as CountryLangSplatRouteImport } from './routes/$country.$lang.$'

const WithdrawalGuideRoute = WithdrawalGuideRouteImport.update({
  id: '/withdrawal-guide',
  path: '/withdrawal-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeBonusRoute = WelcomeBonusRouteImport.update({
  id: '/welcome-bonus',
  path: '/welcome-bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const VipProgramRoute = VipProgramRouteImport.update({
  id: '/vip-program',
  path: '/vip-program',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePolicyRoute = UpdatePolicyRouteImport.update({
  id: '/update-policy',
  path: '/update-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsBettingRoute = SportsBettingRouteImport.update({
  id: '/sports-betting',
  path: '/sports-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityGuideRoute = SecurityGuideRouteImport.update({
  id: '/security-guide',
  path: '/security-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const RocketGuideRoute = RocketGuideRouteImport.update({
  id: '/rocket-guide',
  path: '/rocket-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewPolicyRoute = ReviewPolicyRouteImport.update({
  id: '/review-policy',
  path: '/review-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamingRoute = ResponsibleGamingRouteImport.update({
  id: '/responsible-gaming',
  path: '/responsible-gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationGuideRoute = RegistrationGuideRouteImport.update({
  id: '/registration-guide',
  path: '/registration-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const NagadGuideRoute = NagadGuideRouteImport.update({
  id: '/nagad-guide',
  path: '/nagad-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppGuideRoute = MobileAppGuideRouteImport.update({
  id: '/mobile-app-guide',
  path: '/mobile-app-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSecurityRoute = LoginSecurityRouteImport.update({
  id: '/login-security',
  path: '/login-security',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginProblemsRoute = LoginProblemsRouteImport.update({
  id: '/login-problems',
  path: '/login-problems',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginGuideRoute = LoginGuideRouteImport.update({
  id: '/login-guide',
  path: '/login-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveCricketBettingRoute = LiveCricketBettingRouteImport.update({
  id: '/live-cricket-betting',
  path: '/live-cricket-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const JeetbuzzReviewRoute = JeetbuzzReviewRouteImport.update({
  id: '/jeetbuzz-review',
  path: '/jeetbuzz-review',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FactCheckingRoute = FactCheckingRouteImport.update({
  id: '/fact-checking',
  path: '/fact-checking',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositWithdrawalGuideRoute = DepositWithdrawalGuideRouteImport.update({
  id: '/deposit-withdrawal-guide',
  path: '/deposit-withdrawal-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositGuideRoute = DepositGuideRouteImport.update({
  id: '/deposit-guide',
  path: '/deposit-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentPolicyRoute = ContentPolicyRouteImport.update({
  id: '/content-policy',
  path: '/content-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoGuideRoute = CasinoGuideRouteImport.update({
  id: '/casino-guide',
  path: '/casino-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusAndPromotionsRoute = BonusAndPromotionsRouteImport.update({
  id: '/bonus-and-promotions',
  path: '/bonus-and-promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BkashGuideRoute = BkashGuideRouteImport.update({
  id: '/bkash-guide',
  path: '/bkash-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const ApkDownloadGuideRoute = ApkDownloadGuideRouteImport.update({
  id: '/apk-download-guide',
  path: '/apk-download-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateProgramRoute = AffiliateProgramRouteImport.update({
  id: '/affiliate-program',
  path: '/affiliate-program',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateLoginRoute = AffiliateLoginRouteImport.update({
  id: '/affiliate-login',
  path: '/affiliate-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const GoSignupRoute = GoSignupRouteImport.update({
  id: '/go/signup',
  path: '/go/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLoginRoute = GoLoginRouteImport.update({
  id: '/go/login',
  path: '/go/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GoAffiliateRoute = GoAffiliateRouteImport.update({
  id: '/go/affiliate',
  path: '/go/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CountryLangIndexRoute = CountryLangIndexRouteImport.update({
  id: '/$country/$lang/',
  path: '/$country/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryLangSplatRoute = CountryLangSplatRouteImport.update({
  id: '/$country/$lang/$',
  path: '/$country/$lang/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/affiliate-login': typeof AffiliateLoginRoute
  '/affiliate-program': typeof AffiliateProgramRoute
  '/apk-download-guide': typeof ApkDownloadGuideRoute
  '/author': typeof AuthorRoute
  '/bkash-guide': typeof BkashGuideRoute
  '/blog': typeof BlogRouteWithChildren
  '/bonus-and-promotions': typeof BonusAndPromotionsRoute
  '/casino-guide': typeof CasinoGuideRoute
  '/contact': typeof ContactRoute
  '/content-policy': typeof ContentPolicyRoute
  '/deposit-guide': typeof DepositGuideRoute
  '/deposit-withdrawal-guide': typeof DepositWithdrawalGuideRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking': typeof FactCheckingRoute
  '/faq': typeof FaqRoute
  '/jeetbuzz-review': typeof JeetbuzzReviewRoute
  '/live-cricket-betting': typeof LiveCricketBettingRoute
  '/login-guide': typeof LoginGuideRoute
  '/login-problems': typeof LoginProblemsRoute
  '/login-security': typeof LoginSecurityRoute
  '/mobile-app-guide': typeof MobileAppGuideRoute
  '/nagad-guide': typeof NagadGuideRoute
  '/password-reset': typeof PasswordResetRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/registration-guide': typeof RegistrationGuideRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/review-policy': typeof ReviewPolicyRoute
  '/rocket-guide': typeof RocketGuideRoute
  '/security-guide': typeof SecurityGuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports-betting': typeof SportsBettingRoute
  '/terms': typeof TermsRoute
  '/update-policy': typeof UpdatePolicyRoute
  '/verification': typeof VerificationRoute
  '/vip-program': typeof VipProgramRoute
  '/welcome-bonus': typeof WelcomeBonusRoute
  '/withdrawal-guide': typeof WithdrawalGuideRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/affiliate': typeof GoAffiliateRoute
  '/go/login': typeof GoLoginRoute
  '/go/signup': typeof GoSignupRoute
  '/blog/': typeof BlogIndexRoute
  '/$country/$lang/$': typeof CountryLangSplatRoute
  '/$country/$lang/': typeof CountryLangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/affiliate-login': typeof AffiliateLoginRoute
  '/affiliate-program': typeof AffiliateProgramRoute
  '/apk-download-guide': typeof ApkDownloadGuideRoute
  '/author': typeof AuthorRoute
  '/bkash-guide': typeof BkashGuideRoute
  '/bonus-and-promotions': typeof BonusAndPromotionsRoute
  '/casino-guide': typeof CasinoGuideRoute
  '/contact': typeof ContactRoute
  '/content-policy': typeof ContentPolicyRoute
  '/deposit-guide': typeof DepositGuideRoute
  '/deposit-withdrawal-guide': typeof DepositWithdrawalGuideRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking': typeof FactCheckingRoute
  '/faq': typeof FaqRoute
  '/jeetbuzz-review': typeof JeetbuzzReviewRoute
  '/live-cricket-betting': typeof LiveCricketBettingRoute
  '/login-guide': typeof LoginGuideRoute
  '/login-problems': typeof LoginProblemsRoute
  '/login-security': typeof LoginSecurityRoute
  '/mobile-app-guide': typeof MobileAppGuideRoute
  '/nagad-guide': typeof NagadGuideRoute
  '/password-reset': typeof PasswordResetRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/registration-guide': typeof RegistrationGuideRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/review-policy': typeof ReviewPolicyRoute
  '/rocket-guide': typeof RocketGuideRoute
  '/security-guide': typeof SecurityGuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports-betting': typeof SportsBettingRoute
  '/terms': typeof TermsRoute
  '/update-policy': typeof UpdatePolicyRoute
  '/verification': typeof VerificationRoute
  '/vip-program': typeof VipProgramRoute
  '/welcome-bonus': typeof WelcomeBonusRoute
  '/withdrawal-guide': typeof WithdrawalGuideRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/affiliate': typeof GoAffiliateRoute
  '/go/login': typeof GoLoginRoute
  '/go/signup': typeof GoSignupRoute
  '/blog': typeof BlogIndexRoute
  '/$country/$lang/$': typeof CountryLangSplatRoute
  '/$country/$lang': typeof CountryLangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/affiliate-login': typeof AffiliateLoginRoute
  '/affiliate-program': typeof AffiliateProgramRoute
  '/apk-download-guide': typeof ApkDownloadGuideRoute
  '/author': typeof AuthorRoute
  '/bkash-guide': typeof BkashGuideRoute
  '/blog': typeof BlogRouteWithChildren
  '/bonus-and-promotions': typeof BonusAndPromotionsRoute
  '/casino-guide': typeof CasinoGuideRoute
  '/contact': typeof ContactRoute
  '/content-policy': typeof ContentPolicyRoute
  '/deposit-guide': typeof DepositGuideRoute
  '/deposit-withdrawal-guide': typeof DepositWithdrawalGuideRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking': typeof FactCheckingRoute
  '/faq': typeof FaqRoute
  '/jeetbuzz-review': typeof JeetbuzzReviewRoute
  '/live-cricket-betting': typeof LiveCricketBettingRoute
  '/login-guide': typeof LoginGuideRoute
  '/login-problems': typeof LoginProblemsRoute
  '/login-security': typeof LoginSecurityRoute
  '/mobile-app-guide': typeof MobileAppGuideRoute
  '/nagad-guide': typeof NagadGuideRoute
  '/password-reset': typeof PasswordResetRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/registration-guide': typeof RegistrationGuideRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/review-policy': typeof ReviewPolicyRoute
  '/rocket-guide': typeof RocketGuideRoute
  '/security-guide': typeof SecurityGuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports-betting': typeof SportsBettingRoute
  '/terms': typeof TermsRoute
  '/update-policy': typeof UpdatePolicyRoute
  '/verification': typeof VerificationRoute
  '/vip-program': typeof VipProgramRoute
  '/welcome-bonus': typeof WelcomeBonusRoute
  '/withdrawal-guide': typeof WithdrawalGuideRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/affiliate': typeof GoAffiliateRoute
  '/go/login': typeof GoLoginRoute
  '/go/signup': typeof GoSignupRoute
  '/blog/': typeof BlogIndexRoute
  '/$country/$lang/$': typeof CountryLangSplatRoute
  '/$country/$lang/': typeof CountryLangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/affiliate-login'
    | '/affiliate-program'
    | '/apk-download-guide'
    | '/author'
    | '/bkash-guide'
    | '/blog'
    | '/bonus-and-promotions'
    | '/casino-guide'
    | '/contact'
    | '/content-policy'
    | '/deposit-guide'
    | '/deposit-withdrawal-guide'
    | '/editorial-policy'
    | '/fact-checking'
    | '/faq'
    | '/jeetbuzz-review'
    | '/live-cricket-betting'
    | '/login-guide'
    | '/login-problems'
    | '/login-security'
    | '/mobile-app-guide'
    | '/nagad-guide'
    | '/password-reset'
    | '/payment-methods'
    | '/privacy-policy'
    | '/registration-guide'
    | '/responsible-gaming'
    | '/review-policy'
    | '/rocket-guide'
    | '/security-guide'
    | '/sitemap.xml'
    | '/sports-betting'
    | '/terms'
    | '/update-policy'
    | '/verification'
    | '/vip-program'
    | '/welcome-bonus'
    | '/withdrawal-guide'
    | '/blog/$slug'
    | '/go/affiliate'
    | '/go/login'
    | '/go/signup'
    | '/blog/'
    | '/$country/$lang/$'
    | '/$country/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/affiliate-login'
    | '/affiliate-program'
    | '/apk-download-guide'
    | '/author'
    | '/bkash-guide'
    | '/bonus-and-promotions'
    | '/casino-guide'
    | '/contact'
    | '/content-policy'
    | '/deposit-guide'
    | '/deposit-withdrawal-guide'
    | '/editorial-policy'
    | '/fact-checking'
    | '/faq'
    | '/jeetbuzz-review'
    | '/live-cricket-betting'
    | '/login-guide'
    | '/login-problems'
    | '/login-security'
    | '/mobile-app-guide'
    | '/nagad-guide'
    | '/password-reset'
    | '/payment-methods'
    | '/privacy-policy'
    | '/registration-guide'
    | '/responsible-gaming'
    | '/review-policy'
    | '/rocket-guide'
    | '/security-guide'
    | '/sitemap.xml'
    | '/sports-betting'
    | '/terms'
    | '/update-policy'
    | '/verification'
    | '/vip-program'
    | '/welcome-bonus'
    | '/withdrawal-guide'
    | '/blog/$slug'
    | '/go/affiliate'
    | '/go/login'
    | '/go/signup'
    | '/blog'
    | '/$country/$lang/$'
    | '/$country/$lang'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/affiliate-login'
    | '/affiliate-program'
    | '/apk-download-guide'
    | '/author'
    | '/bkash-guide'
    | '/blog'
    | '/bonus-and-promotions'
    | '/casino-guide'
    | '/contact'
    | '/content-policy'
    | '/deposit-guide'
    | '/deposit-withdrawal-guide'
    | '/editorial-policy'
    | '/fact-checking'
    | '/faq'
    | '/jeetbuzz-review'
    | '/live-cricket-betting'
    | '/login-guide'
    | '/login-problems'
    | '/login-security'
    | '/mobile-app-guide'
    | '/nagad-guide'
    | '/password-reset'
    | '/payment-methods'
    | '/privacy-policy'
    | '/registration-guide'
    | '/responsible-gaming'
    | '/review-policy'
    | '/rocket-guide'
    | '/security-guide'
    | '/sitemap.xml'
    | '/sports-betting'
    | '/terms'
    | '/update-policy'
    | '/verification'
    | '/vip-program'
    | '/welcome-bonus'
    | '/withdrawal-guide'
    | '/blog/$slug'
    | '/go/affiliate'
    | '/go/login'
    | '/go/signup'
    | '/blog/'
    | '/$country/$lang/$'
    | '/$country/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  AffiliateLoginRoute: typeof AffiliateLoginRoute
  AffiliateProgramRoute: typeof AffiliateProgramRoute
  ApkDownloadGuideRoute: typeof ApkDownloadGuideRoute
  AuthorRoute: typeof AuthorRoute
  BkashGuideRoute: typeof BkashGuideRoute
  BlogRoute: typeof BlogRouteWithChildren
  BonusAndPromotionsRoute: typeof BonusAndPromotionsRoute
  CasinoGuideRoute: typeof CasinoGuideRoute
  ContactRoute: typeof ContactRoute
  ContentPolicyRoute: typeof ContentPolicyRoute
  DepositGuideRoute: typeof DepositGuideRoute
  DepositWithdrawalGuideRoute: typeof DepositWithdrawalGuideRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FactCheckingRoute: typeof FactCheckingRoute
  FaqRoute: typeof FaqRoute
  JeetbuzzReviewRoute: typeof JeetbuzzReviewRoute
  LiveCricketBettingRoute: typeof LiveCricketBettingRoute
  LoginGuideRoute: typeof LoginGuideRoute
  LoginProblemsRoute: typeof LoginProblemsRoute
  LoginSecurityRoute: typeof LoginSecurityRoute
  MobileAppGuideRoute: typeof MobileAppGuideRoute
  NagadGuideRoute: typeof NagadGuideRoute
  PasswordResetRoute: typeof PasswordResetRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegistrationGuideRoute: typeof RegistrationGuideRoute
  ResponsibleGamingRoute: typeof ResponsibleGamingRoute
  ReviewPolicyRoute: typeof ReviewPolicyRoute
  RocketGuideRoute: typeof RocketGuideRoute
  SecurityGuideRoute: typeof SecurityGuideRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsBettingRoute: typeof SportsBettingRoute
  TermsRoute: typeof TermsRoute
  UpdatePolicyRoute: typeof UpdatePolicyRoute
  VerificationRoute: typeof VerificationRoute
  VipProgramRoute: typeof VipProgramRoute
  WelcomeBonusRoute: typeof WelcomeBonusRoute
  WithdrawalGuideRoute: typeof WithdrawalGuideRoute
  GoAffiliateRoute: typeof GoAffiliateRoute
  GoLoginRoute: typeof GoLoginRoute
  GoSignupRoute: typeof GoSignupRoute
  CountryLangSplatRoute: typeof CountryLangSplatRoute
  CountryLangIndexRoute: typeof CountryLangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdrawal-guide': {
      id: '/withdrawal-guide'
      path: '/withdrawal-guide'
      fullPath: '/withdrawal-guide'
      preLoaderRoute: typeof WithdrawalGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome-bonus': {
      id: '/welcome-bonus'
      path: '/welcome-bonus'
      fullPath: '/welcome-bonus'
      preLoaderRoute: typeof WelcomeBonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-program': {
      id: '/vip-program'
      path: '/vip-program'
      fullPath: '/vip-program'
      preLoaderRoute: typeof VipProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-policy': {
      id: '/update-policy'
      path: '/update-policy'
      fullPath: '/update-policy'
      preLoaderRoute: typeof UpdatePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-betting': {
      id: '/sports-betting'
      path: '/sports-betting'
      fullPath: '/sports-betting'
      preLoaderRoute: typeof SportsBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-guide': {
      id: '/security-guide'
      path: '/security-guide'
      fullPath: '/security-guide'
      preLoaderRoute: typeof SecurityGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rocket-guide': {
      id: '/rocket-guide'
      path: '/rocket-guide'
      fullPath: '/rocket-guide'
      preLoaderRoute: typeof RocketGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-policy': {
      id: '/review-policy'
      path: '/review-policy'
      fullPath: '/review-policy'
      preLoaderRoute: typeof ReviewPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gaming': {
      id: '/responsible-gaming'
      path: '/responsible-gaming'
      fullPath: '/responsible-gaming'
      preLoaderRoute: typeof ResponsibleGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-guide': {
      id: '/registration-guide'
      path: '/registration-guide'
      fullPath: '/registration-guide'
      preLoaderRoute: typeof RegistrationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nagad-guide': {
      id: '/nagad-guide'
      path: '/nagad-guide'
      fullPath: '/nagad-guide'
      preLoaderRoute: typeof NagadGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-app-guide': {
      id: '/mobile-app-guide'
      path: '/mobile-app-guide'
      fullPath: '/mobile-app-guide'
      preLoaderRoute: typeof MobileAppGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-security': {
      id: '/login-security'
      path: '/login-security'
      fullPath: '/login-security'
      preLoaderRoute: typeof LoginSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-problems': {
      id: '/login-problems'
      path: '/login-problems'
      fullPath: '/login-problems'
      preLoaderRoute: typeof LoginProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-guide': {
      id: '/login-guide'
      path: '/login-guide'
      fullPath: '/login-guide'
      preLoaderRoute: typeof LoginGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-cricket-betting': {
      id: '/live-cricket-betting'
      path: '/live-cricket-betting'
      fullPath: '/live-cricket-betting'
      preLoaderRoute: typeof LiveCricketBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeetbuzz-review': {
      id: '/jeetbuzz-review'
      path: '/jeetbuzz-review'
      fullPath: '/jeetbuzz-review'
      preLoaderRoute: typeof JeetbuzzReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fact-checking': {
      id: '/fact-checking'
      path: '/fact-checking'
      fullPath: '/fact-checking'
      preLoaderRoute: typeof FactCheckingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit-withdrawal-guide': {
      id: '/deposit-withdrawal-guide'
      path: '/deposit-withdrawal-guide'
      fullPath: '/deposit-withdrawal-guide'
      preLoaderRoute: typeof DepositWithdrawalGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit-guide': {
      id: '/deposit-guide'
      path: '/deposit-guide'
      fullPath: '/deposit-guide'
      preLoaderRoute: typeof DepositGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-policy': {
      id: '/content-policy'
      path: '/content-policy'
      fullPath: '/content-policy'
      preLoaderRoute: typeof ContentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino-guide': {
      id: '/casino-guide'
      path: '/casino-guide'
      fullPath: '/casino-guide'
      preLoaderRoute: typeof CasinoGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus-and-promotions': {
      id: '/bonus-and-promotions'
      path: '/bonus-and-promotions'
      fullPath: '/bonus-and-promotions'
      preLoaderRoute: typeof BonusAndPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bkash-guide': {
      id: '/bkash-guide'
      path: '/bkash-guide'
      fullPath: '/bkash-guide'
      preLoaderRoute: typeof BkashGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apk-download-guide': {
      id: '/apk-download-guide'
      path: '/apk-download-guide'
      fullPath: '/apk-download-guide'
      preLoaderRoute: typeof ApkDownloadGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-program': {
      id: '/affiliate-program'
      path: '/affiliate-program'
      fullPath: '/affiliate-program'
      preLoaderRoute: typeof AffiliateProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-login': {
      id: '/affiliate-login'
      path: '/affiliate-login'
      fullPath: '/affiliate-login'
      preLoaderRoute: typeof AffiliateLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/go/signup': {
      id: '/go/signup'
      path: '/go/signup'
      fullPath: '/go/signup'
      preLoaderRoute: typeof GoSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/login': {
      id: '/go/login'
      path: '/go/login'
      fullPath: '/go/login'
      preLoaderRoute: typeof GoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/affiliate': {
      id: '/go/affiliate'
      path: '/go/affiliate'
      fullPath: '/go/affiliate'
      preLoaderRoute: typeof GoAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/$country/$lang/': {
      id: '/$country/$lang/'
      path: '/$country/$lang'
      fullPath: '/$country/$lang/'
      preLoaderRoute: typeof CountryLangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/$lang/$': {
      id: '/$country/$lang/$'
      path: '/$country/$lang/$'
      fullPath: '/$country/$lang/$'
      preLoaderRoute: typeof CountryLangSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  AffiliateLoginRoute: AffiliateLoginRoute,
  AffiliateProgramRoute: AffiliateProgramRoute,
  ApkDownloadGuideRoute: ApkDownloadGuideRoute,
  AuthorRoute: AuthorRoute,
  BkashGuideRoute: BkashGuideRoute,
  BlogRoute: BlogRouteWithChildren,
  BonusAndPromotionsRoute: BonusAndPromotionsRoute,
  CasinoGuideRoute: CasinoGuideRoute,
  ContactRoute: ContactRoute,
  ContentPolicyRoute: ContentPolicyRoute,
  DepositGuideRoute: DepositGuideRoute,
  DepositWithdrawalGuideRoute: DepositWithdrawalGuideRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FactCheckingRoute: FactCheckingRoute,
  FaqRoute: FaqRoute,
  JeetbuzzReviewRoute: JeetbuzzReviewRoute,
  LiveCricketBettingRoute: LiveCricketBettingRoute,
  LoginGuideRoute: LoginGuideRoute,
  LoginProblemsRoute: LoginProblemsRoute,
  LoginSecurityRoute: LoginSecurityRoute,
  MobileAppGuideRoute: MobileAppGuideRoute,
  NagadGuideRoute: NagadGuideRoute,
  PasswordResetRoute: PasswordResetRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegistrationGuideRoute: RegistrationGuideRoute,
  ResponsibleGamingRoute: ResponsibleGamingRoute,
  ReviewPolicyRoute: ReviewPolicyRoute,
  RocketGuideRoute: RocketGuideRoute,
  SecurityGuideRoute: SecurityGuideRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsBettingRoute: SportsBettingRoute,
  TermsRoute: TermsRoute,
  UpdatePolicyRoute: UpdatePolicyRoute,
  VerificationRoute: VerificationRoute,
  VipProgramRoute: VipProgramRoute,
  WelcomeBonusRoute: WelcomeBonusRoute,
  WithdrawalGuideRoute: WithdrawalGuideRoute,
  GoAffiliateRoute: GoAffiliateRoute,
  GoLoginRoute: GoLoginRoute,
  GoSignupRoute: GoSignupRoute,
  CountryLangSplatRoute: CountryLangSplatRoute,
  CountryLangIndexRoute: CountryLangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
